### ISSUE TITLE
Introducing docker compose version 2 format broke multi-cluster setup

### ISSUE THREAD

**Issue by Xaerxess** [wurstmeister/kafka-docker#106]
Since commit cba65a10cda6759d1676c3fb46731e4c4aa560ee, which introduced docker compose version 2 format, zookeeper is bound to its standard port 2181 in contrast to dynamically assigned port in earlier version. Previous configuration enabled multi-cluster setup, i.e.

```
for num in '' 2 3; do docker-compose -p kafkadocker$num up -d; done
```

which I used to setup three kafka+zookeeper clusters. Currenlty, due to hardcoded port, it's not possible. Can you revert previous configuration regarding Zookeeper port?

**Comment by sscaling** [comment]
@Xaerxess - Could you provide a bit more information on why this use-case is useful? Thanks.

**Comment by Xaerxess** [comment]
Obviously until now we have a workaround for that. Having said that, I count this issue as regression, as it was something which worked previously and doesn't now.

**Comment by sscaling** [comment]
Bringing up 3 clusters on a single node seems an unusual configuration (and not one that I would think is suitable for production). So I was just trying to understand what the use-case for this setup is.

As far as I am concerned, we could remove the static host binding for zookeeper in the example `docker-compose.yml` file, but i'm just not sure of the benefit. Other people might like the convenience of being able to access the zookeeper instance on a known port for operational purposes etc.

**Comment by Xaerxess** [comment]
It was definitely a developer environment setup, so I guess it's not a "real world" use case. 

Besides a valid point regarding custom zookeeper I don't think you need to worry about this issue. Relevant xkcd for reference: 

![Workflow](https://imgs.xkcd.com/comics/workflow_2x.png)

(Although I don't need the heating anymore ;))

**Comment by sscaling** [comment]
OK, will leave as-is and close the issue. Thanks for replying!
