### ISSUE TITLE
A docker compose error regarding 'kafka' failed to build

### ISSUE THREAD

**Issue by easysun** [wurstmeister/kafka-docker#107]
When I clone and run this command:
`docker-compose up`

An error has occurred on Step 7.

> ERROR: Service 'kafka' failed to build: The command '/bin/sh -c /tmp/download-kafka.sh && tar xfz /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz -C /opt && rm /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz' returned a non-zero code: 8
> How to solve it?

**Comment by gaconkzk** [comment]
I got same error

**Comment by ynqa** [comment]
After you put the following command on the appropriate directory, you can execute `docker-compose up`

`find . -print | xargs chmod 777`

Probably, the authorities of the shell files on containers are the same as themselves on local environment. So, you need to change them to be able to execute.

**Comment by prayagupd** [comment]
I got the same error, 

```
Step 3 : RUN apk add --update unzip wget curl docker jq coreutils
 ---> Running in ea2aa8d5e315
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.4/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.167438ca.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.4/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.a2e6dac0.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  coreutils (missing):
    required by: world[coreutils]
  curl (missing):
    required by: world[curl]
  docker (missing):
    required by: world[docker]
  jq (missing):
    required by: world[jq]
  unzip (missing):
    required by: world[unzip]
  wget (missing):
    required by: world[wget]
ERROR: Service 'kafka' failed to build: The command '/bin/sh -c apk add --update unzip wget curl docker jq coreutils' returned a non-zero code: 6
```

**Comment by ZmeiGorynych** [comment]
I get a very similar error (see below). The puzzling thing is it ran fine the first time I tried it, but not a single time since! 

Running Docker Toolbox on Windows 10 Home

```
Step 5 : ADD download-kafka.sh /tmp/download-kafka.sh
 ---> Using cache
 ---> 417070951425
Step 6 : RUN chmod a+x /tmp/download-kafka.sh && sync && /tmp/download-kafka.sh && tar xfz /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz -C /opt && rm /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz
 ---> Running in ac7d099418f1
[91m/bin/sh: /tmp/download-kafka.sh: not found[0m[91m
[0m[31mERROR[0m: Service 'kafka' failed to build: The command '/bin/sh -c chmod a+x /tmp/download-kafka.sh && sync && /tmp/download-kafka.sh && tar xfz /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz -C /opt && rm /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz' returned a non-zero code: 127
```

**Comment by cbaxley** [comment]
Yep. Same problem here on windows 10.

**Comment by Shuairan-** [comment]
If anyone else encounters this problem and it fails because of the download-kafka.sh script:
Split the lines up that include the script change the download cmd like so: 
```
RUN wget -q http://apache.mirrors.spacedump.net/kafka/"$KAFKA_VERSION"/kafka_"$SCALA_VERSION"-"$KAFKA_VERSION".tgz -O /tmp/kafka_"$SCALA_VERSION"-"$KAFKA_VERSION".tgz
RUN tar xfz /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz -C /opt 
RUN rm /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz && ln -s /opt/kafka_${SCALA_VERSION}-${KAFKA_VERSION} /opt/kafka
```

Worked for me at least.

**Comment by goanpao** [comment]
Just changed the $KAFKA_VERSION to kafka_version=0.11.0.2 and it worked for me

**Comment by sscaling** [comment]
As reported in other issues. This is actually a problem when the apache mirror cannot be determined. There is https://github.com/wurstmeister/kafka-docker/pull/270 to display an error message to help with this. Retrying should resolve issue.
