### ISSUE TITLE
[Feature Request] Add option to enable topic deletion

### ISSUE THREAD

**Issue by huylv** [wurstmeister/kafka-docker#109]
Hi,
Could you add an option to enable topic deletion? Kafka 0.8.2+ fully supports this feature as described [here](https://kafka.apache.org/082/ops.html).
Thanks.

**Comment by wurstmeister** [comment]
Hi, 

you can enable topic deletion just like any other property as documented here https://github.com/wurstmeister/kafka-docker#pre-requisites
