### ISSUE TITLE
Problematic default advertised port value

### ISSUE THREAD

**Issue by carsonip** [wurstmeister/kafka-docker#111]
I am receiving errors when I have not set the `KAFKA_ADVERTISED_PORT` in the Dockerfile. (Of course the docker image works perfectly when `KAFKA_ADVERTISED_PORT` is set correctly.) Looking into the scripts, I do not understand how does it work when the mentioned environment variable is not set.

Error message:

```
kafka          | [2016-08-03 18:36:57,837] FATAL  (kafka.Kafka$)
kafka          | org.apache.kafka.common.config.ConfigException: Invalid value  for configuration advertised.port: Not a number of type INT
kafka          |    at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:670)
kafka          |    at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:418)
kafka          |    at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:55)
kafka          |    at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:759)
kafka          |    at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:743)
kafka          |    at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:740)
kafka          |    at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:28)
kafka          |    at kafka.Kafka$.main(Kafka.scala:58)
kafka          |    at kafka.Kafka.main(Kafka.scala)

```

In `start-kafka.sh`, line 6:

``` sh
if [[ -z "$KAFKA_ADVERTISED_PORT" ]]; then
    export KAFKA_ADVERTISED_PORT=$(docker port `hostname` $KAFKA_PORT | sed -r "s/.*:(.*)/\1/g")
```

How it possible to run `docker port` inside the container? I am getting `Cannot connect to the Docker daemon. Is the docker daemon running on this host?` when I do this manually in bash. As far as I know, `docker port` only works in the host machine.

**Comment by sergeyjsg** [comment]
Having same issue on AWS

**Comment by kevinleeTCA** [comment]
normally we set KAFKA_ADVERTISED_PORT to be 9092 in environmental configuration, which might fix this problem.

**Comment by damienjoldersma** [comment]
Having same issue on AWS as well.

**Comment by BryceCicada** [comment]
In order for KAFKA_ADVERTISED_PORT to be automatically set, the container needs access to the docker instance running on the host machine.  It does this by connecting to the same socket that must be mapped as a volume.  

For me, I added the following to my docker-compose when deploying locally:

    kafka:
      image: wurstmeister/kafka:latest
      # ...
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

**Comment by sscaling** [comment]
Seems like this was answered by @BryceCicada. 

Connectivity documentation has been added for https://github.com/wurstmeister/kafka-docker/issues/291. 

Wiki page: https://github.com/wurstmeister/kafka-docker/wiki/Connectivity
