### ISSUE TITLE
Permission denied on Windows 

### ISSUE THREAD

**Issue by oscarnevarezleal** [wurstmeister/kafka-docker#112]
I got the following error when I  try to run docker compose on Windows 10.

docker -v
Docker version 1.12.0, build 8eab29e

docker-compose up -d

Building kafka
Step 1 : FROM anapsix/alpine-java
 ---> a029fff7dd31
Step 2 : MAINTAINER Wurstmeister
 ---> Using cache
 ---> d03aa951fe31
Step 3 : RUN apk add --update unzip wget curl docker jq coreutils
 ---> Using cache
 ---> 63747698d450
Step 4 : ENV KAFKA_VERSION "0.10.0.0" SCALA_VERSION "2.11"
 ---> Using cache
 ---> 3e68d04f0c44
Step 5 : ADD download-kafka.sh /tmp/download-kafka.sh
 ---> Using cache
 ---> e71c8041860d
Step 6 : RUN /tmp/download-kafka.sh && tar xfz /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz -C /opt && rm /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz
 ---> Running in 3d4190deec17
[91m/bin/sh: /tmp/download-kafka.sh: Permission denied
[0m[31mERROR[0m: Service 'kafka' failed to build: The command '/bin/sh -c /tmp/download-kafka.sh && tar xfz /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz -C /opt && rm /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz' returned a non-zero code: 126

**Comment by quartz55** [comment]
Although it's a dirty hack, adding `RUN chmod -R 777 /tmp` before the call to the .sh file worked

Here's the snippet:
```Dockerfile
...
ENV KAFKA_VERSION="0.10.0.0" SCALA_VERSION="2.11"
ADD download-kafka.sh /tmp/download-kafka.sh
RUN chmod -R 777 /tmp
RUN /tmp/download-kafka.sh && tar xfz /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz -C /opt && rm /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz
...
```

**Comment by oscarnevarezleal** [comment]
Solved, thnks!

**Comment by pascalnaber** [comment]
I'm having the same problem and was getting the Permission denied message.

After changing the dockerfile with the "dirty hack". I'm getting the following message: 
any idea how to solve this?
I've removed all containers and ran the dockerfile again. Same result.

Step 7 : RUN /tmp/download-kafka.sh && tar xfz /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz -C /opt && rm /tmp/kafka
_${SCALA_VERSION}-${KAFKA_VERSION}.tgz
 ---> Running in 4ed0c6b02be8
**/bin/sh: /tmp/download-kafka.sh: not found**
ERROR: Service 'kafka' failed to build: The command '/bin/sh -c /tmp/download-kafka.sh && tar xfz /tmp/kafka_${SCALA_VER
SION}-${KAFKA_VERSION}.tgz -C /opt && rm /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz' returned a non-zero code: 127

**Comment by wurstmeister** [comment]
this should be fixed since https://github.com/wurstmeister/kafka-docker/commit/72f15ba83041a2decd3110f83832f26e4dd6dde8

**Comment by beauzo** [comment]
@pascalnaber: I was bit by the same issue. If you're editing the files on Windows, make sure to check the file line endings are Unix before kicking off a docker build.

**Comment by evs-mdv** [comment]
@beauzo I have the same issue than @pascalnaber. I checked the line ending (LF) but that didn't solved the problem.

**Comment by beauzo** [comment]
@evs-mdv, have you tried to bash into the container to execute the commands manually? Does /tmp/download-kafka.sh exist in the container?
