### ISSUE TITLE
Reboot kafka without losing the data

### ISSUE THREAD

**Issue by alexcastano** [wurstmeister/kafka-docker#116]
Hello, I'm trying to stop a container and start a new one but keeping the logs. I create a volume to keep the data, but every time a container is created use a new folder with the docker container id not using at all the old data. I'd like to make backups, but I cannot use them later either.

I don't know if this is completely intentional or there is a way to achieve this that I didn't understand. The only way to keep the data is using a cluster and doing the reboot in each broker one by one, however this is more dangerous in my opinion, prone to errors and harder to maintain for our small infrastructure.

**Comment by hbjoylee** [comment]
kafka1:
    image: wurstmeister/kafka
    hostname: kk1
    ports:
        - 9092:9092
    environment:
        - KAFKA_ADVERTISED_PORT=9092
        - KAFKA_BROKER_ID=1
        - KAFKA_NUM_PARTITIONS=3
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./kafka:/kafka

Try use hostname option and make broker id static(less than 1000).

**Comment by alexcastano** [comment]
Thank you @hbjoylee 

The hostname did the trick!

**Comment by rafi5237** [comment]
am facing same issue , can you please elaborate how did you fixed it.
Thanks in advance
