### ISSUE TITLE
producer cannot send messages to broker

### ISSUE THREAD

**Issue by yong93** [wurstmeister/kafka-docker#129]
i have psychical server, where i have set the advertised.host.name to server ip, and do the port forwarding at the router. But the producer cannot connect to broker by using the dns.

this is the log
ERROR:pykafka.connection:Failed to connect to 192.168.1.3:9092
WARNING:pykafka.producer:Broker 192.168.1.3:9092 disconnected. Retrying.

**Comment by sscaling** [comment]
Please check the wiki page: https://github.com/wurstmeister/kafka-docker/wiki/Connectivity. This sounds like a configuration issue.

Closing due to staleness.
