### ISSUE TITLE
how can I increase zookeeper to set cluster of 3. I tried but not working.

### ISSUE THREAD

**Issue by anilnokia** [wurstmeister/kafka-docker#131]

**Comment by anilnokia** [comment]
I updated my yaml file.

version: '2'
services:
  zookeeper1:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  zookeeper2:
    image: wurstmeister/zookeeper
    ports:
      - "2182:2181"
  zookeeper3:
    image: wurstmeister/zookeeper
    ports:
      - "2183:2181"
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 135.104.238.197
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

3 zookeeper comes up fine. but when I try to create a topic on 2 and 3 zookeeper, it says no borkers available. for zookeeper 1, it works fine. 

Thanks,

**Comment by neverfox** [comment]
You're exposing 2181 to 2182 and 2183 to your docker _host_ but then expecting Kafka to connect to the named services "zookeeper2:2182" and "zookeeper3:2183". It should be "zookeeper2:2181" and "zookeeper3:2181". Containers don't connect to named services via exposed ports.

**Comment by sscaling** [comment]
Duplicates #46
