### ISSUE TITLE
How to restart the kafka after the config change in server.properties file

### ISSUE THREAD

**Issue by opiuman** [wurstmeister/kafka-docker#137]
I need to override some default setting in server.properties. That requires the restart of kafka to take the effect. However, the kafka is running as the PID 1 in the container. How can we restart the kafka service without destroying the container?

Or any way to pass the override property setting via env or params when starting the container?

**Comment by opiuman** [comment]
Saw it in ReadMe

**Comment by khle** [comment]
Where? How did you do it?
