### ISSUE TITLE
KAFKA_CREATE_TOPICS with existing topic values

### ISSUE THREAD

**Issue by pazams** [wurstmeister/kafka-docker#140]
If using KAFKA_CREATE_TOPICS environment variable to create topics that already exists, 
then it will render Kafka/ZK state invalid to produce or consume from.
The logs also show this error, but I think it is expected that the process should recover from this type of error.

**Comment by sscaling** [comment]
This was fixed by adding the `--if-not-exists` flag when creating topics.
