### ISSUE TITLE
/tmp/download-kafka.sh not found

### ISSUE THREAD

**Issue by nathanyeung** [wurstmeister/kafka-docker#142]
When I run docker-compose up -d I get the following error at the end after step 5. It seems like the file /tmp/download-kafka.sh was not created

```
←[91m/bin/sh: /tmp/download-kafka.sh: not found
←[0m←[31mERROR←[0m: Service 'kafka' failed to build: The command '/bin/sh -c chm
od a+x /tmp/download-kafka.sh && sync && /tmp/download-kafka.sh && tar xfz /tmp/
kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz -C /opt && rm /tmp/kafka_${SCALA_VER
SION}-${KAFKA_VERSION}.tgz' returned a non-zero code: 127
```

**Comment by basvandenbrink** [comment]
I have exactly the same problem on Windows:
```
PS C:\<path-to>\kafka-docker> docker-compose up
Building kafka
Step 1 : FROM anapsix/alpine-java
 ---> 7598ed87f3ef
Step 2 : MAINTAINER Wurstmeister
 ---> Using cache
 ---> 3e53ccbcd346
Step 3 : RUN apk add --update unzip wget curl docker jq coreutils
 ---> Using cache
 ---> 9ddccc8f0c8b
Step 4 : ENV KAFKA_VERSION "0.10.1.0" SCALA_VERSION "2.11"
 ---> Using cache
 ---> 8738b12871bf
Step 5 : ADD download-kafka.sh /tmp/download-kafka.sh
 ---> Using cache
 ---> c882f6ce5c2c
Step 6 : RUN chmod a+x /tmp/download-kafka.sh && sync && /tmp/download-kafka.sh && tar xfz /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz -C /opt && rm /tmp/kafka_${SCALA
_VERSION}-${KAFKA_VERSION}.tgz
 ---> Running in 9a3d4f327d51
/bin/sh: /tmp/download-kafka.sh: not found
ERROR: Service 'kafka' failed to build: The command '/bin/sh -c chmod a+x /tmp/download-kafka.sh && sync && /tmp/download-kafka.sh && tar xfz /tmp/kafka_${SCALA_VERSION}-${
KAFKA_VERSION}.tgz -C /opt && rm /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz' returned a non-zero code: 127
```

**Comment by nathanyeung** [comment]
@basvandenbrink Looks like there's a solution for this onhttps://github.com/wurstmeister/kafka-docker/issues/94 
I ended up changing the docker-compose.yml file:

`version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
`

**Comment by basvandenbrink** [comment]
@nathanyeung Thanks! While this doesn't solve the problem of building the Docker image on Windows, it is definitely a good workaround.

**Comment by cahlen** [comment]
I found that the issue is that the fileformat is `dos` not `unix`.  Quick fix it to vi the file `download-kafka.sh` and run

`:set fileformat=unix`
`:wq`

Then `docker-compose up --build` and you should be set.

**Comment by abizer-khambati** [comment]
Fantastic cahlen, that is exactly what was required.
