### ISSUE TITLE
Provide a predictable location for kafka scripts

### ISSUE THREAD

**Issue by cressie176** [wurstmeister/kafka-docker#144]
Thanks for kafka-docker. We're using it to create automatically topics from kubernetes init-containers, e.g.

```
pod.beta.kubernetes.io/init-containers: '[
  {
    "name": "ensure-kafka-topics",
    "image": "wurstmeister/kafka",
    "command": ["/opt/kafka_2.11-0.10.1.0/bin/kafka-topics.sh", "--zookeeper", "zookeeper.example.com" ,"--create", "--if-not-exists", "--topic", "experimental-topic", "--partitions", "2", "--replication-factor", "2"]
  }
]'
```

The topic is created correctly but I'd prefer not to hard code the path and using $KAFKA_HOME doesn't work in this context. 

What do you think about creating a symlink ```/opt/kafka => /opt/kafka_2.11-0.10.1.0``` as you did for the jdk or adding $KAFKA_HOME to the path?

Either solution would work for us and I'd be happy to create a PR if it saves you any trouble.

**Comment by wurstmeister** [comment]
Hi, 

thanks for the suggestion. I added both options.
Please let me know if this works for you.

Thanks

**Comment by cressie176** [comment]
Sorry - should have replied. Using the symlink works great.
