### ISSUE TITLE
Build image does not work on Windows 10 - /tmp/download-kafka.sh: not found

### ISSUE THREAD

**Issue by m-a-d-e** [wurstmeister/kafka-docker#146]
Hello,
When I run the build command on Windows 10, Docker 1.12.3, I get the following error:

> Step 6 : RUN chmod a+x /tmp/download-kafka.sh && sync && /tmp/download-kafka.sh && tar xfz /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz -C /opt && rm /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz && ln -s /opt/kafka_${SCALA_VERSION}-${KAFKA_VERSION} /opt/kafka
>  ---> Running in f32b8949e634
> /bin/sh: /tmp/download-kafka.sh: not found
> ERROR: Service 'kafka' failed to build: The command '/bin/sh -c chmod a+x /tmp/download-kafka.sh && sync && /tmp/download-kafka.sh && tar xfz /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz -C /opt && rm /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz && ln -s /opt/kafka_${SCALA_VERSION}-${KAFKA_VERSION} /opt/kafka' returned a non-zero code: 127

I tried to split the "chmod" and the execution of the script into 2 distinct commands but that did not fixed the problem.
I started from a clean situation (no images, no (ended) containers running.

**Comment by m-ciesielski** [comment]
Hello @m-a-d-e ,
I've got the same error on Windows 10 Docker installation.  I've tried to run `download-kafka.sh` script manually on container and following error message was printed:
```
λ docker run -it 9652fded8cea /bin/bash
bash-4.3# cd /tmp
bash-4.3# ./download-kafka.sh
bash: ./download-kafka.sh: /bin/sh^M: bad interpreter: No such file or directory
bash-4.3# bash download-kafka.sh
download-kafka.sh: line 2: $'\r': command not found
```
So issue was caused by Windows CRLF line endings in `download-kafka.sh` script - after removing them (with `dos2unix` in my case), I was able to build kafka-docker image without further problems.

**Comment by Cyb3rFl3x** [comment]
OK... i had the same Problem on Mac with Zsh and i found a workaround:
The workaround was to run the script with bash.
So use: /bin/bash ./start-kafka-shell.sh
