### ISSUE TITLE
Java Mission Control unable to get JMX from Kafka broker

### ISSUE THREAD

**Issue by valiksb** [wurstmeister/kafka-docker#147]
I'm trying to use jmc to connect to a Kafka broker that's within Docker. This is the compose file
The KAFKA_ADVERTISED_HOST_NAME is the IP I get when I do ifconfig on a Mac (Sierra)/ I'm using Docker for Mac (not the ToolBox).

When I start JMC and enter localhost:9999 it just times out after 30 sec.

version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.24
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      JMX_PORT: 9999
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

**Comment by sscaling** [comment]
I've submitted a pull-request for this: https://github.com/wurstmeister/kafka-docker/pull/162

**Comment by mslinn** [comment]
Looks like the PR was accepted. Should this issue be closed?
