### ISSUE TITLE
delete.topic.enable=true

### ISSUE THREAD

**Issue by schmichri** [wurstmeister/kafka-docker#150]
You can create&modify basically any property inside the config/server.properties by settings an docker environment variable starting with "KAFKA_"
e.g. in side the docker-compose.xml 
```
    environment:
      KAFKA_DELETE_TOPIC_ENABLE: "true"     

```
the start-kafka.sh script is changing this in 
`delete.topic.enable=true`

This is an very cool idea but took me an hour to find that by reading the shell script. It should be documented. (worst case it is now documented by this issue ;) )

**Comment by nicholasserra** [comment]
Nice, thanks. Was looking for this.

**Comment by wurstmeister** [comment]
Hi, 

thanks for the feedback but this is documented in the README under Pre-Requisites. I will see if I can make it a bit clearer.

**Comment by JonasSprenger** [comment]
Thanks, I was looking for setting the same property!

**Comment by gssprasad** [comment]
Thank you very much it is very helpfull for me

**Comment by davideicardi** [comment]
#620

**Comment by JooYeonPark** [comment]
Is this possible? I got error 
```sh
kafka.environment contains {"KAFKA_DELETE_TOPIC_ENABLE": true}, which is an invalid type, it should be a string
```

**Comment by schmichri** [comment]
Yes it’s still possible as I’ve written it. You should try to understand your error message better.
