### ISSUE TITLE
Use official openjdk alpine image?

### ISSUE THREAD

**Issue by F21** [wurstmeister/kafka-docker#151]
I've switched to running kafka using OpenJDK/JRE due to some possible violations of the Oracle license outlined here: http://blog.takipi.com/running-java-on-docker-youre-breaking-the-law/

So far, OpenJDK/JRE has been stable and worked really well and there's an official OpenJDK image here: https://hub.docker.com/_/openjdk/

**Comment by cdaringe** [comment]
what did you end up using?

**Comment by F21** [comment]
@cdaringe I ended up making my own image: https://github.com/F21/kafka

**Comment by cdaringe** [comment]
nice.  i see https://github.com/wurstmeister/kafka-docker/pull/290 now too

**Comment by sscaling** [comment]
#290 is merged.
