### ISSUE TITLE
Submit as official image?

### ISSUE THREAD

**Issue by F21** [wurstmeister/kafka-docker#152]
This kafka image seems to be the most popular and full-featured one available. I think it would make a great official image! 😄 

Refs:
https://github.com/docker-library/official-images
https://docs.docker.com/docker-hub/official_repos/

**Comment by maletor** [comment]
@wurstmeister any traction on this?

**Comment by AlJohri** [comment]
@wurstmeister @sscaling this would be great! took me a few minutes to figure out which kafka docker image to use. making it official would be much easier

**Comment by cricket007** [comment]
FWIW, I've reached out to Confluent to make their images official, seeing as they are the enterprise support company and original creators, and this image is only community maintained.

**Comment by F21** [comment]
Closing as this repo appears to be unmaintained and the images are no longer on docker hub.
