### ISSUE TITLE
Not working with Docker 1.13 Swarm mode

### ISSUE THREAD

**Issue by screwgoth** [wurstmeister/kafka-docker#161]
The docker-compose.yml doesn't work with Docker 1.13 swarm mode.
I suspect it's got to do with `KAFKA_ADVERTISED_HOST_NAME` environment variable.

**Comment by screwgoth** [comment]
Please refer PR  #168 as a fix for this issue.

**Comment by sscaling** [comment]
Should be addressed by PR #199. Thanks.
