### ISSUE TITLE
Establish a procedure for backporting changes to master to all published Kafka releases

### ISSUE THREAD

**Issue by dead10ck** [wurstmeister/kafka-docker#163]
There are currently a lot of fixes tangential to the version of Kafka that have been merged into master, but not backported to all the older versions of Kafka. The only difference between any published version of an image from this repo should be the Kafka version, and any operational steps needed to get a particular version working that differ from other versions.

**Comment by sscaling** [comment]
First I think we need to generate deltas between master and versions to see what the drift is.

**Comment by sscaling** [comment]
From some basic analysis: https://gist.github.com/sscaling/96bd7864253a39ab938a4f6649a39c5f - I can't see any reason to not rebuild all supported versions against the `master` code base.

We would have a build matrix such as

| Kafka/Scala | 2.11 | 2.12 |
|-------------|-----|-----|
| 0.8.2.2 | Y | x |
| 0.9.0.1 | Y | x |
| 0.10.2.1 | x | Y |
| 0.11.0.1 | x | Y |
| 1.0.1 | x | Y |
| 1.1.0 | x | Y |

**Comment by sscaling** [comment]
I think the tests will need re-working to target specific versions (for those that are not applicable)
