### ISSUE TITLE
kafka in docker-swarm and Error when sending message to topic test

### ISSUE THREAD

**Issue by pirat8** [wurstmeister/kafka-docker#174]
Hi,
I created a little docker swarm with 3 hosts and then I tried:

1)docker network create -d overlay --attachable webtrackingnet
2)docker service create --name zookeeper --network webtrackingnet -p 2181:2181  wurstmeister/zookeeper

3)docker service create --name kafka --mode global -e 'KAFKA_PORT=9092' -e 'KAFKA_ADVERTISED_PORT=9092' -e 'KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092'  -e 'KAFKA_ZOOKEEPER_CONNECT=192.168.0.120:2181' -e 'HOSTNAME_COMMAND=curl 192.168.0.119:5001' wurstmeister/kafka

docker service ls -->
ID            NAME             MODE        REPLICAS  IMAGE
773w9oqdc2yd  kafka            global      3/3       wurstmeister/kafka:latest
d5o912kdicdw  zookeeper        replicated  1/1       wurstmeister/zookeeper:latest

docker service ps kafka -->
ID            NAME                             IMAGE                      NODE    DESIRED STATE  CURRENT STATE           ERROR  PORTS
9bq82hf70wyy  kafka.te7zgtve4ww5jvy7ycyxlbzs9  wurstmeister/kafka:latest  kafka1  Running        Running 35 minutes ago         
oizaqdp2spz8  kafka.jh1bc6qlo7ecy2vbjbbwn4mdf  wurstmeister/kafka:latest  kafka3  Running        Running 35 minutes ago         
2jz8vmi6rsge  kafka.2e42q3wjoah4n8c0xomboxeo8  wurstmeister/kafka:latest  kafka2  Running        Running 35 minutes ago         

docker service ps zookeeper -->
ID            NAME         IMAGE                          NODE    DESIRED STATE  CURRENT STATE        ERROR  PORTS
vyaox99bawx9  zookeeper.1  wurstmeister/zookeeper:latest  kafka2  Running        Running 3 hours ago        

The startup-Log seems without errors:

[my.txt](https://github.com/wurstmeister/kafka-docker/files/858925/my.txt)

However, when I try to produce a message it gives an error:
kafkacat -P -b 192.168.0.121:9092 -t test2
3|1490113397.406|FAIL|rdkafka#producer-0| 192.168.0.121:9092/bootstrap: Failed to connect to broker at 192.168.0.121:9092: Connection refused
%3|1490113397.406|ERROR|rdkafka#producer-0| 192.168.0.121:9092/bootstrap: Failed to connect to broker at 192.168.0.121:9092: Connection refused
or
docker run --rm -it wurstmeister/kafka bash -c "\$KAFKA_HOME/bin/kafka-console-producer.sh --broker-list  192.168.0.121:9092 --topic test"

I get an error after one minute.
ERROR Error when sending message to topic test with key: null, value: 5 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)

What I'm doing wrong?

**Comment by pirat8** [comment]
I found the following in the zookeeper log when I create the service for kafka:

 from /10.255.0.4:39804
zookeeper.1.vyaox99bawx9@kafka2    | 2017-03-22 06:03:51,746 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@928] - Client attempting to establish new session at /10.255.0.4:39804
zookeeper.1.vyaox99bawx9@kafka2    | 2017-03-22 06:03:51,749 [myid:] - INFO  [SyncThread:0:ZooKeeperServer@673] - Established session 0x15af112b840002f with negotiated timeout 6000 for client /10.255.0.4:39804
zookeeper.1.vyaox99bawx9@kafka2    | 2017-03-22 06:03:51,952 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /10.255.0.4:50046
zookeeper.1.vyaox99bawx9@kafka2    | 2017-03-22 06:03:51,955 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@928] - Client attempting to establish new session at /10.255.0.4:50046
zookeeper.1.vyaox99bawx9@kafka2    | 2017-03-22 06:03:51,957 [myid:] - INFO  [SyncThread:0:ZooKeeperServer@673] - Established session 0x15af112b8400030 with negotiated timeout 6000 for client /10.255.0.4:50046
zookeeper.1.vyaox99bawx9@kafka2    | 2017-03-22 06:03:52,318 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /10.255.0.4:38990
zookeeper.1.vyaox99bawx9@kafka2    | 2017-03-22 06:03:52,323 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@928] - Client attempting to establish new session at /10.255.0.4:38990
zookeeper.1.vyaox99bawx9@kafka2    | 2017-03-22 06:03:52,324 [myid:] - INFO  [SyncThread:0:ZooKeeperServer@673] - Established session 0x15af112b8400031 with negotiated timeout 6000 for client /10.255.0.4:38990
zookeeper.1.vyaox99bawx9@kafka2    | 2017-03-22 06:03:52,670 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@649] - Got user-level KeeperException when processing sessionid:0x15af112b840002f type:create cxid:0x1b zxid:0x108 txntype:-1 reqpath:n/a Error Path:/brokers Error:KeeperErrorCode = NodeExists for /brokers
zookeeper.1.vyaox99bawx9@kafka2    | 2017-03-22 06:03:52,671 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@649] - Got user-level KeeperException when processing sessionid:0x15af112b840002f type:create cxid:0x1c zxid:0x109 txntype:-1 reqpath:n/a Error Path:/brokers/ids Error:KeeperErrorCode = NodeExists for /brokers/ids
zookeeper.1.vyaox99bawx9@kafka2    | 2017-03-22 06:03:52,905 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@649] - Got user-level KeeperException when processing sessionid:0x15af112b8400030 type:create cxid:0x1b zxid:0x10b txntype:-1 reqpath:n/a Error Path:/brokers Error:KeeperErrorCode = NodeExists for /brokers
zookeeper.1.vyaox99bawx9@kafka2    | 2017-03-22 06:03:52,906 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@649] - Got user-level KeeperException when processing sessionid:0x15af112b8400030 type:create cxid:0x1c zxid:0x10c txntype:-1 reqpath:n/a Error Path:/brokers/ids Error:KeeperErrorCode = NodeExists for /brokers/ids
zookeeper.1.vyaox99bawx9@kafka2    | 2017-03-22 06:03:53,433 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@649] - Got user-level KeeperException when processing sessionid:0x15af112b8400031 type:create cxid:0x1b zxid:0x10e txntype:-1 reqpath:n/a Error Path:/brokers Error:KeeperErrorCode = NodeExists for /brokers
zookeeper.1.vyaox99bawx9@kafka2    | 2017-03-22 06:03:53,433 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@649] - Got user-level KeeperException when processing sessionid:0x15af112b8400031 type:create cxid:0x1c zxid:0x10f txntype:-1 reqpath:n/a Error Path:/brokers/ids Error:KeeperErrorCode = NodeExists for /brokers/ids
zookeeper.1.vyaox99bawx9@kafka2    | 2017-03-22 06:03:55,391 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@357] - caught end of stream exception
zookeeper.1.vyaox99bawx9@kafka2    | EndOfStreamException: Unable to read additional data from client sessionid 0x15af112b840002d, likely client has closed socket
zookeeper.1.vyaox99bawx9@kafka2    | 	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228)
zookeeper.1.vyaox99bawx9@kafka2    | 	at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:203)
zookeeper.1.vyaox99bawx9@kafka2    | 	at java.lang.Thread.run(Thread.java:745)

So I'm coning closer...

**Comment by sscaling** [comment]
@pirat8 - did PR #199 resolve this issue?

**Comment by sscaling** [comment]
Closing due to staleness.
