### ISSUE TITLE
can you make it possible for openshift permission

### ISSUE THREAD

**Issue by RobinsChens** [wurstmeister/kafka-docker#182]
can you make it possible for openshift permission

![image](https://cloud.githubusercontent.com/assets/11987492/25320501/3cc1f200-28da-11e7-8e51-c5b9f4cc6a42.png)

**Comment by sscaling** [comment]
@RobinsChens do you know what the specific issue is? I'm not familiar with OpenShift - do you want to raise a PR?

**Comment by sscaling** [comment]
Closing due to staleness. No response from OP.

**Comment by BirgerK** [comment]
I just stumbled upon this issue and want to give an answer:

Seems like this image runs internally as root. That's not allowed for images running in OpenShift. Therefore the should be a `USER`-statement inside of the Dockerfile. F.g.:
```
USER kafka
```

Of course all needed kafka-files and persistence-dirs should be read- and writable to the kafka-user.
