### ISSUE TITLE
Backport startup script fix to 0.9

### ISSUE THREAD

**Issue by pbrisbin** [wurstmeister/kafka-docker#184]
Can you please release a new 0.9 image with https://github.com/wurstmeister/kafka-docker/commit/4811383155393d5aaa98d9f97c30775d444e2c7e ?

We're experiencing incorrect shutdown behavior because the latest tag for the 0.9 series doesn't have the crucial `exec`.

**Comment by wurstmeister** [comment]
i've created ```wurstmeister/kafka:0.9.0.1-1``` with all recent changes. I have not had much time to test.

**Comment by pbrisbin** [comment]
Thanks!
