### ISSUE TITLE
Why /var/run/docker.sock is needed? It runs without

### ISSUE THREAD

**Issue by inancgumus** [wurstmeister/kafka-docker#185]
```bash
$ tail -1 start-kafka-shell.sh
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -e HOST_IP=$1 -e ZK=$2 -i -t wurstmeister/kafka /bin/bash

# this also runs
$ docker run --rm -it wurstmeister/kafka /bin/bash
bash-4.3#
```

Why did you use `-v /var/run/docker.sock:/var/run/docker.sock` for?

**Comment by wurstmeister** [comment]
it's only required if you want to run docker from within the container (e.g. https://github.com/wurstmeister/kafka-docker/blob/master/broker-list.sh)

**Comment by inancgumus** [comment]
Hmm, `docker port` needs it?

**Comment by danielkza** [comment]
Any chance this can be made optional through an environment variable? I just want to run a single broker for CI purposes.

**Comment by sscaling** [comment]
@danielkza - this is optional. Just don't mount the docker socket through to the container and `start-kafka.sh` will not execute the docker command, see: [https://github.com/wurstmeister/kafka-docker/blob/master/start-kafka.sh#L12](https://github.com/wurstmeister/kafka-docker/blob/master/start-kafka.sh#L12)

Specifically the check for the socket.
```
-S /var/run/docker.sock
```

Be sure to set `KAFKA_ADVERTISED_PORT` manually  if you need it.

**Comment by sscaling** [comment]
Added this info the the FAQ: [https://github.com/wurstmeister/kafka-docker/wiki](https://github.com/wurstmeister/kafka-docker/wiki)
