### ISSUE TITLE
Docker-Compose kafka healthcheck

### ISSUE THREAD

**Issue by gjwilk01** [wurstmeister/kafka-docker#187]
What would be the best way to determine when dockerized kafka service reaches healthy state?  I am orchestrating my services using docker-compose and would like to add a dependency on kafka service readiness for dependent services. 

~george

**Comment by terrabl** [comment]
Did you figure this out?

**Comment by sscaling** [comment]
duplicates #167. Closing as that contains more information.

**Comment by kasir-barati** [comment]
### [Here](https://github.com/kasir-barati/docker/blob/main/docker-compose-files/kafka/compose.yaml) is how I did it in docker compose @andrewterra @gjwilk01.

Consider giving it a star if it was useful to you.
