### ISSUE TITLE
Docker-compose fails

### ISSUE THREAD

**Issue by NyorJa** [wurstmeister/kafka-docker#190]
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.4/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.167438ca.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.4/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.a2e6dac0.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  coreutils (missing):
    required by: world[coreutils]
  curl (missing):
    required by: world[curl]
  docker (missing):
    required by: world[docker]
  jq (missing):
    required by: world[jq]
  unzip (missing):
    required by: world[unzip]
  wget (missing):
    required by: world[wget]
ERROR: Service 'kafka' failed to build: The command '/bin/sh -c apk add --update unzip wget curl docker jq coreutils' returned a non-zero code: 6

**Comment by kevintvh** [comment]
Got same issue. Could you please have a look on this ?

Building kafka
Step 1/16 : FROM anapsix/alpine-java
 ---> 8d6c3a114070
Step 2/16 : ARG kafka_version=0.10.2.1
 ---> Using cache
 ---> cd56ff07da0c
Step 3/16 : ARG scala_version=2.12
 ---> Using cache
 ---> f271b2988b70
Step 4/16 : MAINTAINER wurstmeister
 ---> Using cache
 ---> 2eab793d1c78
Step 5/16 : RUN apk add --no-cache --update unzip wget curl docker jq coreutils
 ---> Running in ccf29d8fc306
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.4/main: temporary error (try again later)
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.4/community: temporary error (try again later)
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
ERROR: unsatisfiable constraints:
  coreutils (missing):
    required by: world[coreutils]
  curl (missing):
    required by: world[curl]
  docker (missing):
    required by: world[docker]
  jq (missing):
    required by: world[jq]
  unzip (missing):
    required by: world[unzip]
  wget (missing):
    required by: world[wget]
ERROR: Service 'kafka' failed to build: The command '/bin/sh -c apk add --no-cache --update unzip wget curl docker jq coreutils' returned a non-zero code: 6

**Comment by Montrazul** [comment]
👍

**Comment by LI-Ke** [comment]
Maybe you can try to build your own kafka image. I've succeeded. Look at this : https://github.com/LI-Ke/spark-standalone-cluster-on-docker/blob/master/kafka/Dockerfile  
I hope it will help!

**Comment by sscaling** [comment]
As the error message says `temporary error (try again later)`. If this is persistent, then this is likely your network configuration issue unable to access the external resource.

Closing as temporary issue connecting to alpine repository.
