### ISSUE TITLE
issue with dl-cdn.alpinelinux.org causing build failure

### ISSUE THREAD

**Issue by Johnstean** [wurstmeister/kafka-docker#196]
`Step 5/16 : RUN apk add --update unzip wget curl docker jq coreutils
 ---> Running in 07822d6da149
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.4/main: IO ERROR
`

possible due to certificate error

**Comment by Montrazul** [comment]
👍

**Comment by sscaling** [comment]
No updates in more than 6 months. Seems like a temporary issue with the alpine repository.

@Johnstean - if this is still an issue, please can you re-open with full log, docker versions and OS information. Thanks.
