### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

### ISSUE THREAD

**Issue by infinitebyte** [wurstmeister/kafka-docker#20]
Below error occurred when I ran this command: 
$KAFKA_HOME/bin/kafka-console-producer.sh --topic=topic --broker-list=`broker-list.sh`

here is the full error message:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

I followed the steps mentioned in http://wurstmeister.github.io/kafka-docker/
Everything worked fine until I ran this command.

**Comment by danielkraaij** [comment]
Same problem here. Any ideas? @wurstmeister

**Comment by wurstmeister** [comment]
Hi, 

please see https://issues.apache.org/jira/browse/KAFKA-1354. 

Kafka does not ship with an SLF4J binding, so this just means that the producer will use the NOP logger implementation. If you continue the tutorial and start the consumer everything should work, i.e. enter a message on the producer side and it will arrive on the consumer side.  (you will get the same SLF4j message for the consumer)
