### ISSUE TITLE
Push 0.11.0.0 tag to docker hub

### ISSUE THREAD

**Issue by idooo** [wurstmeister/kafka-docker#203]
Similar to #175

Thanks for the image. Any chance you could push 0.11.0.0 tag to Docker hub please?

Thank you!

**Comment by maraisr** [comment]
Bump @wurstmeister

**Comment by idooo** [comment]
@maraisr https://hub.docker.com/r/wurstmeister/kafka/tags/

This ticket can be closed

**Comment by maraisr** [comment]
Cheers @idooo
