### ISSUE TITLE
kafka topic create error with jmxport open

### ISSUE THREAD

**Issue by ray1888** [wurstmeister/kafka-docker#204]
i try to create a topic or list topic in kafka with cmd:exec -it container id $kafka_path/bin/kafka_topic.sh , but with jmx open , it come error like this. 
./kafka-console-producer.sh --broker-list localhost:9092 --topic abc
Error: JMX connector server communication error: service:jmx:rmi://9dcb21ce1644:1099

myconfiguration of docker-compose.yml is:
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "9094:9094"
      - "1099:1099"
    environment:
      KAFKA_CREATE_TOPICS: "test123:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_PORT: 9092
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1099"
      JMX_PORT: 1099

i can't figure it out where is the problem, so i think maybe someone can help me fixing this, thx

**Comment by sscaling** [comment]
Please see [FAQ](https://github.com/wurstmeister/kafka-docker/wiki#why-do-kafka-tools-fail-when-jmx-is-enabled)
