### ISSUE TITLE
Listing Kafka topics that are up and running?

### ISSUE THREAD

**Issue by terrabl** [wurstmeister/kafka-docker#205]
Is there a way to list the Kafka topics that are running? 

As well as a way to listen to them and see what it coming across them.

**Comment by sscaling** [comment]
Regarding listing topics, use

```
$KAFKA_HOME/bin/kafka-topics.sh --list --zookeeper zookeeper:2181
```

Regarding monitoring usage - you could use a variety of tools such as jmx-exporter + prometheus, JMX to cloud provider (I think datadog offer this service). With high-level consumers, you can get the connected clients / groups via zookeeper. 

However, this is a question for the Kafka mailing list where you can get much more in-depth and detailed information.
