### ISSUE TITLE
Broker id defaults to 1001

### ISSUE THREAD

**Issue by aryzle** [wurstmeister/kafka-docker#206]
Do we want this default behavior? isn't the default max id 1000?

What are other people doing to use a cluster of 3 more kafkas? setting each one's `BROKER_ID`?

I'm using Docker 17.06 and running zoo and kafka in a swarm, everything works with 1 kafka, just trying to figure this last piece out.

**Comment by sscaling** [comment]
@aryzle - did you see the changes made for docker swarm in PR #199 ? Does that resolve your issue?

As for `broker.id` see: [https://kafka.apache.org/documentation/](https://kafka.apache.org/documentation/).

> broker.id
> The broker id for this server. If unset, a unique broker id will be generated.To avoid conflicts between zookeeper generated broker id's and user configured broker id's, generated broker ids start from reserved.broker.max.id + 1.

so the `1000` is for the maximum user assigned broker ID. If you do not provide a `KAFKA_BROKER_ID` environment var, the broker ID will be auto generated.

**Comment by sscaling** [comment]
Closing due to staleness.
