### ISSUE TITLE
Unable to publish to on a topic

### ISSUE THREAD

**Issue by vedavidhbudimuri** [wurstmeister/kafka-docker#212]
Can someone help me with this issue. Im have created 3 kafka nodes and trying to publish, by executing the following command in kafka node.
 
`bin/kafka-console-producer.sh --topic=my-replicated-topic --broker-list='kafka_1:32852,kafka_2:32853,kafka_3:32854'`

<img width="1427" alt="screen shot 2017-08-22 at 10 37 09 am" src="https://user-images.githubusercontent.com/6457019/29550645-5b60990e-872c-11e7-9b60-24491fbe8480.png">

Thanks in advance

**Comment by Eoan242** [comment]
same issue as the previous one in https://github.com/wurstmeister/kafka-docker/issues/211
