### ISSUE TITLE
Fetching metadata with correlation id 750 for topic from broker failed

### ISSUE THREAD

**Issue by lee-cn** [wurstmeister/kafka-docker#213]
HI，
I hava a physical server that run one service out of the swarm mode，then my kafka was running in the swarm mode，so，I expose every container ports 9092 to outside。but it returns with the error log：
[INFO]Disconnecting from kafka1:9092
[INFO]Fetching metadata from broker id:2 ,host：kafka3，port：9092 with correlation id 750 for 1 topic（s）Set(GW_GIS_LOC)
[INFO]Connected to kafka3:9092 for producing
[INFO]Disconecting from kafka3:9092
[WARN]Fetching topic metadata with correlation id 750 for topic from broker failed

**Comment by sscaling** [comment]
Hi @lee-cn - please can you include any configuration files, docker versions and OS information to help people answer this question. Thanks.

**Comment by sscaling** [comment]
Closing due to staleness. No further info provided.
