### ISSUE TITLE
Brokers can't communicate with each other

### ISSUE THREAD

**Issue by tremblerz** [wurstmeister/kafka-docker#217]
Hi!
I think in current version of this docker image, containers can't talk to each other because they are advertising IP of base machine and from inside they can't connect to each other with IP_base_machine:port pair.

**Comment by sscaling** [comment]
Closing due to lack of information.

@tremblerz - if this is still an issue, please can you re-open and attach config you are using, the docker versions, image versions, OS versions and any error logs. Thanks.
