### ISSUE TITLE
How to ssh into kafkadocker_kafka_1?

### ISSUE THREAD

**Issue by adsl99801** [wurstmeister/kafka-docker#223]
In kafka_1 (moby linux). I found apk comand in it . I can use apk install openssh to launch sftp but I want edit something in the file .When  I run scale kafka=number the brokers exist openssh already.

**Comment by jpavanaryan** [comment]
You can use command `docker exec -it kafkadocker_kafka_1 bash` to access the docker instance.

**Comment by sscaling** [comment]
Added this to the FAQ: [https://github.com/wurstmeister/kafka-docker/wiki#how-can-i-connect-to-the-running-container](https://github.com/wurstmeister/kafka-docker/wiki#how-can-i-connect-to-the-running-container)
