### ISSUE TITLE
New build for Kafka 1.0?

### ISSUE THREAD

**Issue by jgoodall** [wurstmeister/kafka-docker#228]
Kafka [1.0](https://dist.apache.org/repos/dist/release/kafka/1.0.0/RELEASE_NOTES.html) was released today. Is there a timeline of when the image will be updated?

**Comment by aayars** [comment]
Hi @wurstmeister -- props for providing this image. I work on Docker stuff at confluent.io, with the creators of Apache Kafka (our AK 1.0 images are tied to our upcoming release, and will take a bit longer!)

Just wanted to let you know we're hiring, and would love to speak with you. Sorry for the entirely inappropriate use of GitHub. If you're interested, LMK!

Alex Ayars
alex.ayars@confluent.io
