### ISSUE TITLE
ERROR Error when sending message to topic squid with key: null, value: 134 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)

### ISSUE THREAD

**Issue by Imadecakson** [wurstmeister/kafka-docker#230]
i try to run 
cat /var/log/squid/access.log | ${HDP_HOME}/kafka-broker/bin/kafka-console-producer.sh --broker-list $BROKERLIST --topic squid 
but the terminal show me that error, someone can help me ?

**Comment by dangkaka** [comment]
I have the same issue

**Comment by sscaling** [comment]
Hi @imadecakson / @dangkaka - could you provide the full log, docker versions, OS informtion, compose file used and any other relevant information. Thanks

**Comment by dangkaka** [comment]
I forgot what I did but it doesn't happen to me anymore
Thanks @sscaling 😄
