### ISSUE TITLE
Kafka Docker and port forwarding from 9092 to 9093

### ISSUE THREAD

**Issue by Artgit** [wurstmeister/kafka-docker#234]
Hi, I ran into the following issue with kafka-docker port forwarding:

https://stackoverflow.com/questions/47439477/kafka-docker-and-port-forwarding-from-9092-to-9093

How to properly forward the port from 9092 to 9093?

**Comment by sscaling** [comment]
@Artgit - why do you want to forward the port? i.e. what are you trying to achieve.

The easiest way would just be to set `KAFKA_PORT` to 9093, then map the port directly (i.e. `9093:9093`)

**Comment by sscaling** [comment]
Closing due to staleness
