### ISSUE TITLE
Unable to build kafka docker (The command '/bin/sh -c /tmp/download-kafka.sh' returned a non-zero code: 8)

### ISSUE THREAD

**Issue by bryanleekw** [wurstmeister/kafka-docker#235]
Hi all, I encounter a problem of unable to build kafka docker, and I have tried the solution mentioned in here, but still could not be solved. Actually, I had another machine following the same rule and was unable to start kafka server less than 1 month ago. So, may anyone help me? 

root@nb1:/proj/speedd/speedd-docker-master/kafka-docker# docker build -t wurstmeister/kafka-docker --rm=true .
Sending build context to Docker daemon 176.6 kB
Step 1/16 : FROM ubuntu:trusty
 ---> d6ed29ffda6b
Step 2/16 : MAINTAINER Wurstmeister
 ---> Using cache
 ---> 7f844453aac2
Step 3/16 : RUN echo 'root:speedd' | chpasswd
 ---> Using cache
 ---> f7b9eada4c08
Step 4/16 : ENV KAFKA_VERSION "0.8.2.1" SCALA_VERSION "2.10"
 ---> Using cache
 ---> 534eb9592772
Step 5/16 : RUN apt-get update && apt-get install -y unzip openjdk-6-jdk wget curl git docker.io jq
 ---> Using cache
 ---> 5dd57f78f767
Step 6/16 : ADD download-kafka.sh /tmp/download-kafka.sh
 ---> Using cache
 ---> 9393578170e5
Step 7/16 : RUN chmod 776 /tmp/download-kafka.sh
 ---> Using cache
 ---> 7227390b83c5
Step 8/16 : RUN /tmp/download-kafka.sh
 ---> Running in b0b8e4a22de7
The command '/bin/sh -c /tmp/download-kafka.sh' returned a non-zero code: 8

**Comment by karthiks** [comment]
See [@cahlen's answer](https://github.com/wurstmeister/kafka-docker/issues/142) to resolve this issue. It says you'll have to change the file format (line-endings) from DOS to Unix of the file - `download-kafka.sh`

**Comment by SamMolokanov** [comment]
Possible reason here in the line `ENV KAFKA_VERSION "0.8.2.1"` - this version is not available on mirrors for downloading, for example http://ftp.heikorichter.name/apache/kafka/

Possible solutions:

- Pull new version of `Dockerfile` from the repo
- Change the script `download-kafka.sh` in order to download the specific version of Kafka.

**Comment by bryanleekw** [comment]
yes, old version no longer available, and I modified version v0.10. Then it works. But I worry about compatibility if installing with newer version.
