### ISSUE TITLE
Moving to kafka 0.8.2

### ISSUE THREAD

**Issue by srangwal** [wurstmeister/kafka-docker#24]
I have been using this extensively and have hit few known bugs in 0.8.1.1 that were fixed in 0.8.2. I was able to successfully migrate to 0.8.2 with the following changes to Dockerfile 

```diff
-RUN wget -q http://mirror.gopotato.co.uk/apache/kafka/0.8.1.1/kafka_2.8.0-0.8.1.1.tgz -O /tmp/kafka_2.8.0-0.8.1.1.tgz
+RUN wget -q http://mirror.gopotato.co.uk/apache/kafka/0.8.2-beta/kafka_2.9.1-0.8.2-beta.tgz -O /tmp/kafka_2.9.1-0.8.2-beta.tgz
 
-RUN tar xfz /tmp/kafka_2.8.0-0.8.1.1.tgz -C /opt
+RUN tar xfz /tmp/kafka_2.9.1-0.8.2-beta.tgz -C /opt
 
-ENV KAFKA_HOME /opt/kafka_2.8.0-0.8.1.1
+ENV KAFKA_HOME /opt/kafka_2.9.1-0.8.2-beta
```

Is there any plan to migrate to 0.8.2?

**Comment by wurstmeister** [comment]
Hi,

I've create a branch for 0.8.2, https://github.com/wurstmeister/kafka-docker/tree/0.8.2

**Comment by srangwal** [comment]
Thanks. Do you plan to push wurstmeister/kafka:0.8.2 to docker repository as well.

**Comment by wurstmeister** [comment]
It's already there  ```curl https://index.docker.io/v1/repositories/wurstmeister/kafka/tags```

you can also use https://github.com/wurstmeister/kafka-docker/blob/0.8.2/fig.yml.
