### ISSUE TITLE
KAFKA_ADVERTISED_HOST_NAME with custom bridge network

### ISSUE THREAD

**Issue by bimission** [wurstmeister/kafka-docker#240]
Hi, 

I have the following setup:
custom docker bridge network with adressing: --subnet=192.168.0.0/16
Inside this subnet I have run 3 zookeeper containers and now I want to run kafka containers.
I want kafka to be available to external producers and consumers. 
When try to run Kafka with distinct values for KAFKA_ADVERTISED_HOST_NAME

docker run --name kafka_dev01-1 --net net_kafka_dev01 --ip 192.168.1.11 -e KAFKA_BROKER_ID=1 -e KAFKA_ZOOKEEPER_CONNECT=192.168.0.11:2181,192.168.0.12:2181,192.168.0.13:2181  -e KAFKA_ADVERTISED_PORT=9092 -e KAFKA_ADVERTISED_HOST_NAME=XXXX????XXXXX -p 9092:9092 -t artifactory.mbank.pl:8443/wurstmeister/kafka 

My understanding of KAFKA_ADVERTISED_HOST_NAME parameter is that it is the name or ip which will by used by consumers or producers to connect to kafka brokers. 

When I put the IP of machine which hosts docker engine then 

docker run --name kafka_dev01-1 --net net_kafka_dev01 --ip 192.168.1.11 -e KAFKA_BROKER_ID=1 -e KAFKA_ZOOKEEPER_CONNECT=192.168.0.11:2181,192.168.0.12:2181,192.168.0.13:2181  -e KAFKA_ADVERTISED_PORT=9092 -e KAFKA_ADVERTISED_HOST_NAME=10.23.2.147 -p 9092:9092 -t artifactory.mbank.pl:8443/wurstmeister/kafka

then I get in logs of Kafka container:

[2017-12-14 08:17:30,845] INFO [KafkaServer id=1] started (kafka.server.KafkaServer)
[2017-12-14 08:17:32,102] WARN [Controller id=1, targetBrokerId=1] Connection to node 1 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2017-12-14 08:17:33,206] WARN [Controller id=1, targetBrokerId=1] Connection to node 1 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2017-12-14 08:17:34,310] WARN [Controller id=1, targetBrokerId=1] Connection to node 1 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)

These messages do not appear only when I use KAFKA_ADVERTISED_HOST_NAME=192.168.1.11 which is IP assigned to this kafka container but then Kafka is not available to external producers/consumers.

**Comment by sscaling** [comment]
Can you reproduce this in a docker-compose.yml file.

**Comment by sscaling** [comment]
The 192.168.0.0/16 address range is only accessible from inside the docker network. When a client retrieves meta data it contains the advertised broker address. An external client cannot access the internal network.
