### ISSUE TITLE
Error of Kakfa class Version

### ISSUE THREAD

**Issue by bryanleekw** [wurstmeister/kafka-docker#242]
When I started up with a newer version of Kafka to build the docker, for example 0.10 being pulled, instead of 0.8, and I found this error. May I know how to solve this? 

kafka_1       | Exception in thread "main" java.lang.UnsWHeupportedClassVersionError: joptsimple/OptionSpec : Unsupported major.minor version 51.0
kafka_1       | 	at java.lang.ClassLoader.defineClass1(Native Method)
kafka_1       | 	at java.lang.ClassLoader.defineClass(ClassLoader.java:648)
kafka_1       | 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
kafka_1       | 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:272)
kafka_1       | 	at java.net.URLClassLoader.access$000(URLClassLoader.java:68)
kafka_1       | 	at java.net.URLClassLoader$1.run(URLClassLoader.java:207)
kafka_1       | 	at java.net.URLClassLoader$1.run(URLClassLoader.java:201)
kafka_1       | 	at java.security.AccessController.doPrivileged(Native Method)
kafka_1       | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:200)
kafka_1       | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:325)
kafka_1       | 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:296)
kafka_1       | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:270)
kafka_1       | 	at kafka.Kafka.main(Kafka.scala)

**Comment by sscaling** [comment]
@bryanleekw - did this issue get resolved? the `Unsupported major.minor version 51.0` exception would indicate trying to run the code on an incompatible JRE.

**Comment by sscaling** [comment]
Closing due to staleness
