### ISSUE TITLE
Tutorial update to use new console-consumer

### ISSUE THREAD

**Issue by DerMorb** [wurstmeister/kafka-docker#243]
Hi wurstmeister,

thanks for your work. Just a small hint (as it cost me a couple of hours today to figure it out, see [here](https://stackoverflow.com/questions/47953901/spring-kafka-producer-not-sending-to-kafka-1-0-0-magic-v1-does-not-support-reco)):

The tutorial worked fine before with Kafka < 1.0 but after the update using an "old" consumer ( `kafka-console-consumer.sh --topic=topic --zookeeper`) can result in errors in consumer also and producer.

So the tutorial should be updated to use a new consumer:  `kafka-console-consumer.sh --topic=topic --bootstrap-server $HOST_IP:$PORT`

Cheers

**Comment by sscaling** [comment]
subsumed by #407

**Comment by abhiTW** [comment]
Even I faced the same issue with regards to --bootstrap-server option. It will be helpful if it can be updated at the earliest.

**Comment by marcusreese** [comment]
The suggestion above does not seem to work. What works is:
$KAFKA_HOME/bin/kafka-console-consumer.sh --bootstrap-server `broker-list.sh` --topic topic --from-beginning
--from the subsuming issue 407: https://github.com/wurstmeister/kafka-docker/issues/407#issuecomment-442820032
