### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by stonefury** [wurstmeister/kafka-docker#25]
Any performance issues with running in docker?

I'm trying to run some performance tests based on: https://gist.github.com/jkreps/c7ddb4041ef62a900e6c, and my numbers are dismal.

**Comment by sscaling** [comment]
None that we're aware of. Kafka is normally bound by IO rather than compute.

Performance can be affected by many things such as memory, disk layout, physical disk hardware (i.e. SSD).

Haven't heard any other complaints and have run this at scale in production.

Closing due to staleness.
