### ISSUE TITLE
kafka-docker in message route VM of ONAP

### ISSUE THREAD

**Issue by pranjal0491** [wurstmeister/kafka-docker#251]
docker start/running, process 20729
Setting up cgroup-lite (1.9) ...
cgroup-lite start/running
Processing triggers for libc-bin (2.19-0ubuntu6) ...
Processing triggers for ureadahead (0.100.0-16) ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   617    0   617    0     0     62      0 --:--:--  0:00:09 --:--:--   160
100 7857k  100 7857k    0     0  89047      0  0:01:30  0:01:30 --:--:-- 68353
docker stop/waiting
docker start/running, process 21427
Cloning into 'dcae-startup-vm-message-router'...
remote: Finding sources: 100% (229/229)
remote: Total 229 (delta 68), reused 228 (delta 68)
Receiving objects: 100% (229/229), 240.30 KiB | 3.00 KiB/s, done.
Resolving deltas: 100% (68/68), done.
Checking connectivity... done.
prep any files with local configurations
starting docker operations
Creating network "dockerfiles_default" with driver "bridge"
Pulling zookeeper (wurstmeister/zookeeper:latest)...
latest: Pulling from wurstmeister/zookeeper
a3ed95caeb02: Pull complete
ef38b711a50f: Pull complete
e057c74597c7: Pull complete
666c214f6385: Pull complete
c3d6a96f1ffc: Pull complete
3fe26a83e0ca: Pull complete
3d3a7dd3a3b1: Pull complete
f8cc938abe5f: Pull complete
9978b75f7a58: Pull complete
4d4dbcc8f8cc: Pull complete
6e2141080cee: Pull complete
7b01624d9a37: Pull complete
438e659516b8: Pull complete
504083860edf: Pull complete
9e313884ca1b: Pull complete
7f32922adacf: Pull complete
Digest: sha256:2d71f9e0cb3440d552ee31769a00eb813be87397bf535995aca0bd4eadc151fc
Status: Downloaded newer image for wurstmeister/zookeeper:latest
Building kafka
Step 1/13 : FROM anapsix/alpine-java
latest: Pulling from anapsix/alpine-java
605ce1bd3f31: Pull complete
bda4574f0ddc: Pull complete
Digest: sha256:f1c839c47015be42af8cb60a86cd5b911716bf2e4dd4374d0163dd639c65fdda
Status: Downloaded newer image for anapsix/alpine-java:latest
 ---> 61d7843b6d95
Step 2/13 : MAINTAINER Wurstmeister
 ---> Running in 7262b0cd7407
 ---> 3563788136c6
Removing intermediate container 7262b0cd7407
Step 3/13 : RUN apk add --update tar wget curl docker coreutils
 ---> Running in 425f4e3c4f13
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.6/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.84815163.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.6/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.24d64ab1.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  coreutils (missing):
    required by: world[coreutils]
  curl (missing):
    required by: world[curl]
  docker (missing):
    required by: world[docker]
  tar (missing):
    required by: world[tar]
  wget (missing):
    required by: world[wget]
ERROR: Service 'kafka' failed to build: The command '/bin/sh -c apk add --update tar wget curl docker coreutils' returned a non-zero code: 5

**Comment by sscaling** [comment]
> ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.6/main: temporary error (try again later)

Sounds like the repo wasn't available, or blocked via your network config. Please reopen if this issue persists. Include commands run, docker versions and OS. Thanks
