### ISSUE TITLE
"\\var\\run\\docker.sock" includes invalid characters for a local volume name

### ISSUE THREAD

**Issue by grib0** [wurstmeister/kafka-docker#259]
Using windows 10
Docker version 1.12.6, build 78d1802
docker-compose version 1.9.0, build 2585387

running 
```sh
docker-compose up -d
```
leads to :
```log
Creating kafkadocker_kafka_1
Creating kafkadocker_zookeeper_1

ERROR: for kafka  Cannot create container for service kafka: create \var\run\docker.sock: "\\var\\run\\docker.sock" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed
[31mERROR[0m: Encountered errors while bringing up the project.
```

**Comment by Hopje** [comment]
Probably the same issue as described in https://github.com/moby/moby/issues/29753
For me, it helped to set COMPOSE_CONVERT_WINDOWS_PATHS=1:
$export COMPOSE_CONVERT_WINDOWS_PATHS=1
$docker-compose up -d

**Comment by sscaling** [comment]
Have tracked this information in the FAQS: https://github.com/wurstmeister/kafka-docker/wiki#on-windows-varrundockersock-cant-be-mounted---is-there-anything-i-can-do
