### ISSUE TITLE
Remove docker package

### ISSUE THREAD

**Issue by davidhiebert** [wurstmeister/kafka-docker#264]
The image already includes `curl` and `jq`, and the docker-compose*.yml's already mount `/var/run/docker.sock`.  If you update the `HOSTNAME_COMMAND` you can drop the `apk add docker`.
HOSTNAME_COMMAND: "curl -s --unix-socket /var/run/docker.sock http:/containers/info | jq -r .Name"

**Comment by tcjennings** [comment]
This sounds like a good approach, especially since the docker you get from Alpine is very old now (1.11) so to access any significant APIs you would need to use curl anyway.

**Comment by sscaling** [comment]
as an aside,  this reduces that particular layer from 153MB -> 56.4MB

**Comment by sscaling** [comment]
Have recently switched to openjdk alpine image and testing currently uses docker. Will leave this as-is for now. docker.sock mounting is documented in wiki: https://github.com/wurstmeister/kafka-docker/wiki#why-is-varrundockersock-needed
