### ISSUE TITLE
Error when sending message to topic records with key: null, value: 1699 bytes with error: (org.apache.kafka.clien ts.producer.internals.ErrorLoggingCallback) java.lang.IllegalStateException: Producer is closed forcefully.

### ISSUE THREAD

**Issue by sd1700092** [wurstmeister/kafka-docker#266]
I'm using the Mirror Maker to transfer messages between clusters.
The transfer is OK at the beginning.
As time went away, it encounters a serious problem:

[2018-02-08 13:32:34,340] ERROR Error when sending message to topic records with key: null, value: 1699 bytes with error: (org.apache.kafka.clien
ts.producer.internals.ErrorLoggingCallback)
java.lang.IllegalStateException: Producer is closed forcefully.
	at org.apache.kafka.clients.producer.internals.RecordAccumulator.abortBatches(RecordAccumulator.java:696)
	at org.apache.kafka.clients.producer.internals.RecordAccumulator.abortIncompleteBatches(RecordAccumulator.java:683)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:185)
	at java.lang.Thread.run(Thread.java:745)

How com does that happen, how shall I fix it?

**Comment by sscaling** [comment]
This seems more like a question for the Kafka user group mailing list. Please re-open if you think that this is related to the kafka-docker image. Thanks.

**Comment by trajakovic** [comment]
@sd1700092 have you found somewhere solution for your case? I'm getting same error using Mirror Maker...

but yes, this is unrelated to this kafka-docker

**Comment by Kashyap23** [comment]
@trajakovic I am also facing the same issue with kafka mirror maker. Did you get any solution for that ?

**Comment by trajakovic** [comment]
@Kashyap23 well lately I've faced this same error when destination broker(s) were unable to consume message due size. Check (and raise) your `message.max.bytes` config for brokers AND check `producer.properties` `max.request.size` for MirrorMaker. It might help.

**Comment by Kashyap23** [comment]
@trajakovic Thanks man. It seems to work now.

**Comment by Valeriyy** [comment]
@Kashyap23 to what value have you raised it? In error it is 1699 bytes, but in `producer.properties` you could not have specified max.request.size 1024 bytes
