### ISSUE TITLE
Boot2Docker and Ports Notes

### ISSUE THREAD

**Issue by alph486** [wurstmeister/kafka-docker#27]
This is maybe more of a "known issue" or documentation thing.

I've been using these images on a mac with boot2docker. I'm not 100% certain the behavior I explain below is caused by boot2docker but it's relevant I suppose since this is kind of a different environment than plain-ol-docker on linux.

When launching the fig cluster, you should be aware (obviously) that the Boot2Docker IP and associated ports may change. When developing locally make sure you are changing your env vars or code to account for this.

Additionally, when you launch the cluster certain external (localhost in our case) ports will be forwarded to the appropriate local ports on the container. For example, when running `fig ps`:

```
         Name                        Command               State                          Ports                        
----------------------------------------------------------------------------------------------------------------------
kafkadocker_kafka_1       /bin/sh -c start-kafka.sh        Up      *0.0.0.0:49160->9092/tcp*                             
kafkadocker_zookeeper_1   /bin/sh -c /usr/sbin/sshd  ...   Up      *0.0.0.0:49159->2181/tcp*, 22/tcp, 2888/tcp, 3888/tcp 
```

The external ports may change when you startup and shutdown the cluster or boot2docker. Mine tended to increment probably due to the software playing it safe or not cleaning up. This has the same implications as above: be aware you may need to change these.

More importantly though, topics that are created on the machine that may persist across restarts will be recorded with leader ports from its last session. From a describe on my topic using `$KAFKA_HOME/bin/kafka-topics.sh --describe --topic topic --zookeeper $ZK` per [the docs](http://wurstmeister.github.io/kafka-docker/):

```
root@7f2e0bdefb6b:/# $KAFKA_HOME/bin/kafka-topics.sh --describe --topic topic --zookeeper $ZK
Topic:topic     PartitionCount:4        ReplicationFactor:1     Configs:
        Topic: topic    Partition: 0    Leader: *49160*   Replicas: 49160 Isr: 49160
        Topic: topic    Partition: 1    Leader: 49160   Replicas: 49160 Isr: 49160
        Topic: topic    Partition: 2    Leader: 49160   Replicas: 49160 Isr: 49160
        Topic: topic    Partition: 3    Leader: 49160   Replicas: 49160 Isr: 49160
```

These appear to be affected by restarts. If those ports cycle, your application may not be able to determine the leader it should look for. At least this was my experience when using [Kafka Node](https://github.com/SOHU-Co/kafka-node).

This may be a good gotcha or known issue to add to docs. Or if I'm doing something wrong also something someone could correct me on :).

**Comment by wurstmeister** [comment]
Thanks for the write up. This is expected behaviour (see "ports" section [http://www.fig.sh/yml.html](http://www.fig.sh/yml.html))

The fig file provided in this project should be seen as a starting point. In order for ```fig scale``` to work the ports can't be fixed. ```fig scale``` is helpful for testing things like “what happens when i add more brokers at runtime”. 

If you want to avoid the issue you described, you can use fixed ports.

I’ve added an example of a fig file with fixed ports for a single broker setup.

```fig -f fig-single-broker.yml up```

make sure you run ```fig rm``` before to avoid any issues with existing containers.

If you don't want to use the port number as the broker id you can set the ```KAFKA_BROKER_ID``` variable in your ```environment``` section

I’ve added a note to the README 

Thanks
