### ISSUE TITLE
Tag Kafka 1.0.1

### ISSUE THREAD

**Issue by wlsc** [wurstmeister/kafka-docker#280]
Please tag the latest image with the tag "1.0.1". thus, it will be available on hub.docker

**Comment by sscaling** [comment]
This is something we're aware of. However, there are a few other minor bug fixes / changes that we'd like to merge before that. If they don't happen soon, then we'll probably just cut the 1.0.1 tag. Thanks.

**Comment by hseeberger** [comment]
+1, please publish 1.0.1 tag.

**Comment by wurstmeister** [comment]
done
