### ISSUE TITLE
on centos 7 - ERROR: Service 'kafka' failed to build

### ISSUE THREAD

**Issue by TechSgin** [wurstmeister/kafka-docker#283]
[dev@ocean kafka-docker]$ docker-compose -f docker-compose-single-broker.yml up -d
Building kafka
Step 1/10 : FROM anapsix/alpine-java
 ---> fedcd26522ec
Step 2/10 : ARG kafka_version=1.0.1
 ---> Using cache
 ---> 5e9e1bfc54e2
Step 3/10 : ARG scala_version=2.12
 ---> Using cache
 ---> 35076e89c0b6
Step 4/10 : MAINTAINER wurstmeister
 ---> Using cache
 ---> f8b57d634fdd
Step 5/10 : ENV KAFKA_VERSION $kafka_version SCALA_VERSION $scala_version KAFKA_HOME /opt/kafka
 ---> Running in bb456ce72a70
 ---> 6181265abcdb
Removing intermediate container bb456ce72a70
Step 6/10 : ENV PATH ${PATH}:${KAFKA_HOME}/bin
 ---> Running in a204e17f09db
 ---> b81298ffefe5
Removing intermediate container a204e17f09db
Step 7/10 : COPY download-kafka.sh start-kafka.sh broker-list.sh create-topics.sh /tmp/
 ---> 27c551cb3533
Removing intermediate container f84857ebba6c
Step 8/10 : RUN apk add --update unzip wget curl docker jq coreutils  && chmod a+x /tmp/*.sh  && mv /tmp/start-kafka.sh /tmp/broker-list.sh /tmp/create-topics.sh /usr/bin  && /tmp/download-kafka.sh  && tar xfz /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz -C /opt  && rm /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz  && ln -s /opt/kafka_${SCALA_VERSION}-${KAFKA_VERSION} /opt/kafka  && rm /tmp/*
 ---> Running in 4711efa6e670

fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
(1/16) Installing libattr (2.4.47-r6)
(2/16) Installing libacl (2.2.52-r3)
(3/16) Installing coreutils (8.27-r0)
(4/16) Installing libssh2 (1.8.0-r1)
(5/16) Installing libcurl (7.58.0-r1)
(6/16) Installing curl (7.58.0-r1)
(7/16) Installing libmnl (1.0.4-r0)
(8/16) Installing libnftnl-libs (1.0.7-r0)
(9/16) Installing iptables (1.6.1-r0)
(10/16) Installing device-mapper-libs (2.02.168-r3)
(11/16) Installing libseccomp (2.3.2-r0)
(12/16) Installing docker (17.05.0-r0)
Executing docker-17.05.0-r0.pre-install
(13/16) Installing oniguruma (6.3.0-r0)
(14/16) Installing jq (1.5-r3)
(15/16) Installing unzip (6.0-r2)
(16/16) Installing wget (1.19.2-r0)
Executing busybox-1.26.2-r9.trigger
Executing glibc-bin-2.27-r0.trigger
OK: 123 MiB in 42 packages
mv: cannot move '/tmp/start-kafka.sh' to a subdirectory of itself, '/usr/bin/start-kafka.sh'
mv: cannot move '/tmp/broker-list.sh' to a subdirectory of itself, '/usr/bin/broker-list.sh'
mv: cannot move '/tmp/create-topics.sh' to a subdirectory of itself, '/usr/bin/create-topics.sh'
ERROR: Service 'kafka' failed to build: The command '/bin/sh -c apk add --update unzip wget curl docker jq coreutils  && chmod a+x /tmp/*.sh  && mv /tmp/start-kafka.sh /tmp/broker-list.sh /tmp/create-topics.sh /usr/bin  && /tmp/download-kafka.sh  && tar xfz /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz -C /opt  && rm /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz  && ln -s /opt/kafka_${SCALA_VERSION}-${KAFKA_VERSION} /opt/kafka  && rm /tmp/*' returned a non-zero code: 1

**Comment by sscaling** [comment]
The error would indicate that this command failed

```
mv /tmp/start-kafka.sh /tmp/broker-list.sh /tmp/create-topics.sh /usr/bin
```

Have you tried debugging any further? Reproducing the mv command independently with other files to see if it's something wrong with the distros `mv` command?

You could try updating the command to avoid ambiguity:

```
mv -t /usr/bin /tmp/start-kafka.sh /tmp/broker-list.sh /tmp/create-topics.sh
```

It would be useful to provide the docker version, os versions etc if this problem persists.

**Comment by sscaling** [comment]
Both your kernel and docker versions look pretty old (I think both are no longer maintained/supported).

* Do other docker images build without issue? 
* Have you tried a simple test case Dockerfile such as:

```
RUN echo "a" > /tmp/a.txt && echo "b" > /tmp/b.txt && mv /tmp/a.txt /tmp/b.txt /usr/bin
```

**Comment by TechSgin** [comment]
All my dockers works fine I am running databases with it.
I have now installed the newest docker
Docker version 17.12.1-ce, build 7390fc6

I am now getting completely different error

ERROR: Service 'kafka' failed to build: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/494d64196a6f131444310ac645b27ad68be3291f3ef86e5c4a1d8c054a6483dd/log.json: no such file or directory): docker-runc did not terminate sucessfully: unknown

I will try to update the operating system as well.

**Comment by sscaling** [comment]
Apparently 3.10 is current minimum req for docker [https://docs.docker.com/engine/faq/#what-platforms-does-docker-run-on](https://docs.docker.com/engine/faq/#what-platforms-does-docker-run-on) so it should have been OK. 

I can't explain why the move doesn't work (if that is the true error). Other than breaking out each step into a separate RUN command to see where it truly fails I'm not sure what else to suggest. If I have time at the weekend, i'll try running a centos 7 VM.

**Comment by TechSgin** [comment]
Works after updating to 3.10

yum update
uname -a
Linux ocean.water 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Thanks
