### ISSUE TITLE
Problems with kubernetes 1.9

### ISSUE THREAD

**Issue by MartinX3** [wurstmeister/kafka-docker#294]
I can't used it anymore since using kubernetes 1.9

I get timeouts while sending something on the kafka bus via java spring.

Or this error message.
`Connection to node 1003 could not be established. Broker may not be available.`

**Comment by wurstmeister** [comment]
if it worked with k8s 1.8 is might be a k8s issue, once you narrowed it down to an issue with this image please re-open and provide more information on what the issue with this image is.

Thanks

**Comment by MartinX3** [comment]
Could you give me your standard yaml file to create a kubernetes service with a zookeeper pod and a kafka pod, which is working?
Then I will try to write data on the kafka bus from another service pod. :)
