### ISSUE TITLE
Error using snappy compression

### ISSUE THREAD

**Issue by jbrackett** [wurstmeister/kafka-docker#298]
I believe the cause is a missing glibc library since the base image is using Alpine. Kafka cannot load the snappy compression library which has a dependency on it.

Exception will look like this in Kafka:

```java
java.lang.NoClassDefFoundError: Could not initialize class org.xerial.snappy.Snappy
at org.xerial.snappy.SnappyInputStream.hasNextChunk(SnappyInputStream.java:435)
at org.xerial.snappy.SnappyInputStream.read(SnappyInputStream.java:466)
at java.io.DataInputStream.readByte(DataInputStream.java:265)
```

To reproduce add to Kafka with a producer that has snappy compression enabled
```java
config.put(ProducerConfig.COMPRESSION_TYPE_CONFIG, "snappy");
```

See also: https://github.com/xerial/snappy-java/issues/181

**Comment by jbrackett** [comment]
Is using Alpine a must for this project? The fix could be as simple as 
```dockerfile
FROM openjdk:8-jre-slim
```

**Comment by sscaling** [comment]
I think the main driver for using alpine is the image size

```
openjdk                      8-jre-slim          d60fc6fb46e3        2 weeks ago         205MB
openjdk                      8u151-jre-alpine    b1bd879ca9b3        2 months ago        82MB
```

We could alternatively use something like https://github.com/sgerrand/alpine-pkg-glibc

**Comment by getrdone93** [comment]
Which shared object file(s) does it try to load? I can't seem to find which one.
