### ISSUE TITLE
1.0.1 version does not support snappy compession

### ISSUE THREAD

**Issue by gburanov** [wurstmeister/kafka-docker#303]
Hi. 

I saw you recently (in this commit https://github.com/wurstmeister/kafka-docker/commit/7a25ade4cc820ec9e5a103a0b83f412008d3351e#diff-3254677a7917c6c01f55212f86c57fbf) introduced new base image

The problem with the new base image is that it lacks libc.

https://github.com/xerial/snappy-java (that is used by kafka) uses libc and fails without it

This means that snappy compression is broken now =(
Can we add extra step to install libc?

**Comment by sscaling** [comment]
Duplicates https://github.com/wurstmeister/kafka-docker/issues/298

**Comment by sscaling** [comment]
Also worth noting that 1.0.1 was cut before the change to the openjdk alpine base image. So if you simple use the wurstmeister/kafka:1.0.1 build this should address any immediate issue.
