### ISSUE TITLE
not allowed set offsets.topic.replication.factor parameter

### ISSUE THREAD

**Issue by qinlai** [wurstmeister/kafka-docker#314]
offsets.topic.replication.factor default value is 1, need set offsets.topic.replication.factor parameter for cluster.Thanks!

**Comment by sscaling** [comment]
I'm not sure what you are asking. If it is how to set this broker config parameter, then as per [Readme](https://github.com/wurstmeister/kafka-docker#pre-requisites), this can be specified by `KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR` environment variable.

**Comment by qinlai** [comment]
ok,thanks.

**Comment by elwaxoro** [comment]
Coming to this much later, found that `KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR` no longer appears in the readme

**Comment by sscaling** [comment]
@elwaxoro - the README is the same

> If you want to customize any Kafka parameters, simply add them as environment variables in docker-compose.yml, e.g. in order to increase the message.max.bytes parameter set the environment to KAFKA_MESSAGE_MAX_BYTES: 2000000. To turn off automatic topic creation set KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'

The image just translates `KAFKA_X_Y_Z` vars to `x.y.z` properties in the server.properties files. This allows you configure anything in kafka broker. You should refer to the official docs for available configuration for your kafka version: https://kafka.apache.org/documentation/#brokerconfigs.

**Comment by elwaxoro** [comment]
Perfect, thanks for the clarification.
