### ISSUE TITLE
KAFKA_JMX_OPTS causing start-kafka.sh to fail

### ISSUE THREAD

**Issue by geoffzelenka** [wurstmeister/kafka-docker#320]
Attempting to set KAFKA_JMX_OPTS will cause the start-kafka.sh script to fail with the following error:

```
kafka_1            | waiting for kafka to be ready
kafka_1            | /usr/bin/start-kafka.sh: line 107: KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port: bad substitution
threatanalytics_kafka_1 exited with code 1
```

I have KAFKA_JMX_OPTS set to:

```      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1099"```

which is what is given on the https://hub.docker.com/r/wurstmeister/kafka/ JMX configuration example.

**Comment by geoffzelenka** [comment]
The KAFKA_ option parsing also breaks when trying to set JVM options for kafka using KAFKA_HEAP_OPTS and KAFKA_JVM_PERFORMANCE_OPTS that are used in kafka's kafka-run-class.sh script.

```
$ docker-compose up kafka
Recreating threatanalytics_kafka_1 ... done
Attaching to threatanalytics_kafka_1
kafka_1            | waiting for kafka to be ready
kafka_1            | /usr/bin/start-kafka.sh: line 107: KAFKA_JVM_PERFORMANCE_OPTS=-XX:MetaspaceSize=96m -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:G1HeapRegionSize=16M -XX:MinMetaspaceFreeRatio=50 -XX:MaxMetaspaceFreeRatio: bad substitution
threatanalytics_kafka_1 exited with code 1
```

**Comment by sscaling** [comment]
Duplicates #312
