### ISSUE TITLE
The producer attempted to use a producer id which is not currently assigned to its transactional id

### ISSUE THREAD

**Issue by pedrohh** [wurstmeister/kafka-docker#322]
Hello,

I'm adding transaction support for kafka in my application. While testing transactions with this kafka-docker image, after simulating a crash in the docker image (stop and then restart), I have to call multiple times the endpoint I'm using to send messages to kafka for the application to exit an error state. I'm always receiving an exception saying that "The producer attempted to use a producer id which is not currently assigned to its transactional id". Only after 2/3 times calling that endpoint, a new transaction is created and the message is successfully delivered.

I opened an [issue in the spring-kafka project](https://github.com/spring-projects/spring-kafka/issues/660) (full code used is there) and while testing the solutions presented there, we realized that this error only occurs while using this kafka docker image. If we used kafka from homebrew this exception didn't occur. 

While I know this may not be directly related with this docker image, I was hopping that someone here may know any configuration that may be causing this.

Thanks,
Pedro

**Comment by sscaling** [comment]
Please can you include the broker configuration, exact commands used, broker logs before and after restart (as well as standard information such as version of the image, version of docker, host os type and version)

That will give everyone the best chance of trying to help with this question. Also include the docker-compose file if used and any other relevant info. 

Thanks.

**Comment by sscaling** [comment]
No response from OP, so closing due to staleness
