### ISSUE TITLE
[Performance test] Only 30% of the performance which install on host directly

### ISSUE THREAD

**Issue by MadeInChina** [wurstmeister/kafka-docker#323]
Hardware
  Processor Name:	Intel Core i7
  Processor Speed:	2.8 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
  Physical Drive:
  Device Name:	APPLE SSD SM0512G

./bin/kafka-producer-perf-test.sh --num-records 3000000 --record-size 1024 --topic test_performance --throughput 100000 --producer-props bootstrap.servers=localhost:9092

Installed on host directly
```
3000000 records sent, 109186.198864 records/sec (106.63 MB/sec), 277.12 ms avg latency, 596.00 ms max latency, 266 ms 50th, 382 ms 95th, 474 ms 99th, 588 ms 99.9th.
```

On docker
```
3000000 records sent, 31669.956823 records/sec (30.93 MB/sec), 961.29 ms avg latency, 1354.00 ms max latency, 947 ms 50th, 1123 ms 95th, 1283 ms 99th, 1331 ms 99.9th.
```

**Comment by MadeInChina** [comment]
I guess because that docker on mac are using vm.

**Comment by sscaling** [comment]
Probably worth checking your docker configuration settings as well. Depending on the version of Docker you are using, you can control how much memory / cpu cores / swap is allocated etc.

**Comment by sscaling** [comment]
Closing due to staleness. No other performance questions open / comments / +1's on this ticket. Please re-open if there is any more information to help us investigate.
