### ISSUE TITLE
KAFKA_JMX_OPTS causing start-kafka.sh to fail (Issue reopen)

### ISSUE THREAD

**Issue by maytals** [wurstmeister/kafka-docker#324]
I'm getting this error on kafka logs:

```/usr/bin/start-kafka.sh: line 107: KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port: bad substitution```

When KAFKA_JMX_OPTS is defined as:
`KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=9010"`

This error happens only when upgrading to version 1.1.0 (on version 1.0.1 it doesn't happen).

**Comment by sscaling** [comment]
@maytals - have you got the latesst 1.1.0 version? There were multiple changes made on master to fix some of these issue. There is also a test scenario to validate this: https://github.com/wurstmeister/kafka-docker/blob/master/test/scenarios/jmx/docker-compose.yml

Can you try with `wurstmeister/kafka:latest` image?

**Comment by maytals** [comment]
It works with `wurstmeister/kafka:latest`
So in which tagged version this fix will be available?

Thanks.

**Comment by matlockx** [comment]
any news?
