### ISSUE TITLE
kafka can't see logstash consumer

### ISSUE THREAD

**Issue by like-inspur** [wurstmeister/kafka-docker#332]
I install kafka cluster and logstash in docker swarm environment , and config logstash as consumers. But I can't see consumer in kafka command like this:
/opt/kafka_2.12-1.1.0/bin # ./kafka-consumer-groups.sh --bootstrap-server localhost:9092 --list
Note: This will not show information about old Zookeeper-based consumers.

**Comment by sscaling** [comment]
Hi @like-inspur - I think for anyone to help, you will need to provide more information - such as your swarm setup (multi node / aws / local), OS, configuration files (e.g. docker compose files), commands run (e.g. `docker stack`) and any logs.

Have you confirmed your Swarm configuration is correct, and you can use normal kafka operations - i.e. connect to this from outside and inside the cluster?

Does logstash even use consumer groups? This is not a mandatory requirement of consumers.

**Comment by sscaling** [comment]
Closing due to staleness. No response from OP.
