### ISSUE TITLE
Message not delivered but topic gets created

### ISSUE THREAD

**Issue by shbhsngh** [wurstmeister/kafka-docker#334]
I am using **wurstmeister/kafka** image for kafka  and **digitalwonderland/zookeeper** image for zookeeper to create kubernetes service. They are interacting using clusterIP/serviceName.
My microservices are also running on different kubernetes service within a cluster and interacting with kafka with clusterIP/serviceName.
While sending a message from microservice to kafka, **message is not being reached to broker (but topic gets created  if not available).**

here is the error which i am getting while sending message from producer shell client:
```
ERROR Error when sending message to topic TRIPS4 with key: null, value: 8 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
```

Here is content of my server.properties file:
[server.txt](https://github.com/wurstmeister/kafka-docker/files/2041435/server.txt)

Relevant parts:

```
broker.id=1
num.network.threads=3
num.io.threads=8
socket.send.buffer.bytes=102400
socket.receive.buffer.bytes=102400
socket.request.max.bytes=104857600
log.dirs=/kafka/kafka-logs-kafka-broker1-6cbc9679c6-jxgvs
num.partitions=1
num.recovery.threads.per.data.dir=1
offsets.topic.replication.factor=1
transaction.state.log.replication.factor=1
transaction.state.log.min.isr=1
log.retention.hours=168
log.segment.bytes=1073741824
log.retention.check.interval.ms=300000
zookeeper.connect=10.103.158.205:2181
zookeeper.connection.timeout.ms=6000
group.initial.rebalance.delay.ms=0
advertised.port=9092
advertised.host.name=10.99.199.230
service.service.port=9092
service.port.9092.tcp.addr=10.99.199.230
service.service.host=10.99.199.230
port=9092
service.port.9092.tcp.proto=tcp
service.port=tcp://10.99.199.230:9092
service.port.9092.tcp.port=9092
service.service.port.kafka.port=9092
service.port.9092.tcp=tcp://10.99.199.230:9092
```

Here is content of yml files
[yml.txt](https://github.com/wurstmeister/kafka-docker/files/2041445/yml.txt)

**Comment by sscaling** [comment]
It would be better to put your server.properties file and config as attachments so they are together in one issue. If you rename server.properties -> server.txt you can upload it as an attachment to this issue.

**Comment by shbhsngh** [comment]
Hi @sscaling ,
Thanks for reply.
In my case, There is only 1 broker as kubernetes service and 1 zookeeper as kubernetes service in same cluster, so I have used KAFKA_ADVERTISED_HOST_NAME as localhost (as provided in the link you have given).
I have also used kafkacat to test, Here are the details
`kafkacat  -b 10.99.199.230:9092 -C -t TRIPS`
Results:
`% ERROR: Topic TRIPS error: Broker: Leader not available`
and 
`kafkacat  -b 10.99.199.230:9092 -L -t TRIPS`
Results:
```
Metadata for TRIPS (from broker -1: 10.99.199.230:9092/bootstrap):
 0 brokers:
 1 topics:
  topic "TRIPS" with 0 partitions: Broker: Leader not available (try again)
```

**Comment by shbhsngh** [comment]
I have added kafka and zookeeper in same pod but in different container, now Leader is available:
`kafkacat  -b 10.99.199.230:9092 -L -t DRIVERS`
results
```
Metadata for DRIVERS (from broker -1: 10.99.199.230:9092/bootstrap):
 1 brokers:
  broker 1 at localhost:9092
 1 topics:
  topic "DRIVERS" with 1 partitions:
    partition 0, leader 1, replicas: 1, isrs: 1
```

but message is still not accessible by consumer
`kafkacat  -b 10.99.199.230:9092 -C -t DRIVERS`
results
```
%4|1527338659.651|PROTOERR|rdkafka#consumer-0| :9092/0: Protocol parse failure at rd_kafka_fetch_reply_handle:3155
%4|1527338659.651|PROTOERR|rdkafka#consumer-0|:9092/0: Remaining data after message set parse: 335 bytes
```
Any idea, what's wrong here?

**Comment by sscaling** [comment]
> broker 1 at localhost:9092

Looks like you have configured 'localhost' as the advertised host name. This does not resolve to your service IP from outside the cluster so the three connectivity requirements are not met. 

i.e. when kafkacat connects, it performs the bootstrap process, retrieves the metadata, finds that your topic is assigned to broker (id 1), tries to connect to that broker (on localhost) and fails.

**Comment by shbhsngh** [comment]
Thanks @sscaling , That really helped!

**Comment by sscaling** [comment]
@shbhsngh - if you have a working setup - If you have time, it would help future users if you posted the information here. Hopefully, we'll eventually have an `examples/` directory with various different example setups (i.e. swarm/kubernetes/aws ECS etc). Thanks.
