### ISSUE TITLE
Service 'kafka' failed to build:

### ISSUE THREAD

**Issue by yigubigu** [wurstmeister/kafka-docker#338]
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz: Permission denied
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz: Permission denied
ERROR: unsatisfiable constraints:
  bash (missing):
    required by: world[bash]
  curl (missing):
    required by: world[curl]
  docker (missing):
    required by: world[docker]
  jq (missing):
    required by: world[jq]
ERROR: Service 'kafka' failed to build: The command '/bin/sh -c apk add --no-cache bash curl jq docker  && mkdir /opt  && chmod a+x /tmp/*.sh  && mv /tmp/start-kafka.sh /tmp/broker-list.sh /tmp/create-topics.sh /usr/bin  && sync && /tmp/download-kafka.sh  && tar xfz /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz -C /opt  && rm /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz  && ln -s /opt/kafka_${SCALA_VERSION}-${KAFKA_VERSION} /opt/kafka  && rm /tmp/*  && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk  && apk add --no-cache --allow-untrusted glibc-${GLIBC_VERSION}.apk  && rm glibc-${GLIBC_VERSION}.apk' returned a non-zero code: 4

**Comment by sscaling** [comment]
> WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz: Permission denied

Would indicate you're behind a firewall or blocked from the remote node.

Have you tried to see if you can manually download the file? i.e.

```
curl -vvv  http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz > /dev/null
```

**Comment by sscaling** [comment]
closing due to staleness and no response from OP

**Comment by t2o2** [comment]
I got the pretty much the same error as yigubigu.

ERROR: Service 'kafka' failed to build: The command '/bin/sh -c /tmp/download-kafka.sh' returned a non-zero code: 2

After breaking the commands into individual lines. I think it is a shell issue. It can't access the /usr/bin/version.sh when executing /tmp/download-kafka.sh. ls results an empty folder /usr/bin/ when I added it in the download-kafka.sh
