### ISSUE TITLE
Backup/restore kafka and zookeeper in swarm mode

### ISSUE THREAD

**Issue by sguilly** [wurstmeister/kafka-docker#339]
First, Thank you for your work.

I would like to know which is the good way of backup a zookeeper/kafka cluster when use it in swarm mode.

BR

**Comment by sscaling** [comment]
I think that's just a general Kafka operational question, not specifically related to this image. I think you're best bet would be try the Kafka mailing list: https://kafka.apache.org/contact.html

There's a huge distribution and very active community.

Thanks.
