### ISSUE TITLE
Kafka build error

### ISSUE THREAD

**Issue by monimail** [wurstmeister/kafka-docker#340]
Hello,

I'm getting :

```ERROR: Service 'kafka' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder738158798/download-kafka.sh: no such file or directory```

Any ideas on what could cause this issue ?

Thanks.

**Comment by sscaling** [comment]
Hi @monimail  - providing additional information will help the community to have a better understanding of what you are trying to do - and hopefully provide some help.

I'd suggest, at a minimum, including:

*  host OS + version
* docker version (client + daemon)
* command used to build
* version/tag/sha of kafka-docker you are trying to build
* any other relevant information

**Comment by monimail** [comment]
Hello,

Some more information :

- My OS is Ubuntu 16.04
- Docker is the latest version I guess
- I used the docker-compose file as described in the tutorial
- I used the Dockerfile available here : https://hub.docker.com/r/wurstmeister/kafka/

In general I followed the instructions of the Docker Hub page.

**Comment by sscaling** [comment]
It sounds like you're trying to build this from the `Dockerfile` alone. If you don't want to build a pre-existing binary - then you'll need to clone this git repo so that you have all the dependencies.

**Comment by sscaling** [comment]
Closed due to no response from OP - assume solved, please re-open if still having issues after cloning repo.
