### ISSUE TITLE
Kafka resend messages

### ISSUE THREAD

**Issue by zbence** [wurstmeister/kafka-docker#341]
Kafka constantly resending messages. If I send one message then kafka delivers it but after a short period of time it again delivers out the exact same message. I really don't want that.

Anyone has met this problem before?

**Comment by zbence** [comment]
Same messages with the same offset are coming in.

I read the messages with a java application with auto commit enabled and set to 1 sec

**Comment by sscaling** [comment]
You either have a configuration issue, in which case the [Connectivity Guide](https://github.com/wurstmeister/kafka-docker/wiki/Connectivity) may help, or if this is a general Kafka question, you'd be better off posting a question on the [Kafka mailing list](https://kafka.apache.org/contact.html) where there is a much broader audience to help with Kafka specific questions.

Please re-open if you think this is a bug in the Kafka-docker image with the relevant information, such as host os, docker version, commands being run, specific setup (produce / consumer), docker-compose.yml being used if relevant etc, Along with full steps to reproduce. Thanks.
