### ISSUE TITLE
Failed to configure SSL for version 0.11.0.1

### ISSUE THREAD

**Issue by tulios** [wurstmeister/kafka-docker#342]
Hi, I'm using the `0.11.0.1` version, and I can't configure it correctly, at least not in the same way as the `0.10.2.1` version. After analyzing the `start-kafka.sh` script I think it will either replace the listeners with `PLAINTEXT` or generate duplicates which also crashes the server.

I'm using the following configuration:

```docker
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LISTENERS: "PLAINTEXT://:9092,SSL://:9093,SASL_SSL://:9094"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://${HOST_IP}:9092,SSL://${HOST_IP}:9093,SASL_SSL://${HOST_IP}:9094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_SSL:SASL_SSL
      KAFKA_SSL_KEYSTORE_LOCATION: "/var/private/ssl/certs/kafka.server.keystore.jks"
      KAFKA_SSL_KEYSTORE_PASSWORD: "testtest"
      KAFKA_SSL_KEY_PASSWORD: "testtest"
      KAFKA_SSL_TRUSTSTORE_LOCATION: "/var/private/ssl/certs/kafka.server.truststore.jks"
      KAFKA_SSL_TRUSTSTORE_PASSWORD: "testtest"
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"
      KAFKA_SASL_ENABLED_MECHANISMS: "PLAIN,SCRAM-SHA-256,SCRAM-SHA-512"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/opt/kafka/config/server-jaas.conf"
      KAFKA_CREATE_TOPICS: "topic-test:6:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./testHelpers/certs:/var/private/ssl/certs
      - ./testHelpers/kafka/server-jaas.conf:/opt/kafka/config/server-jaas.conf
```

I've managed to make it work by commenting out two sections of the script:

1) If the protocol map is defined there is a bunch of configurations and then something with the inter-broker listener name. If it's undefined, it will assume the protocol name.

```sh
# if [[ -z "$KAFKA_INTER_BROKER_LISTENER_NAME" ]]; then
#   export KAFKA_INTER_BROKER_LISTENER_NAME=$KAFKA_PROTOCOL_NAME
# fi
```

2) Then, if the inter-broker listener is defined it automatically add it to the list of brokers

```sh
# if [[ -n "$KAFKA_INTER_BROKER_LISTENER_NAME" && ! "$KAFKA_INTER_BROKER_LISTENER_NAME"X = "$KAFKA_PROTOCOL_NAME"X ]]; then
#    if [[ -n "$KAFKA_INTER_BROKER_PORT" ]]; then
#       export KAFKA_INTER_BROKER_PORT=$(( $KAFKA_PORT + 1 ))
#    fi
#    export INTER_BROKER_LISTENER="${KAFKA_INTER_BROKER_LISTENER_NAME}://:${KAFKA_INTER_BROKER_PORT}"
#    export KAFKA_LISTENERS="${KAFKA_LISTENERS},${INTER_BROKER_LISTENER}"
#    export KAFKA_ADVERTISED_LISTENERS="${KAFKA_ADVERTISED_LISTENERS},${INTER_BROKER_LISTENER}"
#    unset KAFKA_INTER_BROKER_PORT
#    unset KAFKA_SECURITY_INTER_BROKER_PROTOCOL
#    unset INTER_BROKER_LISTENER
# fi
```

I've tried in many ways to have a configuration where I can define the listeners, but I haven't managed to do that.

Is this a regression from `0.10.2.1`? I haven't been able to find any examples of this version with SSL. Commenting out the sections works but I would appreciate some guidance.

Thanks

**Comment by sscaling** [comment]
Hi, this was due to some undesirable behaviour introduce in 0.11.0.1 and removed in 1.1.0. However - it is worth noting that we will **hopefully** be changing to a more consistent way of building docker images as well as keeping them updated with security patches etc. This depends on this PR. https://github.com/wurstmeister/kafka-docker/pull/335

This should make configuration consistent with the latest version, which should set all configuration as per canonical Kafka parameters.

As an aside, you shouldn't be setting `KAFKA_ADVERTISED_HOST_NAME` and `KAFKA_ADVERTISED_LISTENERS` they are mutually exclusive: https://kafka.apache.org/documentation/#configuration

**Comment by tulios** [comment]
Nice, I'll fix the `advertised` configs. Would you generate a `0.11.0.2` after the PR?
Thanks for the reply!

**Comment by tulios** [comment]
`0.11.0.2` is in the PR, thanks!

**Comment by sscaling** [comment]
Probably won’t push that as it’s a known issue that is fixed in an open PR. Would rather fix everything than having divergence on a deprecated branch - which I don’t think has any tests (these were introduced later)
