### ISSUE TITLE
when entry container use kafka-console-producer.sh and kafka-console-consumer.sh  to  simulate send or receive msg  meet some errors

### ISSUE THREAD

**Issue by fengpf** [wurstmeister/kafka-docker#353]
HI
 I enter container  
 exec  
     $KAFKA_HOME/bin/kafka-console-producer.sh --broker-list localhost:9092 --topic test

output 
  [2018-07-06 08:54:26,644] WARN [Consumer clientId=consumer-1, groupId=console-consumer-47357] Error while fetching metadata with correlation id 69 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)

**Comment by sscaling** [comment]
Please check the [FAQ](https://github.com/wurstmeister/kafka-docker/wiki) which includes a link to the connectivity guide.

I would suggest including all information to reproduce the issue, such as docker-compose.yml config, host OS, docker versions etc. Without this information it's pretty difficult to help.

**Comment by sscaling** [comment]
Closing due to staleness. No response from OP.

**Comment by SyedMuhammadSufyian** [comment]
I am facing the same issue , Is there any update ?

**Comment by sscaling** [comment]
There was no information provided in the original issue. It looks like many of the user error tickets we get. Without more information it is impossible to say. If you have read the FAQ and Connectivity Guide and think there is an issue with the image - please open a new ticket with the relevant docker-compose files, commands used, logs and versions of OS / docker daemon etc.
