### ISSUE TITLE
Cannot read/write into topic from outside container

### ISSUE THREAD

**Issue by msartor92** [wurstmeister/kafka-docker#355]
Hi, 
we are deploing with swarm a kafka-zookeeper cluster in three hosts. We are using daehyung/zookeeper-ensemble-swarm:3.4.12 image for zookeeper hosts and your image for kafka with tag 2.11-1.1.0. 
Inside the cluster all works fine we could publish and consume message to all kafka instance, but from outside the containers we are getting 
` ERROR Error when sending message to topic test with key: 2 bytes, value: 3 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for test-71: 1526 ms has passed since batch creation plus linger time`

From outside the container we could create the topic so the problems seems to be kafka listener options. Below our setup, but we've tried also other configurations without success

`KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:19092
KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:19092
`
 
Any ideas?
Thanks in advance

Michele

**Comment by sscaling** [comment]
I think the best option is to supply the full configuration and setup information (e.g. docker-compose file, environment deployed on AWS/Google cloud/Azure, VM/Host type, commands being run etc)

The information provided is a bit limited and therefore difficult to diagnose.

**Comment by sscaling** [comment]
No response from OP so closing due to staleness.
