### ISSUE TITLE
Upgrade to Kafka 0.8.2.1

### ISSUE THREAD

**Issue by hadronzoo** [wurstmeister/kafka-docker#36]
0.8.2.1 fixed some [critical issues](https://archive.apache.org/dist/kafka/0.8.2.1/RELEASE_NOTES.html)

**Comment by wurstmeister** [comment]
done. 

available as wurstmeister/kafka:0.8.2.1

**Comment by andreimarinescu** [comment]
On docker 1.6.2 and wurstmeister/kafka:0.8.2.1 automatically creating the topics fails using the syntax described in the example (KAFKA_CREATE_TOPICS: "Topic1:1:3,Topic2:1:1"). It considers :1:3 as part of the topic name. Using just the topic name works, creating a topic with 1 partition and 1 replica. Any updates on how we can create topics automatically while specifying partitions and replicas?
