### ISSUE TITLE
Kafka producer and consumer

### ISSUE THREAD

**Issue by iamnvvicky** [wurstmeister/kafka-docker#370]
KAFKA PRODUCER & CONSUMER ( Is This Possible )

i created two instance in google cloud (VM instances)

instance 1 ip : 123:456:7:8 ----> with kafka (consumer)
instance 2 ip : 789:654:1:2 ----> without kafka  (producer)

i want to make instance 2 as a producer if i type any message in instance2  that will be consume in instance 1 

Guide me for this and as well as configuration for (config/server.properties) files

**Comment by sscaling** [comment]
This question would be better asked on the [kafka mailing list](https://kafka.apache.org/contact.html) where there is a larger, knowledgeable support base to help you with general kafka questions. As far as I can tell this isn't an issue with the kafka-docker image itself? Please re-open if you are experiencing specific issues with the kafka-docker image.
