### ISSUE TITLE
Error in setting up Kafka Zookeeper Cluster in Dockers using wurstmeister/zookeeper image

### ISSUE THREAD

**Issue by rishi007bansod** [wurstmeister/kafka-docker#372]
I am trying to setup multiple zookeeper and multiple kafka broker cluster in docker with following `docker-compose.yml` file. 

    version: '3.1'
    
    services:
      zookeeper1:
        image: wurstmeister/zookeeper
        ports:
          - "2185:2181"
      zookeeper2:
        image: wurstmeister/zookeeper
        ports:
          - "2186:2181"
        depends_on:
         - zookeeper1
      zookeeper3:
        image: wurstmeister/zookeeper
        ports:
          - "2187:2181"
        depends_on:
         - zookeeper1
         - zookeeper2
      kafka1:
        image: "wurstmeister/kafka"
        hostname: kafka1
        ports:
         - "9095:9092"
        depends_on:
         - zookeeper1
         - zookeeper2
         - zookeeper3
        environment:
         - KAFKA_ADVERTISED_HOST_NAME=kafka1
         - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
         - KAFKA_ADVERTISED_PORT=9092
         - KAFKA_BROKER_ID=1
        volumes:
         - /var/run/docker.sock:/var/run/docker.sock
      kafka2:
        image: "wurstmeister/kafka"
        hostname: kafka2
        ports:
         - "9096:9092"
        depends_on:
         - zookeeper1
         - zookeeper2
         - zookeeper3
        environment:
         - KAFKA_ADVERTISED_HOST_NAME=kafka2
         - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
         - KAFKA_ADVERTISED_PORT=9092
         - KAFKA_BROKER_ID=2
        volumes:
         - /var/run/docker.sock:/var/run/docker.sock
      kafka3:
        image: "wurstmeister/kafka"
        hostname: kafka3
        ports:
         - "9097:9092"
        depends_on:
         - zookeeper1
         - zookeeper2
         - zookeeper3
         - kafka1
         - kafka2
        environment:
         - KAFKA_ADVERTISED_HOST_NAME=kafka3
         - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
         - KAFKA_ADVERTISED_PORT=9092
         - KAFKA_CREATE_TOPICS=check_new:3:1
         - KAFKA_BROKER_ID=3
        volumes:
         - /var/run/docker.sock:/var/run/docker.sock

But zookeeper cluster does not gets 
formed. For example with command e.g. with 

    zookeeper1
    kafka-topics.sh --create --topic test --replication-factor 1 --partitions 5 --zookeeper zookeeper1:2181

 
topic is created whereas with following commands e.g. with `zookeeper2` & `zookeeper3`

    kafka-topics.sh --create --topic test --replication-factor 1 --partitions 5 --zookeeper zookeeper2:2181

OR 
 
    kafka-topics.sh --create --topic test --replication-factor 1 --partitions 5 --zookeeper zookeeper3:2181

I get error as 

    Error while executing topic command : Replication factor: 1 larger than available brokers: 0.
    [2018-07-31 09:17:55,326] ERROR org.apache.kafka.common.errors.InvalidReplicationFactorException: Replication factor: 1 larger than available brokers: 0.
     (kafka.admin.TopicCommand$)

what is the issue, is there anywhere I have to provide `broker_ids` in zookeeper image? so that zookeeper cluster will work correctly

**Comment by sscaling** [comment]
the `wurstmeister/zookeeper` image does not currently support zookeeper in replicated mode, only standalone mode - so this setup will not work. You are effectively running 3 standalone zookeepers, and kafka state is registered in one or more of them.

**Comment by imcelibate** [comment]
I had the similar issue . Made following changes in yaml 
==> KAFKA_ADVERTISED_PORT 
from 
KAFKA_ADVERTISED_PORT=9092 
to 
KAFKA_ADVERTISED_PORT=19092  

And ports ==>
From 
ports:
     - "9096:9092" 
to 
ports:
     - "19092:19092" 
the issue got resolved. 

I think the 9090, 9091,9092 ports of host were not available and the kafka servers where not getting started.

**Comment by kobvel** [comment]
@imcelibate could you share your full docker-compose file?

**Comment by imcelibate** [comment]
> @imcelibate could you share your full docker-compose file?
@kobvel sending the yaml as a text file , as I am not able to upload yaml

[docker-compose.txt](https://github.com/wurstmeister/kafka-docker/files/4621322/docker-compose.txt)
