### ISSUE TITLE
Is exposing docker.sock to containers a security issue?

### ISSUE THREAD

**Issue by nikoudel** [wurstmeister/kafka-docker#380]
According to [this](https://www.lvh.io/posts/dont-expose-the-docker-socket-not-even-to-a-container.html) it is - the containers get root access to the host.

What happens if the docker.sock volume is not mapped?

**Comment by sscaling** [comment]
https://github.com/wurstmeister/kafka-docker/wiki#why-is-varrundockersock-needed

It's down to an individual setup to determine if they want/need it - Primarily in the included docker-compose files it's there as a convenience to get things running quicker - definitely not necessary (especially in a production setup)
