### ISSUE TITLE
 Can't resolve address

### ISSUE THREAD

**Issue by theone-pang** [wurstmeister/kafka-docker#388]
environment:
      KAFKA_ADVERTISED_HOST_NAME: mq
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

 WARN [Controller id=1001, targetBrokerId=1001] Error connecting to node mq:9092 (id: 1001 rack: null) (org.apache.kafka.clients.NetworkClient)
 java.io.IOException: Can't resolve address: mq:9092

**Comment by sscaling** [comment]
Please read through the [connectivity guide](https://github.com/wurstmeister/kafka-docker/wiki/Connectivity) for help on the basics and getting started.

Without the full docker-compose file, the command used to start the broker and information on where the included log snippet came from there isn't a lot of help or information I can provide. Please re-open if this is still an issue and you can provide more information.
