### ISSUE TITLE
Kafka shutting down on the initial run with the error 'node already exists'

### ISSUE THREAD

**Issue by THPubs** [wurstmeister/kafka-docker#389]
When I try to run the docker composer for the first time it gives me the following error:

    kafka_1      | [2018-08-28 05:47:34,119] ERROR Error while creating ephemeral at /brokers/ids/1001, node already exists and owner '100620751440642057' does not match current session '100626284643549184' (kafka.zk.KafkaZkClient$CheckedEphemeral)
    kafka_1      | [2018-08-28 05:47:34,120] INFO Result of znode creation at /brokers/ids/1001 is: NODEEXISTS (kafka.zk.KafkaZkClient)
    kafka_1      | [2018-08-28 05:47:34,125] ERROR [KafkaServer id=1001] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
    kafka_1      | org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists
    kafka_1      | 	at org.apache.zookeeper.KeeperException.create(KeeperException.java:122)
    kafka_1      | 	at kafka.zk.KafkaZkClient.checkedEphemeralCreate(KafkaZkClient.scala:1518)
    kafka_1      | 	at kafka.zk.KafkaZkClient.registerBrokerInZk(KafkaZkClient.scala:84)
    kafka_1      | 	at kafka.server.KafkaServer.startup(KafkaServer.scala:257)
    kafka_1      | 	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
    kafka_1      | 	at kafka.Kafka$.main(Kafka.scala:75)
    kafka_1      | 	at kafka.Kafka.main(Kafka.scala)
    kafka_1      | [2018-08-28 05:47:34,130] INFO [KafkaServer id=1001] shutting down (kafka.server.KafkaServer)

My docker-compose.yml looks like this:

    zookeeper:
      image: wurstmeister/zookeeper:latest
      ports:
        - "2181:2181"
      hostname: zookeeper
    kafka:
      image: wurstmeister/kafka:latest
      command: [start-kafka.sh]
      ports:
        - "9092:9092"
      hostname: kafka
      environment:
        KAFKA_ADVERTISED_HOST_NAME: localhost # docker-machine ip
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_CREATE_TOPICS: "UploadFile:1:1,GetFile:1:1,TrackUpload:1:1,GetEmailContent:1:1" # topic:partition:replicas
        KAFKA_ADVERTISED_PORT: 9092
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      depends_on:
        - "zookeeper"

But when I close it and re-start it works. Any idea how to fix this?

**Comment by sscaling** [comment]
>  ERROR Error while creating ephemeral at /brokers/ids/1001, node already exists and owner '100620751440642057' does not match current session '100626284643549184'

The error message means that there is an ephemeral connection to the znode that has not been closed. e.g. you have restarted kafka but zookeeper has not detected the old, now stopped kafka has closed it's connection. 

This should not happen on the first time you create containers from the docker-compose file. Please make sure you are starting with a clean environment, i.e. `docker-compose rm -svf`.

If you want better persistence handling across restarts, make sure you configure broker ID and logs dir etc. However, this is a more advanced topic which requires a more in-depth knowledge of how Kafka is configured - please refer to the [official documentation](https://kafka.apache.org/documentation/) for full information.

**Comment by nervgh** [comment]
Hi everybody!

First of all I want to say thanks to @sscaling for his \ her comment above :+1: It guided me to attempt to use `tmpfs` for Zookeeper in development mode. So in our case this configuration works as well:

```yml
version: '3.4'
services:

  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'

  zookeeper:
    image: zookeeper:3.4
    tmpfs: "/datalog"
```

**Comment by devenpatel2** [comment]
Hi,
Even though i was using another kafka docker image, I was facing this same issue, This is what resolved the issue for me. 

Introduce a 20 second delay between zookeeper and kafka. The zookeeper has a session expiry time of 18000ms. You can thus create an entrypoint 
```bash
#!/bin/bash
sleep 20
start-kafka.sh
```

and then use this entry point when running the docker
```
    entrypoint: /tmp/entrypoint.sh
    volumes: 
        ./entrypoint:/tmp/entrypoint
```

**Comment by rakibulalam** [comment]
I don't know why. I think the zookeeper cluster-id mismatch with Kafka. clear the meta.properties.
read more: https://blog.container-solutions.com/dynamic-zookeeper-cluster-with-docker

**Comment by artshishkin** [comment]
Hello Everyone!
I was using another kafka docker image, but I had the same issue. Thanks @devenpatel2 for the advice to introduce 20 seconds delay. But I used `restart` option of docker-compose like this
```
services:

  kafka-3:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    restart: always
.
.
.
    volumes:
      - kafka_data_3:/var/lib/kafka/data
      - kafka_secrets_3:/etc/kafka/secrets
```

**Comment by jlurena** [comment]
> If you want better persistence handling across restarts, make sure you configure broker ID and logs dir etc. 

Is there any other documentation you can point us to? I've configured broker ID and logs dir and still face this issue
