### ISSUE TITLE
what should I do?thank you

### ISSUE THREAD

**Issue by patience00** [wurstmeister/kafka-docker#391]
ERROR: missing mandatory config: KAFKA_ZOOKEEPER_CONNECT

**Comment by sscaling** [comment]
You will need to set this as an environment variable - it is one of the required configurations for kafka. Please see any of the example docker compose files and/or read the connectivity guide in the wiki. Thanks.

**Comment by patience00** [comment]
Thanks a lot

**Comment by sahanmvs** [comment]
I had the same problem for a minute, realised I had made a typo in my docker-compose file
