### ISSUE TITLE
[FEATURE_REQUEST] Please add openssl binary to the image

### ISSUE THREAD

**Issue by IvanovOleg** [wurstmeister/kafka-docker#392]
Hi! I found it very difficult to automate kafka SASL_SSL configuration for this image because openssl binary is missing. According to this manual https://sharebigdata.wordpress.com/2018/01/21/generating-ssl-certificates/ we need openssl for generating and signing certificates. The problem is that host cert should be generated in keytool and then signed using openssl. I can't do everything outside container. Could you please add openssl to this image?

**Comment by sscaling** [comment]
>  I can't do everything outside container

Could you please elaborate and maybe highlight the steps that you cannot perform outside the container? Thanks in advance.

**Comment by sscaling** [comment]
Closing due to staleness  - no response from OP and no other comments/reactions from members on this ticket to indicate it is currently required.
