### ISSUE TITLE
no port exposed by default

### ISSUE THREAD

**Issue by holms** [wurstmeister/kafka-docker#396]
This seems to be quite broad practice. Every Dockerfile you'd find out there would contain `EXPOSE` directive in order to know which port should be exposed by default in local docker network. Would you accept my PR if I'd submit this fix?

**Comment by sscaling** [comment]
No, because the port is configured by the user. There is a default, but is user configurable - so having a default would end up exposing unnecessary ports if the user changes their configuration.

Thanks.
