### ISSUE TITLE
Console-consumer.sh not working

### ISSUE THREAD

**Issue by annajeanine** [wurstmeister/kafka-docker#404]
Hi everyone! I am trying to follow along the Wurstmeister Kafka-Docker tutorial but the given consumer consule command keeps erroring: 

> bash-4.4# $KAFKA_HOME/bin/kafka-console-consumer.sh --topic=test --zookeeper=$ZK
> zookeeper is not a recognized option

How can I fix this?

**Comment by sscaling** [comment]
Unfortunately - if you are using one of the more recent versions of Kafka - you will need to use `--bootstrap-server` see open ticket for more info: https://github.com/wurstmeister/kafka-docker/issues/243
