### ISSUE TITLE
No option to use Kafka Connect

### ISSUE THREAD

**Issue by bartmentech** [wurstmeister/kafka-docker#411]
For the deployment of Kafka, I make use of Kafka connect. Currently, the docker image does not support adding connectors to Kafka. See the documentation for [Kafka Connect](https://kafka.apache.org/documentation.html#connect) here.

The requirements for adding connectors to Kafka would be adding jar files to the classpath and adding a config file for the connector. This is usually ${kafka-install-root}/lib or the classpath environment variable.

Next, the connect-standalone.sh or connect-distributed would need to be called with the config file as parameter.

If there is interest in this feature, I am willing to make a pull request.

**Comment by sscaling** [comment]
This image just packages the Kafka binary. The start-up script is just a convenience for running the brokers.

As with all images, when you create a container instance, you are free to configure commands / entrypoints etc. Files / directories can be mounted in (in the case of Jars / config files) so there should be nothing to prevent you from running the Kafka connect server unless I missed something?

I'm not sure what your intention is; to run another process along side the kafka process or to replace it. If it's the former, i'd suggest [CUSTOM_INIT_SCRIPT](https://github.com/wurstmeister/kafka-docker/blob/master/start-kafka.sh#L145-L147) env var. If it's the later, it's probably better to use this image as a base image and replace the `CMD` configuration with the kafka connect requirements along with any dependencies.

However, we're always open to PRs if you find something that you think is generic and useful for other people then it'd definitely be considered. At this point though, I'm thinking that it may be more of a bespoke process that would be better as a tutorial and/or documentation.

**Comment by sscaling** [comment]
No response from OP, so closing due to staleness.
