### ISSUE TITLE
compacted topic does not seem to be working... 

### ISSUE THREAD

**Issue by GregBalajewicz** [wurstmeister/kafka-docker#419]
Hello,

I am setting up a compacted topic, like so: 
`KAFKA_CREATE_TOPICS=test:1:1:compact,test2:1:1
`

or like this in k8s yaml file: 

```
    - name: KAFKA_CREATE_TOPICS
      value: "test:1:1:compact,test2:1:1"

```
Is that all that is needed to create test as a compact topic? 
Because it does not seem to be a compact topic... it is never compacted, and old offsets are deleted after 7 days. 

I have noticed that when my kafka starts up, it reports the following config:
`log.cleanup.policy = [delete]`

Should it be set to delete, compact ?

Thank for your help!

**Comment by sscaling** [comment]
You should be able to verify the topic config with something like:

```
$ docker exec  kafka-docker_kafka_1 bash -c "kafka-configs.sh --zookeeper zookeeper --describe --entity-type topics"
Configs for topic 'test' are cleanup.policy=compact
Configs for topic 'test2' are 
```

To make this work you should have `log.cleaner.enable = true`. This is the default.

I'd expect all data to be deleted after what ever value is in `log.retention.hours` configuration (default 7 days / 168 hours). This is to stop unbounded growth of data on disk.

I imagine what is happening is that you are seeing this, rather than the cleanup.policy.

How are you populating the data in Kafka? do you have data that can be compacted? [https://kafka.apache.org/documentation/#compaction](https://kafka.apache.org/documentation/#compaction)

**What exactly are you expecting to happen during log-compaction, and how have you verified this behaviour?**

**Comment by GregBalajewicz** [comment]
In my testing, `log.retention.hours ` has to effect on compacted topic. In my test, I've got:
```
log.retention.hours = 0
log.retention.minutes = 2
```
and all regular topics get their logs cleaned up properly after 2 minutes, but the compacted topics, are not effected. However, I cannot get the compacted topic to actually compact. I have lots of (almost all ) duplicates but the compaction never kicks in and I am puzzled why. My settings are:

```
log.cleaner.backoff.ms = 15000
log.cleaner.dedupe.buffer.size = 134217728
log.cleaner.delete.retention.ms = 1000
log.cleaner.enable = true
log.cleaner.io.buffer.load.factor = 0.9
log.cleaner.io.buffer.size = 524288
log.cleaner.io.max.bytes.per.second = 1.7976931348623157E308
log.cleaner.min.cleanable.ratio = 0.001
log.cleaner.min.compaction.lag.ms = 0
log.cleaner.threads = 1
log.cleanup.policy = [compact, delete]
```

any ideas?

**Comment by GregBalajewicz** [comment]
OK, problem solved. This https://stackoverflow.com/questions/46513527/kafka-log-compaction-not-starting was the necessary clue. You need at least two log files, which can be simulated by setting really low value for log.segment.bytes

**Comment by sscaling** [comment]
@GregBalajewicz - thanks for closing the loop. I've added info to the FAQ here: https://github.com/wurstmeister/kafka-docker/wiki#topic-compaction-does-not-work

Do you have time to take a look, and see if this resolves the issues you were seeing?

**Comment by GregBalajewicz** [comment]
Yes, I am going through and trying to compile a minimal config set and will update

**Comment by GregBalajewicz** [comment]
@sscaling - I've reviewed your FAQ. it is accurate. I would considering adding one gotcha, because I found the kafka documentation not clear - Do not set LOG.CLEANUP.POLICY to "compact, delete" as this will result in a compacted topic to compact but also delete all messages (segments) that are older than the set retention time, which is probably not what one typically desires in a compact topic.

**Comment by sscaling** [comment]
I think this is getting into 'advanced configuration' territory. We can try to provide some guidance on some common areas - However, it's up to the operator to understand the broker configuration and the impact each setting has. We simply package the Kafka binary.

I'll close this ticket now. I specifically added the FAQ in this case as we've had several similar questions in the past. Hopefully this will help people in the future.

Thanks for highlighting the area actually causing a problem (lack of data) as this is not something that has been pointed out before.
