### ISSUE TITLE
JMX port for remote monitoring

### ISSUE THREAD

**Issue by igorbarinov** [wurstmeister/kafka-docker#42]
Hi! What is the best way to open JMX ports on your docker kafka for the remote monitoring? I plan to use it with docker-kafka inside the docker container. Here is a screenshot for the inspiration:

![broker list 2015-06-21 21-24-31](https://cloud.githubusercontent.com/assets/424628/8275513/f0d60f24-185b-11e5-8c5e-cc8069ba6e20.png)

**Comment by ibizaman** [comment]
I think the only way is to modify the Dockerfile and add an EXPOSE command in it. This means you will need to build the image locally. Or submitting a PR with the change.

**Comment by janantala** [comment]
Add `JMX_PORT=9999` into your env variables.
You can also specify `KAFKA_JMX_OPTS` env variable, but it's not required.

**Comment by wurstmeister** [comment]
Thanks for the answer @janantala

**Comment by IRobL** [comment]
I'm confused about how metrics work still.  Indeed I can use `KAFKA_JMX_OPTS=49999` for instance, and I can inspect the data on this port via a tool called `jconsole`, but does anyone know a way to convert this jmx port data into the http style of page that monitoring tools such as Prometheus scrape?  I'm accustomed to working with pages such as the snippet below:

```
# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 4.3461e-05
go_gc_duration_seconds{quantile="0.25"} 7.4567e-05
go_gc_duration_seconds{quantile="0.5"} 9.2285e-05
go_gc_duration_seconds{quantile="0.75"} 0.000144579
go_gc_duration_seconds{quantile="1"} 0.006251525
go_gc_duration_seconds_sum 0.397238821
go_gc_duration_seconds_count 2410
...
```

**Comment by IRobL** [comment]
I just made a bit of a breakthrough following the help folks left on gh.  I hope this helps others:

```
version=0.3.0

echo "
---
hostPort: localhost:49999
username:
password:

rules:
- pattern: ".*"
" > httpserver_sample_config.yml


# Get the jar
wget -N https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_httpserver/0.3.0/jmx_prometheus_httpserver-0.3.0-jar-with-dependencies.jar

# Note: You can use localhost:5559 instead of 5559 for configuring socket hostname.
java -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=9999 -jar jmx_prometheus_httpserver-${version}-jar-with-dependencies.jar 5559 httpserver_sample_config.yml
```

now you can `curl http://localhost:5559` and see all the metrics.

**Comment by sscaling** [comment]
@IRobL - JMX usage is documented in the [Readme.md#jmx](https://github.com/wurstmeister/kafka-docker/blob/master/README.md#jmx). 

However, It appears what you are actually asking is how to expose Prometheus metrics. The recommended way is to use the java agent (not the standalone http server as per your suggestion).

If you want more info on Kafka metrics, there are lots of documents or you could ask on the [Kafka mailing list](https://kafka.apache.org/contact.html)

**Comment by IRobL** [comment]
Correct me if I'm wrong, but I think the java agent method requires direct access to the system being monitored, whereas the stand alone http method only requires access to the port that is serving JMX data.

**Comment by sscaling** [comment]
Correct on the first point. 

The standalone http method needs access to the JMX listening port and the ephemeral service port for the RMI requests.  In the JMX instructions we use a fixed service port which is the same as the listener for simplicity of use. 

However, given your previous comment is for configuring the jmx-exporter for Prometheus - not for configuring the kafka-docker JMX image - I was pointing out that the recommended way to serve JMX metrics is to use the jmx-exporter java-agent (not the jmx-exporter stand alone server). See the second paragraph: [https://github.com/prometheus/jmx_exporter](https://github.com/prometheus/jmx_exporter)

> This exporter is intended to be run as a Java Agent, exposing a HTTP server and serving metrics of the local JVM
