### ISSUE TITLE
Topic named "test" is not set as cleanup.policy=compact 

### ISSUE THREAD

**Issue by GregBalajewicz** [wurstmeister/kafka-docker#420]
I am experiencing a strange problem with a topic named "test". No mater what I do, I cannot set it to be a compact topic. 

As I was struggling to figure out what is happening related to the first issue I posted https://github.com/wurstmeister/kafka-docker/issues/419, I finally looked at the actual resulting topic config and I realize that topic test, and only this topic, is not marked as compact and I am puzzled why! 

This is how I create all topic as part of starting kafka:
`greg:1:1:compact,test:1:1:compact,test2:1:1,test3:1:1,...`

when kafka starts, it reports: 

```
creating topics: greg:1:1:compact
creating topics: test:1:1:compact
creating topics: test2:1:1
creating topics: test3:1:1
```

However, when I actually examine the topic, i get : 
```
bash-4.4# kafka-configs.sh --zookeeper zoo --describe --entity-type topics;
Configs for topic '__consumer_offsets' are segment.bytes=104857600,cleanup.policy=compact,compression.type=producer
Configs for topic 'test' are
Configs for topic 'greg' are cleanup.policy=compact
Configs for topic 'test2' are
Configs for topic 'test3' are
```

Why isn't 'test' cleanup.policy=compact ?

**Comment by sscaling** [comment]
I cannot reproduce this issue. Have you got previous state (i.e. topic has been previously created)?

I'd try tearing everything down:

```
docker-compose rm -vfs
```

Then starting again. The logs should indicate if the topic already exists, something like

> Error while executing topic command : Topic 'test' already exists.

**Comment by GregBalajewicz** [comment]
Thanks @sscaling, you were right. I thought that restarting kafka, will update the topics as needed. But it seems that once a topic is created as non-compact, you cannot change it by simply re-running the kafka docker container with the new topic specification. My guess it probably only creates topics that do not exist and does not touch existing topic
