### ISSUE TITLE
Tutorial documents consumer test not working.

### ISSUE THREAD

**Issue by heojoon** [wurstmeister/kafka-docker#423]
Hello.
First of all , Thanks your kafka-docker code.

I found some error your tutorial site documents.

http://wurstmeister.github.io/kafka-docker/

I tested consumer part, but not working.

I couldn't found kafka-console-consumer.sh  script's  --zookeeper option.

And, I fixed myself and succeed to testing kafka consumer.

How about fix blew?
 
docker exec -it {kafka-docker_kafka_~~~~~~~} /bin/bash
$KAFKA_HOME/bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic topic --from-beginning

**Comment by sscaling** [comment]
It depends on which version of Kafka you are using. I can't remember when the options changed, but I believe the options in the tutorial work with `0.8.x`, `0.9.x` and `0.10.x`. For newer versions you'll need to use the options that you have listed.

The work to update documentation is captured in https://github.com/wurstmeister/kafka-docker/issues/407

**Comment by FinnFrotscher** [comment]
@heojoon  Solved by https://github.com/wurstmeister/kafka-docker/issues/407#issuecomment-442820032
