### ISSUE TITLE
Getting Started missing a step

### ISSUE THREAD

**Issue by arieljake-bluescape** [wurstmeister/kafka-docker#425]
http://wurstmeister.github.io/kafka-docker/

The above webpage is missing this step:

```
git clone https://github.com/wurstmeister/kafka-docker
cd kafka-docker
```

**Comment by sscaling** [comment]
There's the github / tarball / zip link on the tutorial page. 

The tutorial is pretty out-of-date (certain things won't work with newer versions of Kafka).

I've added a task to the existing issue: https://github.com/wurstmeister/kafka-docker/issues/407
