### ISSUE TITLE
[Dockerfile], Could you create a image from openjdk10?

### ISSUE THREAD

**Issue by akdj** [wurstmeister/kafka-docker#426]
Hi,  

Thank a lot for your sharing, I very like it!

Hovewer, I see an article about the resource limitation of jvm working with docker, [here](https://developers.redhat.com/blog/2017/03/14/java-inside-docker/)
And I thinks it might increase the performance if you can build kafka and zookeeper docker images from openjdk10 like this [example](https://github.com/redhat-developer-demos/java-container/blob/master/Dockerfile.openjdk10)  :)

**Comment by sscaling** [comment]
As far as I'm aware - Java 8 is the supported platform for Kafka: https://kafka.apache.org/documentation.html#java

To set Xmx/Xms parameters you can configure the `KAFKA_HEAP_OPTS` or `KAFKA_OPTS` environment vars (I can't remember which).

Currently we're using JDK 8u181, so you should be able to configure the `XX:+UnlockExperimentalVMOptions` and `-XX:+UseCGroupMemoryLimitForHeap` parameters if you want to test this out.
