### ISSUE TITLE
Failed to start kafka docker

### ISSUE THREAD

**Issue by duybinh0208** [wurstmeister/kafka-docker#43]
Hi, I followed the tutorial on http://wurstmeister.github.io/kafka-docker/ but it seems to be a problem. I cannot build the Kafka.  I did test on Ubuntu 14 64-bit.
Please help me to resolve this problem.
Thanks.
![ubuntu 64-bit-2015-06-23-13-44-35](https://cloud.githubusercontent.com/assets/1755759/8300378/546d8fe6-19ae-11e5-8bc6-851245fd1dae.png)

**Comment by ibizaman** [comment]
Could you tell the exact steps/commands you issued?
