### ISSUE TITLE
Connectivity wiki page doesn't give a working example of external connectivity

### ISSUE THREAD

**Issue by glandais-eptica** [wurstmeister/kafka-docker#431]
By default, the Kafka broker doesn't work if the port 9092 is simply opened. A dumb way is to add to docker host /etc/hosts the container name and access to Kafka with "fake" bootstrap servers kafka:9092.

An alternative is to do something similar to https://github.com/testcontainers/testcontainers-java/blob/master/modules/kafka/src/main/java/org/testcontainers/containers/KafkaContainer.java but I think they missed something as they have to start socat as a proxy!

Another better way is to use all the knowledge inside https://github.com/wurstmeister/kafka-docker/wiki/Connectivity and start a container with a precise configuration.
First, we add port 9094 as accessible, and bind /var/run/docker.sock. Then we use those properties to be able to connect to Kafka from outside of docker network :

Env var | Value | Comment
------------ | ------------- | ---------
`HOSTNAME_COMMAND` | `docker info \| grep ^Name: \| cut -d' ' -f2` | If this name is not in DNS, other containers in a different network may need to get an extra host
`PORT_COMMAND` | `docker port $(hostname) 9094/tcp \| cut -d: -f2` | The external port
`KAFKA_LISTENER_SECURITY_PROTOCOL_MAP` | `INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT` | declare INSIDE and OUTSIDE as PLAINTEXT
`KAFKA_ADVERTISED_LISTENERS` | `INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:_{PORT_COMMAND}` | advertised INSIDE as usual, OUTSIDE is reached through docker port mapping, on docker hostname and docker mapped port
`KAFKA_LISTENERS` | `INSIDE://:9092,OUTSIDE://:9094` | create two listeners, one for INSIDE traffic, one for OUTSIDE traffic
`KAFKA_INTER_BROKER_LISTENER_NAME` | `INSIDE` | use INSIDE for inter broker communication (even if we have a single Kafka)

We can then use `` `HOSTNAME_COMMAND`:`PORT_COMMAND` `` from outside as bootstrap servers :tada:

**Comment by sscaling** [comment]
The second example in the connectivity guide shows how to configure Kafka for internal and external access.

----

> By default, the Kafka broker doesn't work if the port 9092 is simply opened

What do you mean by 'opened' ?

----

Typically in a clustered environment you would want one broker per physical node so you can optimise partitions over physical disks (appeasing the IO bound nature of Kafka). This means that you can just expose the broker port over the docker bridge proxy, or run in host network mode on each node. In a testing scenario you can just run a single broker in the same way.

So for a testing scenario, by far the easiest way to start a broker accessible from inside + outside the docker network is something like https://github.com/wurstmeister/kafka-docker/blob/master/docker-compose-single-broker.yml - replacing `KAFKA_ADVERTISED_HOST_NAME ` with your public IP.
