### ISSUE TITLE
Automatically create topics

### ISSUE THREAD

**Issue by wanghaisheng** [wurstmeister/kafka-docker#44]
i add the following lines to docker-compose.yml

```
  environment:
    KAFKA_CREATE_TOPICS: "page_visits:1:1,fhir:1:3"
    KAFKA_ADVERTISED_HOST_NAME: 192.168.59.103
```

and run docker-compose up -d,when i query curl http://192.168.59.103:8082//topics, there is  only page_visits,what is wrong?

**Comment by wsimmonds** [comment]
Hi wanghaisheng,

Did you check the logs for kafka instances? If you're asking for a replication count of 3 for the topic "fhir", then it's probably failing with a message like:

kafka.admin.AdminOperationException: replication factor: 3 larger than available brokers: 1

**Comment by wanghaisheng** [comment]
@wsimmonds  thx  let me check logs

**Comment by autodidacticon** [comment]
@wanghaisheng I suspect that KAFKA_ZOOKEEPER_CONNECT isnt getting set at all; change line 13 of start-kafka.sh to 
`
export KAFKA_ZOOKEEPER_CONNECT="$(env | grep ZK.*PORT_2181_TCP= | sed -e 's|.*tcp://||' | paste -sd ,)"
`

**Comment by wanghaisheng** [comment]
@autodidacticon  let me try

**Comment by wurstmeister** [comment]
@wanghaisheng did you manage to solve your problem?

**Comment by sscaling** [comment]
No response in 1.5 years. Closing.
