### ISSUE TITLE
Unable to connect Kafka broker outside of docker-compose

### ISSUE THREAD

**Issue by akin-ozer** [wurstmeister/kafka-docker#442]
I am using docker-compose.yml and my configuration is 

      version: '2'
      services:
        zookeeper:
          image: wurstmeister/zookeeper
          ports:
            - "2181:2181"
        kafka:
          build: .
          environment:
            KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
          depends_on:
          - zookeeper

when i want to access it outside of docker-compose(or inside but i am using docker-compose v3 for that and still doesn't connect)

    version: '3'
    services:
      redis:
        image: redis
        hostname: redis
        container_name: redis
        ports:
          - "6379:6379"
      web:
        container_name: web
        build: http-source
        depends_on:
          - redis
        environment:
          SPRING_PROFILES_ACTIVE: container
        ports:
          - "8080:8080"
        external_links:
          - kafkazookeperelkstack_kafka_1
      engine:
        build: engine
        container_name: engine
        depends_on:
          - redis
        ports:
          - "8080"
        environment:
          SPRING_PROFILES_ACTIVE: container
        external_links:
          - kafkazookeperelkstack_kafka_1
      bonus-action:
        build: bonus-action
        container_name: bonus_action
        depends_on:
          - redis
        ports:
          - "8080"
        environment:
          SPRING_PROFILES_ACTIVE: container
        external_links:
          - kafkazookeperelkstack_kafka_1

notes: 
- I am using kafka appender for log4j2 and tested with this image from localhost:9092 and it works without problem

- Using kafka:29092 to connect to broker

**Comment by sscaling** [comment]
https://docs.docker.com/compose/compose-file/#external_links

> If you’re using the version 2 or above file format, the externally-created containers must be connected to at least one of the same networks as the service that is linking to them. Links are a legacy option. We recommend using networks instead.

I'm not sure how the two separate compose created networks are linked given the information provided.

You have not published the Kafka ports into the network, so as far as I'm aware only containers on the same network as Kafka will be able to connect to it.

---

> I am using kafka appender for log4j2 and tested with this image from localhost:9092 and it works without problem

I'm not sure how this would work. You have not published port 9092 to the host. You'd need to provide a minimal reproducible example with the commands that you ran to investigate this further. it is unclear where this was run from and what was run. In general I'd always recommend verifying connectivity with a simpler tool such as `kafkacat` so you can give one-liner examples of failing commands for consuming / producing data.

However, with all that said - this appears to be a configuration issue - not an issue with the image as far as I can see.

**Comment by akin-ozer** [comment]
Thanks for quick response.

> I'm not sure how this would work. You have not published port 9092 to the host. You'd need to provide a minimal reproducible example with the commands that you ran to investigate this further. it is unclear where this was run from and what was run. In general I'd always recommend verifying connectivity with a simpler tool such as kafkacat so you can give one-liner examples of failing commands for consuming / producing data.

I added localhost:9092 previous version of the file and tested it works fine with elk stack and docker image based kafka there are no problems there(spring project wasn't dockerized), but i wonder if this connection failure might be happening from "spring image with log4j2 kafka appender" which cannot resolve broker name somewhat. Elk stack can resolve the kafka:29092 also.

> I'm not sure how the two separate compose created networks are linked given the information provided.
You have not published the Kafka ports into the network, so as far as I'm aware only containers on the same network as Kafka will be able to connect to it.

I tried with all of them in same docker-compose and thought maybe it was caused from having incompatible docker-compose versions so i tried to seperate it just before creating this issue. 

My latest question is can this image used by docker-compose version 3.x?

**Comment by akin-ozer** [comment]
I am so sorry, it was caused corrupted jar not really working well. If anyone sees this problem at your projects check ".jar" files and images. Both Log4j2 and Elk stack is compatible with this image and yes you can use docker-compose 3.0 as far as i can tell.
