### ISSUE TITLE
Kafka 0.8.2 has the wrong mirror

### ISSUE THREAD

**Issue by vincent-ogury** [wurstmeister/kafka-docker#444]
The installation of the tags 0.8.2 failed because it uses a mirror that doesn't contain this version anymore.

I have made this patch to make it work:
```
commit ca869d5a0638a5373f0e88476647ed8c67485a67
Author: Vincent Bachelier <vincent@ogury.co>
Date:   Mon Nov 19 16:36:11 2018 +0100

    fix mirror

diff --git a/download-kafka.sh b/download-kafka.sh
index 2ddc911..6a27d4f 100755
--- a/download-kafka.sh
+++ b/download-kafka.sh
@@ -1,5 +1,6 @@
 #!/bin/sh

 mirror=$(curl --stderr /dev/null https://www.apache.org/dyn/closer.cgi\?as_json\=1 | jq -r '.preferred')
+mirror=https://archive.apache.org/dist/
 url="${mirror}kafka/${KAFKA_VERSION}/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz"
 wget -q "${url}" -O "/tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz"
```

Can you fix this version (and maybe the previous one ?).

I think the outdated package is removed from the main server and move to the archive one.

Thanks

**Comment by sscaling** [comment]
This is already the case, as per the current kafka-download.sh script - https://github.com/wurstmeister/kafka-docker/blob/master/download-kafka.sh#L8-L12.

I would suggest updating to the most recently maintained version of the `0.8.x` branch - `wurstmeister/kafka:2.10-0.8.2.2`

**Comment by vincent-ogury** [comment]
I don't see this branch on the project.
I have fix my docker compose this way:

```
version: '2'
services:
  kafka:
    build:
      context: kafka-local
      args:
        - kafka_version=0.8.2.2
        - scala_version=2.10
```

The kafka-local is link to the master branch.

**Comment by sscaling** [comment]
We don't maintain branches / tags any more. `master` is always the current release version of any kafka image (including all security updates etc). This is built in travis-ci upon any merge to master (see https://github.com/wurstmeister/kafka-docker/blob/master/.travis.yml)

The image is available from docker hub with `wurstmeister/kafka:2.10-0.8.2.2` (https://hub.docker.com/r/wurstmeister/kafka/tags)
