### ISSUE TITLE
404 Not Found Error

### ISSUE THREAD

**Issue by dixon1e** [wurstmeister/kafka-docker#448]
After logging into Docker hub, and then running the docker-compose up command, the following error occurs:

```
wget: server returned error: HTTP/1.1 404 Not Found
ERROR: Service 'kafka' failed to build: The command '/bin/sh -c apk add --no-cache bash curl jq docker  && mkdir /opt  && chmod a+x /tmp/*.sh  && mv /tmp/start-kafka.sh /tmp/broker-list.sh /tmp/create-topics.sh /usr/bin  && sync && /tmp/download-kafka.sh  && tar xfz /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz -C /opt  && rm /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz  && ln -s /opt/kafka_${SCALA_VERSION}-${KAFKA_VERSION} /opt/kafka  && rm /tmp/*  && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk  && apk add --no-cache --allow-untrusted glibc-${GLIBC_VERSION}.apk  && rm glibc-${GLIBC_VERSION}.apk' returned a non-zero code: 1
```

**Comment by sscaling** [comment]
You'll need to provide more information. 

The full build log would be handy, then version / commit you are trying to build. Also, we've seen issues with some people running this on Windows, so host OS and docker version help. If you are not trying to build, i'd suggest changing the docker-compose.yml to use a pre-built image, rather than building from source, e.g.

```
  kafka:
    image: wurstmeister/kafka
   ... snip ...
```

**Comment by dixon1e** [comment]
Thanks for your fast answer, and of course I should have added all the configuration info. My bad.

Having said that, I am using it on a Mac High Sierra and just tried it on a different Mac using Sierra and it works. I changed from wget to curl on the High Sierra system and the build worked. 

It's not clear why wget was not working, but I am not going to investigate it any further.

Closing.
