### ISSUE TITLE
Dockerfile Problem '/opt' directory exists

### ISSUE THREAD

**Issue by angeloparchitelli** [wurstmeister/kafka-docker#457]
In Dockerfile there is a problem with RUN command. 
A `/opt` directory exists. This causes the block of composition on a 12 layer. 
Removing `mkdir /opt` command, the `docker-compose up` ends without problem.

**Comment by sscaling** [comment]
[travis-ci](https://travis-ci.org/wurstmeister/kafka-docker/builds/487853696) says otherwise (as does my local machine). Please can you provide more information (what version of docker, OS etc are you using.
