### ISSUE TITLE
How to use ensemble(multi node zookeeper)?

### ISSUE THREAD

**Issue by dhsingh** [wurstmeister/kafka-docker#46]
How to use ensemble(multi node zookeeper)?

I already setup multi node zookeeper on native environment but How can we implement it in docker build.

Thanks

**Comment by ibizaman** [comment]
Could docker compose suit your needs?

**Comment by vanthome** [comment]
Usually, you allow for a list of ZK hosts like here:

https://github.com/sheepkiller/kafka-manager-docker

**Comment by kevinleeTCA** [comment]
just find a docker image of zookeeper like this https://github.com/fabric8io/fabric8-zookeeper-docker
and hook up in ur docker machine.
editing "KAFKA_ZOOKEEPER_CONNECT" of ur kafka container environmental variable to be the hostname of the zookeeper container like (zk-1:2181,zk-2:2181,zk-3:2181)

**Comment by sscaling** [comment]
Closing due to staleness
