### ISSUE TITLE
HOSTNAME_COMMAND is evaluated

### ISSUE THREAD

**Issue by AndyGee** [wurstmeister/kafka-docker#466]
Unable to parse EXTERNAL://_{HOSTNAME_COMMAND}:9092 to a broker endpoint

Where the following is provided:

-e "HOSTNAME_COMMAND=ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1"

**Comment by sscaling** [comment]
I think `$4` will get interpreted by your shell before being passed to the docker daemon. You'll need to escape the backslash, e.g.

not escaped 

```
$ docker run --rm --entrypoint /bin/bash wurstmeister/kafka -c "ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1"
60: eth0    inet 172.17.0.2
```

escaped

```
$ docker run --rm --entrypoint /bin/bash wurstmeister/kafka -c "ip -o -4 addr list eth0 | awk '{print \$4}' | cut -d/ -f1"
172.17.0.2
```

**Comment by AndyGee** [comment]
That did the trick @sscaling , thank you for the catch!

**Comment by AndyGee** [comment]
Actaully, here's one that works better out of the box:
```
ip -4 addr show eth0 | grep -Po 'inet \K[\d.]+
```
