### ISSUE TITLE
Failed to connect external Zookeeper. known issue? or Kafka.NIO limit?

### ISSUE THREAD

**Issue by Zhaojp-Frank** [wurstmeister/kafka-docker#47]
Hi, 
I can run it successfully if deploy both zk and kafka container in the same host, so they're "link" together. however, it failed if host1.kafka container to connect to another host2's zk (port is exported as confirmed), 
a known issue/limit? shall I config some network route? I am using default Docker daemon NAT mode.

but in the meantime, if I exec into the host1.kafka container, I can ping/ssh host2 w/o problem. so suppose the default eth0 are pipe to host1 NAT and the traffic shall be ok. I doubt "kafka" java NIO 's problem ? need some guidance. thanks. 

here's my cmd to start host1.kafka, trying to connect zk at host2:port
[root@localhost config]# docker run --privileged -e KAFKA_BROKER_ID=2 -e KAFKA_ZOOKEEPER_CONNECT=<host2IP>:49181 -e KAFKA_ADVERTISED_HOST_NAME=<Host1IP> --expose=9092 --publish-all=true -v /var/run/docker.sock:/var/run/docker.sock -d kafkadocker_kafka

Error Msg: 
[2015-07-31 13:35:03,765] INFO Opening socket connection to server 10.62.98.242/10.62.98.242:49181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2015-07-31 13:35:04,776] WARN Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.NoRouteToHostException: No route to host
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:601)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
Host1.kafka ifconfig output:
root@615282cdba8c:/# ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:ac:11:00:08
          inet addr:172.17.0.8  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:acff:fe11:8/64 Scope:Link
          UP BROADCAST RUNNING  MTU:1500  Metric:1
          RX packets:23 errors:0 dropped:0 overruns:0 frame:0
          TX packets:23 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:2038 (2.0 KB)  TX bytes:1814 (1.8 KB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:6 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:448 (448.0 B)  TX bytes:448 (448.0 B)

But actually I can ping host2
root@615282cdba8c:/# ping 10.62.98.242
PING 10.62.98.242 (10.62.98.242) 56(84) bytes of data.
64 bytes from 10.62.98.242: icmp_seq=1 ttl=64 time=0.236 ms
64 bytes from 10.62.98.242: icmp_seq=2 ttl=64 time=0.101 ms
64 bytes from 10.62.98.242: icmp_seq=3 ttl=64 time=0.090 ms
64 bytes from 10.62.98.242: icmp_seq=4 ttl=64 time=0.091 ms

**Comment by Zhaojp-Frank** [comment]
there's some typo. cmd shall be this:
[root@localhost config]# docker run --privileged -e KAFKA_BROKER_ID=2 -e KAFKA_ZOOKEEPER_CONNECT=<host2IP>:49181 -e KAFKA_ADVERTISED_HOST_NAME= <host1> --expose=9092 --publish-all=true -v /var/run/docker.sock:/var/run/docker.sock -d kafkadocker_kafka

**Comment by Zhaojp-Frank** [comment]
I confirm it's firewall issue, and resolved when I add the host.firewall rule
firewall-cmd  --zone=trusted --add-interface=docker0 // centos, add eth0 as trusted

**Comment by wurstmeister** [comment]
Thanks
