### ISSUE TITLE
DNS lookup error while running docker-compose up -d

### ISSUE THREAD

**Issue by viveksinghggits** [wurstmeister/kafka-docker#471]
I am getting below error while running `docker-compose up -d` on my machine
`WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz: DNS lookup error`

Below are the details of the machine that I have

```
 Operating System: Red Hat Enterprise Linux
       CPE OS Name: cpe:/o:redhat:enterprise_linux:7.5:GA:server
            Kernel: Linux 3.10.0-862.20.2.el7.x86_64
      Architecture: x86-64

```
Docker compose details 
```
# docker-compose version
docker-compose version 1.23.2, build 1110ad0
docker-py version: 3.6.0
CPython version: 2.7.5
OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017

```

**Comment by sscaling** [comment]
Behind a proxy? (https://github.com/wurstmeister/kafka-docker/issues/465)

You should can specify the image in the docker-compose.yaml if you don’t want to build it, e.g.

   image: wurstmeister/kafka:2.12_2.1.0

**Comment by viveksinghggits** [comment]
yes I am being the proxy. let me look at #465 .

**Comment by viveksinghggits** [comment]
I added the proxy details in the Dockerfile and `docker-compose up -d` progressed for some steps and got stuck in another one.
That is again proxy related issue 
```
Connecting to <proxy>
wget: error getting response: Invalid argument
```
Looking into that now.

**Comment by sscaling** [comment]
No update from OP, so closing.
