### ISSUE TITLE
Failed to acquire lock on file .lock in /kafka/kafka-logs-bba7b75cdada

### ISSUE THREAD

**Issue by jpvds** [wurstmeister/kafka-docker#477]
I have this running on my macbook : 

```
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                                NAMES
bba7b75cdada        wurstmeister/kafka       "start-kafka.sh"         9 seconds ago       Up 7 seconds        0.0.0.0:9092->9092/tcp                               kafka_kafka_1
0fee1904f490        wurstmeister/zookeeper   "/bin/sh -c '/usr/sb…"   9 seconds ago       Up 7 seconds        22/tcp, 2888/tcp, 3888/tcp, 0.0.0.0:2181->2181/tcp   kafka_zookeeper_1
```

And then get the following error running : `docker exec kafka_kafka_1 start-kafka.sh localhost zookeeper:2181`

```
ERROR [KafkaServer id=1001] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.apache.kafka.common.KafkaException: Failed to acquire lock on file .lock in /kafka/kafka-logs-bba7b75cdada. A Kafka instance in another process or thread is using this directory.
```

I've redeployed with docker-compose a few times to no avail. Any ideas? thanks !

**Comment by sscaling** [comment]
> docker exec kafka_kafka_1 start-kafka.sh localhost zookeeper:218

It looks like you have a running broker which you try to `exec` into and execute the `start-kafka.sh` script. This tries to start a second Kafka process on the running node which gives you the error.

What are you trying to do?

**Comment by jpvds** [comment]
Yes, apologies, I misread the "Kafka Shell" section here http://wurstmeister.github.io/kafka-docker/ 
Thanks for the quick response.
