### ISSUE TITLE
Offer non-root access base Zookeeper options.

### ISSUE THREAD

**Issue by mmacheerpuppy** [wurstmeister/kafka-docker#479]
[Currently you assign root SSH access to all the machines running your Docker compose script (which inherits your Zookeeper image which inherits this base image).](https://github.com/wurstmeister/docker-base/blob/master/Dockerfile#L7)

[You should probably notify users of your script that this is not intended for production use in the documentation....](https://github.com/wurstmeister/docker-base/blob/master/Dockerfile#L7)

**Comment by sscaling** [comment]
That is not related to this image. Please see the Dockerfile (https://github.com/wurstmeister/kafka-docker/blob/master/Dockerfile#L1) - we use the openjdk base image.

**Comment by mmacheerpuppy** [comment]
@sscaling https://github.com/wurstmeister/kafka-docker/blob/master/docker-compose-single-broker.yml The single broker compose Yaml doesn't.

**Comment by sscaling** [comment]
Please see response here https://github.com/wurstmeister/kafka-docker/issues/480
