### ISSUE TITLE
failed: Host is unreachable 

### ISSUE THREAD

**Issue by liuhanjia** [wurstmeister/kafka-docker#488]
```
WARNING: [pool www] child 18 said into stderr: "%3|1555660765.754|ERROR|rdkafka#producer-2| [thrd:192.168.4.99:32769/bootstrap]: 192.168.4.99:32769/bootstrap: Connect to ipv4#192.168.4.99:32769 failed: Host is unreachable (after 1002ms in state CONNECT)"
```

docker

```
1fa9482b6dfc        kafkadocker_kafka        "start-kafka.sh"         2 days ago          Up 2 days           0.0.0.0:32769->9092/tcp                              kafkadocker_kafka_1
```

host ip ：`192.168.4.99`

code：

```
 const TEST_KAFKA_BROKERS = "192.168.4.99:32769";

    public function rkProduce()
    {
        try {
                Log::info('生产消息：---');
                //$topicName = sprintf('test_rdkafka_%s', uniqid());
                $topicName = sprintf('test_0419_0616');
                $producer = new \RdKafka\Producer();
                $producer->addBrokers(self::TEST_KAFKA_BROKERS);
                $topic = $producer->newTopic($topicName);
```

**Comment by liuhanjia** [comment]
1fa9482b6dfc        kafkadocker_kafka        "start-kafka.sh"         2 days ago          Up 2 days           0.0.0.0:32769->9092/tcp                              kafkadocker_kafka_1

**Comment by sscaling** [comment]
To provide any assistance you'll need to provide more information. However, it looks like it's most likely a basic configuration error. Have you read the [Connectivity Guide](https://github.com/wurstmeister/kafka-docker/wiki/Connectivity).

Without any further information, I'd guess that your `advertised.host` + `advertised.port` / `advertised.listeners` are not configured correctly.

At a minimum your container configuration (`docker run` args or `docker-compose.yml` file) and log files. 

I'm not sure what you are using to connect to the brokers, but i'd recommend validating with something like [kafkacat](https://github.com/edenhill/kafkacat) before trying to write your own code (i.e. validate the brokers are configured correctly first, then implement your code).

**Comment by sscaling** [comment]
no response from OP so closing due to staleness.
