### ISSUE TITLE
How to configure multiple ip with same port?

### ISSUE THREAD

**Issue by wangshifeng** [wurstmeister/kafka-docker#489]

**Comment by sscaling** [comment]
Please can you clarify the question? "multiple IP" would imply multiple NICs (virtual/physical) or separate nodes. Unless you're talking about internal docker IPs in which case the [tutorial](http://wurstmeister.github.io/kafka-docker/) and [Connectivity Guide](https://github.com/wurstmeister/kafka-docker/wiki/Connectivity) cover this

Perhaps you can state what you are trying to achieve and provide details of what you have tried so far? i.e. docker-compose files / `docker run` commands.

**Comment by sscaling** [comment]
Closing due to lack of info and no response from OP.
