### ISSUE TITLE
docker-compose scale kafka=3 出现报错

### ISSUE THREAD

**Issue by yangbo1987** [wurstmeister/kafka-docker#494]
执行命令 docker-compose up --scale kafka1=3
Creating network "kafka_default" with the default driver
WARNING: The "kafka1" service specifies a port on the host. If multiple containers for this service are created on a single host, the port will clash.
Creating kafka_zookeeper_1 ... done
Creating kafka_kafka1_1    ... error
Creating kafka_kafka1_2    ... error
Creating kafka_kafka1_3    ... done

ERROR: for kafka_kafka1_1  Cannot start service kafka1: b'driver failed programming external connectivity on endpoint kafka_kafka1_1 (abb30c31e12b97df65fb0203ccab48d55314b435564d24ffad49a0b76fd124f2): Bind for 0.0.0.0:9091 failed: port is already allocated'

ERROR: for kafka_kafka1_2  Cannot start service kafka1: b'driver failed programming external connectivity on endpoint kafka_kafka1_2 (38e7af352d82724a7cd819d1922436d8ebd7e61ddd7cb73956efe0b51d99e170): Bind for 0.0.0.0:9091 failed: port is already allocated'

ERROR: for kafka1  Cannot start service kafka1: b'driver failed programming external connectivity on endpoint kafka_kafka1_1 (abb30c31e12b97df65fb0203ccab48d55314b435564d24ffad49a0b76fd124f2): Bind for 0.0.0.0:9091 failed: port is already allocated'
ERROR: Encountered errors while bringing up the project.

**Comment by yangbo1987** [comment]
docker-compose.yml如下
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper   ## 镜像
    ports:
      - "2181:2181"                 ## 对外暴露的端口号
  kafka1:
    image: wurstmeister/kafka       ## 镜像
    volumes: 
        - /etc/localtime:/etc/localtime ## 挂载位置（kafka镜像和宿主机器之间时间保持一直）
    ports:
      - "9091:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.38   ## 修改:宿主机IP
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181       ## 卡夫卡运行是基于zookeeper的

**Comment by sscaling** [comment]
> WARNING: The "kafka1" service specifies a port on the host. If multiple containers for this service are created on a single host, the port will clash.

>  Bind for 0.0.0.0:9091 failed: port is already allocated

You cannot map multiple services to the same port on the host. This is explained in the [Connectivity Guide](https://github.com/wurstmeister/kafka-docker/wiki/Connectivity).

You will have to remove the host binding of the port, i.e.

```
ports:
  - "9092"
```
