### ISSUE TITLE
Would like exact path to docker-compose.yml file in instructions

### ISSUE THREAD

**Issue by cwoodruf** [wurstmeister/kafka-docker#495]
The instructions assume that the reader knows where the docker-compose.yml file is when the docker image is installed via the docker-compose pull command. I'm not having much luck seeing where this file is to modify it in the way described. 

Could we have more explicit instructions on this step to save time?

**Comment by cwoodruf** [comment]
I cloned the github repo and used that. 
However, I'm not clear what docker-compose pull is doing in this case. I feel like the instructions are missing steps in either case.

**Comment by sscaling** [comment]
Which instructions?

There is a link to the docker-compose.yml in the README, under 'Pre-requisites'

**Comment by sscaling** [comment]
No response from OP so closing.

**Comment by cwoodruf** [comment]
Hi, I've been ill for the last week. What I am referring to is the documentation on the main page of your website for how to use the docker image. If the end user has never used docker before they aren't going to have enough information to actually use it. The only way I could use it was to download the github project and build and run the image from there.

________________________________
