### ISSUE TITLE
How to limit kafka-logs-* size?

### ISSUE THREAD

**Issue by Jenuce** [wurstmeister/kafka-docker#496]
I have fond that  kafka-logs-* of docker/volumes is very big, how can I limit the size?  only several days, it is larger then 40G

**Comment by sscaling** [comment]
Look at the `log.retention.xxx` settings in the documentation: https://kafka.apache.org/documentation/

If you are using message keys, you may also be looking for topic compaction: https://kafka.apache.org/documentation/#compaction
