### ISSUE TITLE
start-kafka-shell.sh unable to find the image

### ISSUE THREAD

**Issue by vahuja4** [wurstmeister/kafka-docker#505]
I used the docker-compose-single-broker.yml script and here is the output of `docker ps`

```
iseadmin@iseadmin:~/kafka/kafka-docker$ docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                                NAMES
e0fc6c57f4ae        wurstmeister/zookeeper   "/bin/sh -c '/usr/sb…"   26 minutes ago      Up 26 minutes       22/tcp, 2888/tcp, 3888/tcp, 0.0.0.0:2181->2181/tcp   kafkadocker_zookeeper_1
f60c99c6e745        kafkadocker_kafka        "start-kafka.sh"         26 minutes ago      Up 26 minutes       0.0.0.0:9092->9092/tcp                               kafkadocker_kafka_1
```

But when I run the command below:
`./start-kafka-shell.sh HOST_IP HOST_IP:2181`, I get the following message:
`Unable to find image 'wurstmeister/kafka:latest' locally
latest: Pulling from wurstmeister/kafka
`

Can someone please tell me what is wrong? I am running this on Ubuntu 16.04.

**Comment by sscaling** [comment]
Could you try to elaborate what the exact issue is? You don't have the image locally so it needs to be pulled from dockerhub.

**Comment by sscaling** [comment]
No response from OP so closing.
