### ISSUE TITLE
How to manually mount volume for kafka through docker-compose file

### ISSUE THREAD

**Issue by bhavik5** [wurstmeister/kafka-docker#511]
whenever I tried to stop & start the kafka container, it will flush all data & starts again.
how can I mount volume, so that data persists even when container stops or automatically restarts.

I have tried following:
``` YML
    volumes:
      - /kafka:/kafka-volume
```

Data stores inside logs file in provided folder, but whenever container restarts it will not fetch data from folder & starts a fresh copy of container.

**Comment by sscaling** [comment]
See answer in this comment: https://github.com/wurstmeister/kafka-docker/issues/360#issuecomment-407081463

Looking at your `volumes` definition, if you haven't provided a custom `logs.dir` location, you'll want to map

```
- /path/on/host:/kafka
```

**Comment by sscaling** [comment]
No response from OP, closing due to staleness.

**Comment by bhavik5** [comment]
I have provided custom directory in ```logs.dir``` for logging, by going inside docker container of wurstmeister/kafka-docker. How can I mount the folder to the container that saves data of kafka. So that container can fetch data from that foler whenever it restarts.

**Comment by sscaling** [comment]
> I have provided custom directory in logs.dir for logging, by going inside docker container of wurstmeister/kafka-docker

I'm not sure what you mean.

>  How can I mount the folder to the container that saves data of kafka. So that container can fetch data from that foler whenever it restarts.

As previously stated - you'll need the log dir configuration fixed so you can mount it through and that needs to match the broker ID so meta data information matches, e.g.

```
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LOG_DIRS: /logs
      ... snip ...
    volumes:
      - ./logs:/logs
      ... snip ...
```

**NOTE**: there was a typo in previous comment which I have corrected. `log.dirs` > `logs.dir`. Please refer to the canonical [kafka documentation](http://kafka.apache.org/documentation/) for
