### ISSUE TITLE
How to specify that the kafka and zookeeper containers should run inside the default bridge network

### ISSUE THREAD

**Issue by vahuja4** [wurstmeister/kafka-docker#512]
Currently, when I do `docker-compose -f docker-compose-singlebroker.yml up`, it runs the containters in a separate docker network, and not the default `bridge` network. Can someone please tell me how to stop the creation of this new network and have the containers run within the default docker network?

I have read that for every service in the yml file, if we specify `network_mode: bridge`, then docker-compose will not create a new network and the containers will run in the default bridge network, but when I tried this I got the following error:

```
zookeeper_1  | 2019-06-25 10:44:24,533 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@949] - Client attempting to establish new session at /172.16.20.1:39248
zookeeper_1  | 2019-06-25 10:44:24,534 [myid:] - INFO  [SyncThread:0:ZooKeeperServer@694] - Established session 0x1005e18f8520011 with negotiated timeout 30000 for client /172.16.20.1:39248
zookeeper_1  | 2019-06-25 10:44:24,570 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@376] - Unable to read additional data from client sessionid 0x1005e18f8520010, likely client has closed socket
zookeeper_1  | 2019-06-25 10:44:24,571 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1056] - Closed socket connection for client /172.16.20.1:39244 which had sessionid 0x1005e18f8520010
zookeeper_1  | 2019-06-25 10:44:24,572 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@376] - Unable to read additional data from client sessionid 0x1005e18f8520011, likely client has closed socket
zookeeper_1  | 2019-06-25 10:44:24,573 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1056] - Closed socket connection for client /172.16.20.1:39248 which had sessionid 0x1005e18f8520011
zookeeper_1  | 2019-06-25 10:44:26,614 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@215] - Accepted socket connection from /172.16.20.1:39256
```

**Comment by sscaling** [comment]
The default bridge network is deprecated and will most likely not provide the requirements that Kafka needs (containers only talk to each other via IP). https://docs.docker.com/network/bridge/#differences-between-user-defined-bridges-and-the-default-bridge.

Perhaps you could explain why you are trying to add it to the default bridge, i.e. what is the end-goal? Is this to facilitate firewall configuration or something else?

**Comment by vahuja4** [comment]
@sscaling, I have containers in the bridge network which need to talk to the kafka/zookeeper containers.

**Comment by sscaling** [comment]
Well, if you really want to use the deprecated default bridge network this sounds like a general Docker question. I don't think that's anything we can help you with - perhaps trying the Docker community might be a good starting point https://www.docker.com/docker-community

**Comment by vahuja4** [comment]
@sscaling, please take a look at the following bits of information and help me:

docker-compose-single-broker.yml
`version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOSTNAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock`

Now, the following piece of code runs in a docker container within the bridge network:

`const Producer = kafka.Producer;
    const client = new kafka.Client("localhost:2181");
    console.log("CLIENT = ", client)
    //const client = new kafka.Client();
    const producer = new Producer(client);
    const kafka_topic = 'hello-topic';
   //code here which receives an event - this works fine

               let payloads = [{topic:kafka_topic ,messages:JSON.stringify(event_payload),  partition: 0 }]
            let push_status = producer.send(payloads, (err, data) => {
                if (err) {
                console.log(err);
                } else {
                console.log('[kafka-producer -> '+kafka_topic+']: broker update success');
                }
            });
`
The `console.log(err)` gives me `Broker not available`

**Comment by sscaling** [comment]
This still sounds like a general configuration issue. Have you read the [Connectivity Guide](https://github.com/wurstmeister/kafka-docker/wiki/Connectivity)?

You're question is not very precise - so it's a bit difficult to provide any specific help. For example

> the following piece of code runs in a docker container within the bridge network:

Which bridge network. Previously you said code runs in the default bridge network, but in the provided docker-compose.yml you are using an isolated bridge network.

---

If everything is running in the same isolated bridge network (created by docker-compose), you should only need

```
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
```

Then your Kafka broker connection string would look like `kafka:9092`.

I'd recommend using something like [kafkacat](https://github.com/edenhill/kafkacat) to verify connectivity from inside the network as that requires no custom code and can be used such as `kafkacat -b kafka:9092 [... other params]`

**Comment by sscaling** [comment]
No response from OP, closing due to staleness.

**Comment by sscaling** [comment]
@cloutiertyler - it would depend on your config. Which config is the "exact config" that you are referring to - there isn't a complete example that you could re-use anywhere in the ticket. 

>  Connection to node 1001 (kafka/172.18.0.4:32778) could not be established. Broker may not be available

Would indicate the advertised port is the ephemeral one assigned by docker, this shouldn't be the case if you have

```
    ports:
      - "9092:9092"
```

So it just seems like a basic configuration error. Have you read the [Connectivity Guide](https://github.com/wurstmeister/kafka-docker/wiki/Connectivity)?
