### ISSUE TITLE
2.12-2.3.0 tag is not available on docker hub

### ISSUE THREAD

**Issue by bobbyio** [wurstmeister/kafka-docker#519]
The Github page stats tag 2.12-2.3.0 is available but this is not found on docker hub which shows 2.12-2.2.1 as the latest 

Can we please get 2.12-2.3.0 added to docker hub? 

thanks

**Comment by sscaling** [comment]
It looks like the build failed - https://travis-ci.org/wurstmeister/kafka-docker/jobs/551769430. Perhaps the artefact hadn't propagated to the selected mirror yet. I have re-run the build.

**Comment by bobbyio** [comment]
looks like that did the trick. I can see the tag 2.12-2.3.0 in Docker hub now

thanks
