### ISSUE TITLE
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

### ISSUE THREAD

**Issue by nijatmursali** [wurstmeister/kafka-docker#522]
Hello, 

I'm trying to create a cluster using this repository, but I'm getting the following error by typing 
`$ docker-compose up -d`

> ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?
> 
> If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
> 

In the docker-compose.yml file I have done changes and final version is like this:
```
environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
```

I have searched on google, tried several commands, but none works. I would appreciate your help.

Commands I have tried:
1. `$ sudo docker-compose up -d`

2. `$ service docker restart`

3.  `$ sudo apt-get remove docker docker-engine`
     `$ curl -sSL https://get.docker.com/ | sh`
    ` $ sudo usermod -aG docker user `

4.  `$ sudo service docker start && docker-compose up -d`

**Comment by sscaling** [comment]
Looks like docker / docker-compose isn't working - nothing to do with this image. Maybe start with a simpler example until you get docker running, i.e.

```
version: '3'

services:
  test:
    image: busybox
    command:
      - ls
```

Then iterate on `docker-compose run test` until it displays something like 

```
bin   dev   etc   home  proc  root  sys   tmp   usr   var
```

For issues configuring docker, try asking for help on the [Docker forums](https://forums.docker.com/)
