### ISSUE TITLE
Deleting topic for each run

### ISSUE THREAD

**Issue by prakashnm** [wurstmeister/kafka-docker#524]
Hi,
I am newbie to docker. I would like to know if there is any better way to delete the kafka topic before I re-run the `docker-compose up`. 
Currently I am deleting the topic from zookeeper and kafka manually by getting into the container using `start-kafka-shell.sh`. If I don't delete the topic and try to launch `$KAFKA_HOME/bin/kafka-console-consumer.sh`, I get the below warnings.
<pre>
[2019-08-06 20:28:18,771] WARN [Consumer clientId=consumer-1, groupId=console-consumer-89857] 1 partitions have leader brokers without a matching listener, including [EligibleEvent-0] (org.apache.kafka.clients.NetworkClient)
</pre>

My docker-compose.yml file

<pre>
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    volumes:
      - /tmp/docker/zk1/logs:/logs
      - /tmp/docker/zk1/data:/data
  kafka:
    image: wurstmeister/kafka
    #command: [start-kafka.sh]
    depends_on:
      - zookeeper
    #build: .
    ports:
      - "9092:9092"
    environment:
      #KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.130.98.110:9092 # ifconfig inet ip
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CREATE_TOPICS: "test:1:1,EligibleEvent:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_MESSAGE_MAX_BYTES: 10000000
      KAFKA_QUEUED_MAX_REQUEST: 20
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: PLAINTEXT
      KAFKA_LOG_DIRS: /home/y/var/kafka-logs
      KAFKA_LOG_CLEANER_ENABLE: 'false' 
      KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 20000
      KAFKA_LOG_FLUSH_INTERVAL_MS: 10000
      KAFKA_LOG_FLUSH_SCHEDULER_INTERVAL_MS: 2000
      KAFKA_LOG_MESSAGE_FORMAT_VERSION: 0.8.2
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
      KAFKA_LOG_RETENTION_MINUTES: 60
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/docker/kafka/logs:/logs
      - /tmp/docker/kafka/data:/data
      - /tmp/docker/kafka/kafka-logs:/kafka
</pre>

Also I would like to know if there is a way to map server.log from kafka to my local file system. I used `volumes` in docker-compose but it doesn't seem to be logging.

**Comment by sscaling** [comment]
> if there is any better way to delete the kafka topic before I re-run the docker-compose up.

`docker-compose down -v` will bring down kafka and zookeeper and all associated state. However, if you have mapped state to the host machine, you will also need to remove that before running `docker-compose up` again.

> Also I would like to know if there is a way to map server.log from kafka to my local file system

You'll need to use a bind mount and map the `host:container` path. By default I believe logs are in `/opt/kafka/logs`, so something like

```
volumes:
  - /path/on/host:/opt/kafka/logs:rw
```

If you're unfamiliar with Docker the official website has lots of documentation and getting started guides etc - https://docs.docker.com

**Comment by sscaling** [comment]
No response from OP, so closing due to staleness
