### ISSUE TITLE
Kafka Docker instance with PLAINTEXT, SSL and SASL

### ISSUE THREAD

**Issue by anuraagshah** [wurstmeister/kafka-docker#525]
Is there a way to configure one broker with multiple security protocols ? 
      KAFKA_LISTENERS: PLAINTEXT://:9092,SSL://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.19.17.64:9092,SSL://172.19.17.64:9093

I am trying to spin up a single node cluster with this docker image but I am not getting too far. I am seeing this in the startup logs which suggests both protocols up and running.
```
kafka_1      | [2019-08-13 20:48:36,689] INFO Registered broker 1 at path /brokers/ids/1 with addresses: ArrayBuffer(EndPoint(172.19.17.64,9092,ListenerName(PLAINTEXT),PLAINTEXT), EndPoint(172.19.17.64,9093,ListenerName(SSL),SSL)), czxid (broker epoch): 418 (kafka.zk.KafkaZkClient)
```

I am able to create/delete/list topics within the container but no luck using the producer/consumer, keep getting this error

```
bash-4.4# bin/kafka-console-producer.sh --broker-list 172.19.17.64:9092 --topic anuraag
>test
[2019-08-13 20:50:33,941] WARN [Producer clientId=console-producer] 1 partitions have leader brokers without a matching listener, including [anuraag-0] (org.apache.kafka.clients.NetworkClient)
>[2019-08-13 20:50:34,040] WARN [Producer clientId=console-producer] 1 partitions have leader brokers without a matching listener, including [anuraag-0] (org.apache.kafka.clients.NetworkClient)
[2019-08-13 20:50:34,143] WARN [Producer clientId=console-producer] 1 partitions have leader brokers without a matching listener, including [anuraag-0] (org.apache.kafka.clients.NetworkClient)
```

Here is my yaml file 
![image](https://user-images.githubusercontent.com/7451919/62976454-391d7080-bde2-11e9-9a84-01151da5be7c.png)

**Comment by sscaling** [comment]
>  I am seeing this in the startup logs which suggests both protocols up and running.

I would read this as meta data is stored in a znode - not sure it directly correlates to availability (you'd need to check the source code)

> I am able to create/delete/list topics within the container

You haven't provided information on how you have done this or defined how you have confirmed the commands were successful. For example, depending how you run the commands you may use zookeeper directly, which would negate any broker interaction (https://github.com/apache/kafka/blob/211745d0b3346b69451932358f45987dc790858f/core/src/main/scala/kafka/admin/TopicCommand.scala#L53-L56)

---

1. Have you confirmed your certs are up and being served correctly?
2. have you validated this against a native Kafka install - i.e. do you have reason to believe this is an issue with the image?
3. Are the cert paths correct - seems odd that you mount `./certs:/certs` but reference `certs/...` as the path

**Comment by anuraagshah** [comment]
Yes - I think  create/delete/list topics within the container was with the ZK directly. 
1&2. I have verified the certs work correctly with native kafka install.  
3. Yeah seems strange let me check up on that.

Do you have a single node docker.yml with SSL working as an example ?

**Comment by sscaling** [comment]
> 1&2. I have verified the certs work correctly with native kafka install.
They are two distinct things

(1) is checking that the docker instance is serving what you think are the correct certs (2) is checking that the certs work and are correct outside of the docker configuration. 

Assuming at this point that (1) you are not serving the correct certs because of (3) then if you've done (2) at least that means you have valid certs to serve when you fix your config.

**Comment by anuraagshah** [comment]
Resolved the issues with more investigation and updating the yaml file, thanks for the help

**Comment by aggrwalhimanshu** [comment]
@anuraagshah  do you mind sharing your updated yaml file

**Comment by fcarrero** [comment]
hey @anuraagshah could you please share us more information about how did you fix it ?
