### ISSUE TITLE
--zookeeper is not an option for kafka-console-consumer.sh

### ISSUE THREAD

**Issue by john408** [wurstmeister/kafka-docker#530]
The tutorial at http://wurstmeister.github.io/kafka-docker/ says
```
$ $KAFKA_HOME/bin/kafka-console-consumer.sh --topic=topic --zookeeper=$ZK
```

However, this doesn't seem to be recognized. Shouldn't it be `--bootstrap-servers` instead?

Kafka version is kafka_2.12-2.3.0 (taken from /opt)

**Comment by sscaling** [comment]
duplicates https://github.com/wurstmeister/kafka-docker/issues/407
