### ISSUE TITLE
--zookeeper option not found for kafka-console-consumer.sh

### ISSUE THREAD

**Issue by john408** [wurstmeister/kafka-docker#531]
In this tutorial (http://wurstmeister.github.io/kafka-docker/), the command is:

```
$ $KAFKA_HOME/bin/kafka-console-consumer.sh --topic=topic --zookeeper=$ZK
```

but `--zookeeper` is not a valid option. Shouldn't this be `--bootstrap-server` instead?

Kafka version is kafka_2.12-2.3.0.

**Comment by sscaling** [comment]
Duplicate of #530
