### ISSUE TITLE
Kafka version mismatch on DockerHub DockerFile

### ISSUE THREAD

**Issue by Code88Hary** [wurstmeister/kafka-docker#535]
Hi Team,
On the docker hub home page for WM Kafka - the version is 2.2.0 but if we check the docker file, the version is 1.1.0 , so could someone explain why is it so. How do we find the actual Kafka version from the container image. We believe the Docker file version is still pointing to older version of Kafka, this needs to be updated. Any suggestions would be appreciated. 
Thanks

**Comment by wurstmeister** [comment]
Hi 
please check
https://github.com/wurstmeister/kafka-docker/blob/master/Dockerfile#L3
https://github.com/wurstmeister/kafka-docker/blob/master/.travis.yml#L14

**Comment by sscaling** [comment]
Also, tracked in https://github.com/wurstmeister/kafka-docker/issues/373
