### ISSUE TITLE
bug cannot overwrite log.segment.bytes value 

### ISSUE THREAD

**Issue by FridMehdi** [wurstmeister/kafka-docker#545]
hello Folks; 

I create new topic with segment.bytes set to 50MB which mean this value should overwrite the log.segment.bytes value in  server properties  find here ty topic description: 
but like see the segment is higher than > 50000000 and no new segments created, also no compact in log.cleaner could find someone explain this behavior thanks is advance if it's a bug 

```
Topic:testKafkachangelog	PartitionCount:3	ReplicationFactor:3	Configs:segment.bytes=50000000,retention.ms=600000,cleanup.policy=compact
	Topic: testKafkachangelog	Partition: 0	Leader: 0	Replicas: 0,2,1	Isr: 0,2,1
	Topic: testKafkachangelog	Partition: 1	Leader: 1	Replicas: 1,0,2	Isr: 1,0,2
	Topic: testKafkachangelog	Partition: 2	Leader: 2	Replicas: 2,1,0	Isr: 2,1,0

testKafkachangelog-0]$ ll
total 139640
-rw-r--r-- 1 kafka kafka  10485760 Nov 12 13:57 00000000000000000000.index
-rw-r--r-- 1 kafka kafka 142907881 Nov 12 13:57 00000000000000000000.log
-rw-r--r-- 1 kafka kafka  10485756 Nov 12 13:57 00000000000000000000.timeindex
-rw-r--r-- 1 kafka kafka         8 Nov 12 13:16 leader-epoch-checkpoint
```
```
-rw-r--r-- 1 kafka kafka 142907881 Nov 12 13:57 00000000000000000000.log
```

**Comment by sscaling** [comment]
To provide any further help you would at least need to provide your docker compose file and versions being used. If you look in the server.properties file that should show you the configuration set (also this is out put in the container log)
