### ISSUE TITLE
Java producer/consumer example connecting to kafka-docker?

### ISSUE THREAD

**Issue by mcandre** [wurstmeister/kafka-docker#55]
I can connect to kafka-docker just fine in Python with the kafka-python library! However, the official Java library doesn't seem to work without a lot of manual configuration. Would you mind posting an example of Java producers/consumers that successfully connect to kafka-docker?

Here's my progress so far:

https://github.com/mcandre/hello-kafka

**Comment by ibizaman** [comment]
What is not working, exactly?

**Comment by mcandre** [comment]
Turned out that the Apache Kafka Java lib doesn't use compatible defaults.

**Comment by ibizaman** [comment]
Glad you sorted it out!
