### ISSUE TITLE
loosing unprocessed messages after kafka server restarts (wurstmeister/kafka:2.12-2.1.0)

### ISSUE THREAD

**Issue by rafi5237** [wurstmeister/kafka-docker#551]
I made all the brokers are up only consumer is down, and now I posted messages.since my brokers are up producer is able to produce the message to the Kafka brokers.but all these messages are not consumed by consumer coz it's in down. Now message which I posted should be in Kafka broker. Later I stopped Kaka brokers ,and then after some time restarted both Kafka brokers and consumer, ideally consumer has to consume message which I posted earlier. But it was not happening

**Comment by sscaling** [comment]
Have you configured persistence. If you are looking for help I'd recommend posting the docker-compose file, along with any commands to reproduce the issue. Without this it is nearly impossible to provide any help

**Comment by sscaling** [comment]
No response from OP so closing due to staleness.
