### ISSUE TITLE
Kafka listener issue

### ISSUE THREAD

**Issue by sourjya123** [wurstmeister/kafka-docker#557]
Hi,
I am running one jar file in Linux, which has Kafka listeners spring boot annotation. While I am running that jar no data is coming to the topic until I press any key from keyboard. After pressing any key all the data is coming which are already there in that topic. 
Can anyone please let me know what is the root cause?

**Comment by sscaling** [comment]
The information you have provided isn't sufficient to offer any advice / guidance. Please provide config files / links to source files / commands run / docker versions / os versions etc and anything else of use that may be used to reproduce the problem. 

However, as this appears to be an issue in the client this seems outside the scope of this repo (which packages the Kafka binary as a Docker image). You will find a much larger base of support on the kafka mailing list - https://kafka.apache.org/contact

**Comment by sourjya123** [comment]
Sure I will be providing all the documents.

**Comment by sourjya123** [comment]
Kafka is installed in CentOs machine. Kafka version is 2.4.0.
I have written sample java code which consumes data from topic. I am using 

@KafkaListener(topics = "Device")
public void receive(final String record) {
System.out.println(record);
}
This annotation is mapped with one function(recieve) and data which is present on topic Device will be mapped to functional argument(record).

I have executed on my local machine and data is coming to variable record. Now I have created the jar file and ran it on centos machine. Where the kafka itself is running. While I am pushing data to kafka, my jar file is not getting the data until and unless I am pressing any key from keyboard. Please let me know any information is required from my side.

**Comment by cricket007** [comment]
There still is not enough information. Is your problem with Spring-Kafka, or this container?

For example, it's not clear what your Kafka Consumer settings are nor what listeners you've set on the broker side. 

Note: It is preferred not to run your code on the same machines as the Kafka brokers in a production environment.

**Comment by sscaling** [comment]
Closing due to staleness. no response from OP
