### ISSUE TITLE
Can't connect to Docker using a public ip address

### ISSUE THREAD

**Issue by rodmandi** [wurstmeister/kafka-docker#562]
I'm trying to deploy the following code to Google Cloud Platform, according to some comments from the web the following code could work.

version: '3.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://public-address-of-my-server:9094
      KAFKA_LISTENERS: INSIDE://kafka:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "Topic1:1:3,Topic2:1:1:compact"
      KAFKA_LOG_DIRS: /var/logs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

**But once I tried to send a message from my local machine I got the following error:**

`WARNING:kafka.producer.record_accumulator:Produced messages to topic-partition TopicPartition(topic='Topic1', partition=0) with base offset -1 and error KafkaTimeoutError: Batch for TopicPartition(topic='Topic1', partition=0) containing 1 record(s) expired: 10 seconds have passed since batch creation plus linger time.
`

**Do you have any idea?**

**Comment by cricket007** [comment]
Not sure why this would be an issue on the container; seems networking related, and only you'll be able to debug that one. 

Please clarify "public IP address". If you mean you WAN address, you need to forward a port on your router. If you mean you LAN address, then the configurations seem fine to me. Make sure the external machine can `nc -vz <public IP>:9094`

**Comment by sscaling** [comment]
Closing due to staleness, no response from OP

**Comment by saikatsarker** [comment]
Change properties

KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
KAFKA_ADVERTISED_LISTENERS 
KAFKA_LISTENERS

as mentioned below to create a 3 tire port redirection.

`KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT, INSIDE_HOST:PLAINTEXT,OUTSIDE:PLAINTEXT
KAFKA_ADVERTISED_LISTENERS: INSIDE_CONTAINER://kafka:9092,INSIDE_HOST:localhost://9093,OUTSIDE://public-address-of-my-server:9094
KAFKA_LISTENERS: INSIDE://0.0.0.0:9092, INSIDE_HOST:0.0.0.0://9093,OUTSIDE://0.0.0.0:9094
`
