### ISSUE TITLE
kafka can not connect to zookeeper

### ISSUE THREAD

**Issue by xinghen110** [wurstmeister/kafka-docker#563]
I have run default docker-compose script well, but when i change the port of zookeeper like this, the zookeeper is not lisen the configurated port , and kafka can not connect to zookeeper.
docker-compose.yml:
version: '3'

services:
    zoo1:
        image: zookeeper
        restart: always
        privileged: true
        container_name: zoo1
        ports:
            - "7905:2181"
        volumes:
            - "/root/docker/kafka/data/zookeeper/zookeeper1/data:/data"
            - "/root/docker/kafka/data/zookeeper/zookeeper1/datalog:/datalog"
        environment:
            ZOO_MY_ID: 1
    broker1:
        image: wurstmeister/kafka
        restart: always
        container_name: broker1
        ports:
          - "7906:9092"
        depends_on:
          - zoo1
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ADVERTISED_HOST_NAME: broker1
          KAFKA_ADVERTISED_PORT: 7905
          KAFKA_HOST_NAME: broker1
          KAFKA_ZOOKEEPER_CONNECT: zoo1:7905
          KAFKA_LISTENERS: PLAINTEXT://broker1:7906
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:7906
        volumes:
          - "/root/docker/kafka/var/run/docker.sock:/var/run/docker.sock"
          - "/root/docker/kafka/data/kafka/broker1:/kafka"
 
-----------------------------------------------------------------------------------------------------
log is:
[root@iZ8vbet8a94r2nx8k3thinZ kafka]# docker-compose -f kafka.yml up
Creating network "kafka_default" with the default driver
Creating zoo1 ... done
Creating broker1 ... done
Attaching to zoo1, broker1
broker1    | [Configuring] 'advertised.port' in '/opt/kafka/config/server.properties'
broker1    | Excluding KAFKA_HOME from broker config
zoo1       | ZooKeeper JMX enabled by default
zoo1       | Using config: /conf/zoo.cfg
zoo1       | 2020-01-20 17:47:14,478 [myid:] - INFO  [main:QuorumPeerConfig@133] - Reading configuration from: /conf/zoo.cfg
zoo1       | 2020-01-20 17:47:14,482 [myid:] - INFO  [main:QuorumPeerConfig@375] - clientPort is not set
zoo1       | 2020-01-20 17:47:14,483 [myid:] - INFO  [main:QuorumPeerConfig@389] - secureClientPort is not set
zoo1       | 2020-01-20 17:47:14,487 [myid:] - ERROR [main:QuorumPeerConfig@645] - Invalid configuration, only one server specified (ignoring)
zoo1       | 2020-01-20 17:47:14,492 [myid:1] - INFO  [main:DatadirCleanupManager@78] - autopurge.snapRetainCount set to 3
zoo1       | 2020-01-20 17:47:14,492 [myid:1] - INFO  [main:DatadirCleanupManager@79] - autopurge.purgeInterval set to 0
zoo1       | 2020-01-20 17:47:14,492 [myid:1] - INFO  [main:DatadirCleanupManager@101] - Purge task is not scheduled.
zoo1       | 2020-01-20 17:47:14,492 [myid:1] - WARN  [main:QuorumPeerMain@125] - Either no config or no quorum defined in config, running  in standalone mode
zoo1       | 2020-01-20 17:47:14,493 [myid:1] - INFO  [main:ManagedUtil@46] - Log4j found with jmx enabled.
zoo1       | 2020-01-20 17:47:14,504 [myid:1] - INFO  [main:QuorumPeerConfig@133] - Reading configuration from: /conf/zoo.cfg
zoo1       | 2020-01-20 17:47:14,504 [myid:1] - INFO  [main:QuorumPeerConfig@375] - clientPort is not set
zoo1       | 2020-01-20 17:47:14,504 [myid:1] - INFO  [main:QuorumPeerConfig@389] - secureClientPort is not set
zoo1       | 2020-01-20 17:47:14,504 [myid:1] - ERROR [main:QuorumPeerConfig@645] - Invalid configuration, only one server specified (ignoring)
zoo1       | 2020-01-20 17:47:14,505 [myid:1] - INFO  [main:ZooKeeperServerMain@117] - Starting server
zoo1       | 2020-01-20 17:47:14,507 [myid:1] - INFO  [main:FileTxnSnapLog@103] - zookeeper.snapshot.trust.empty : false
zoo1       | 2020-01-20 17:47:14,518 [myid:1] - INFO  [main:Environment@109] - Server environment:zookeeper.version=3.5.6-c11b7e26bc554b8523dc929761dd28808913f091, built on 10/08/2019 20:18 GMT
zoo1       | 2020-01-20 17:47:14,519 [myid:1] - INFO  [main:Environment@109] - Server environment:host.name=d1bc34396baa
zoo1       | 2020-01-20 17:47:14,519 [myid:1] - INFO  [main:Environment@109] - Server environment:java.version=1.8.0_232
zoo1       | 2020-01-20 17:47:14,519 [myid:1] - INFO  [main:Environment@109] - Server environment:java.vendor=Oracle Corporation
zoo1       | 2020-01-20 17:47:14,519 [myid:1] - INFO  [main:Environment@109] - Server environment:java.home=/usr/local/openjdk-8
zoo1       | 2020-01-20 17:47:14,519 [myid:1] - INFO  [main:Environment@109] - Server environment:java.class.path=/apache-zookeeper-3.5.6-bin/bin/../zookeeper-server/target/classes:/apache-zookeeper-3.5.6-bin/bin/../build/classes:/apache-zookeeper-3.5.6-bin/bin/../zookeeper-server/target/lib/*.jar:/apache-zookeeper-3.5.6-bin/bin/../build/lib/*.jar:/apache-zookeeper-3.5.6-bin/bin/../lib/zookeeper-jute-3.5.6.jar:/apache-zookeeper-3.5.6-bin/bin/../lib/zookeeper-3.5.6.jar:/apache-zookeeper-3.5.6-bin/bin/../lib/slf4j-log4j12-1.7.25.jar:/apache-zookeeper-3.5.6-bin/bin/../lib/slf4j-api-1.7.25.jar:/apache-zookeeper-3.5.6-bin/bin/../lib/netty-transport-native-unix-common-4.1.42.Final.jar:/apache-zookeeper-3.5.6-bin/bin/../lib/netty-transport-native-epoll-4.1.42.Final.jar:/apache-zookeeper-3.5.6-bin/bin/../lib/netty-transport-4.1.42.Final.jar:/apache-zookeeper-3.5.6-bin/bin/../lib/netty-resolver-4.1.42.Final.jar:/apache-zookeeper-3.5.6-bin/bin/../lib/netty-handler-4.1.42.Final.jar:/apache-zookeeper-3.5.6-bin/bin/../lib/netty-common-4.1.42.Final.jar:/apache-zookeeper-3.5.6-bin/bin/../lib/netty-codec-4.1.42.Final.jar:/apache-zookeeper-3.5.6-bin/bin/../lib/netty-buffer-4.1.42.Final.jar:/apache-zookeeper-3.5.6-bin/bin/../lib/log4j-1.2.17.jar:/apache-zookeeper-3.5.6-bin/bin/../lib/json-simple-1.1.1.jar:/apache-zookeeper-3.5.6-bin/bin/../lib/jline-2.11.jar:/apache-zookeeper-3.5.6-bin/bin/../lib/jetty-util-9.4.17.v20190418.jar:/apache-zookeeper-3.5.6-bin/bin/../lib/jetty-servlet-9.4.17.v20190418.jar:/apache-zookeeper-3.5.6-bin/bin/../lib/jetty-server-9.4.17.v20190418.jar:/apache-zookeeper-3.5.6-bin/bin/../lib/jetty-security-9.4.17.v20190418.jar:/apache-zookeeper-3.5.6-bin/bin/../lib/jetty-io-9.4.17.v20190418.jar:/apache-zookeeper-3.5.6-bin/bin/../lib/jetty-http-9.4.17.v20190418.jar:/apache-zookeeper-3.5.6-bin/bin/../lib/javax.servlet-api-3.1.0.jar:/apache-zookeeper-3.5.6-bin/bin/../lib/jackson-databind-2.9.10.jar:/apache-zookeeper-3.5.6-bin/bin/../lib/jackson-core-2.9.10.jar:/apache-zookeeper-3.5.6-bin/bin/../lib/jackson-annotations-2.9.10.jar:/apache-zookeeper-3.5.6-bin/bin/../lib/commons-cli-1.2.jar:/apache-zookeeper-3.5.6-bin/bin/../lib/audience-annotations-0.5.0.jar:/apache-zookeeper-3.5.6-bin/bin/../zookeeper-*.jar:/apache-zookeeper-3.5.6-bin/bin/../zookeeper-server/src/main/resources/lib/*.jar:/conf:
zoo1       | 2020-01-20 17:47:14,520 [myid:1] - INFO  [main:Environment@109] - Server environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
zoo1       | 2020-01-20 17:47:14,520 [myid:1] - INFO  [main:Environment@109] - Server environment:java.io.tmpdir=/tmp
zoo1       | 2020-01-20 17:47:14,520 [myid:1] - INFO  [main:Environment@109] - Server environment:java.compiler=<NA>
zoo1       | 2020-01-20 17:47:14,520 [myid:1] - INFO  [main:Environment@109] - Server environment:os.name=Linux
zoo1       | 2020-01-20 17:47:14,520 [myid:1] - INFO  [main:Environment@109] - Server environment:os.arch=amd64
zoo1       | 2020-01-20 17:47:14,520 [myid:1] - INFO  [main:Environment@109] - Server environment:os.version=3.10.0-957.21.3.el7.x86_64
zoo1       | 2020-01-20 17:47:14,520 [myid:1] - INFO  [main:Environment@109] - Server environment:user.name=zookeeper
zoo1       | 2020-01-20 17:47:14,520 [myid:1] - INFO  [main:Environment@109] - Server environment:user.home=/home/zookeeper
zoo1       | 2020-01-20 17:47:14,520 [myid:1] - INFO  [main:Environment@109] - Server environment:user.dir=/apache-zookeeper-3.5.6-bin
zoo1       | 2020-01-20 17:47:14,520 [myid:1] - INFO  [main:Environment@109] - Server environment:os.memory.free=466MB
zoo1       | 2020-01-20 17:47:14,521 [myid:1] - INFO  [main:Environment@109] - Server environment:os.memory.max=889MB
zoo1       | 2020-01-20 17:47:14,521 [myid:1] - INFO  [main:Environment@109] - Server environment:os.memory.total=481MB
zoo1       | 2020-01-20 17:47:14,523 [myid:1] - INFO  [main:ZooKeeperServer@938] - minSessionTimeout set to 4000
zoo1       | 2020-01-20 17:47:14,523 [myid:1] - INFO  [main:ZooKeeperServer@947] - maxSessionTimeout set to 40000
zoo1       | 2020-01-20 17:47:14,523 [myid:1] - INFO  [main:ZooKeeperServer@166] - Created server with tickTime 2000 minSessionTimeout 4000 maxSessionTimeout 40000 datadir /datalog/version-2 snapdir /data/version-2
zoo1       | 2020-01-20 17:47:14,549 [myid:1] - INFO  [main:Log@193] - Logging initialized @408ms to org.eclipse.jetty.util.log.Slf4jLog
broker1    | [Configuring] 'advertised.host.name' in '/opt/kafka/config/server.properties'
broker1    | [Configuring] 'port' in '/opt/kafka/config/server.properties'
broker1    | [Configuring] 'advertised.listeners' in '/opt/kafka/config/server.properties'
zoo1       | 2020-01-20 17:47:14,657 [myid:1] - WARN  [main:ContextHandler@1588] - o.e.j.s.ServletContextHandler@2d928643{/,null,UNAVAILABLE} contextPath ends with /*
zoo1       | 2020-01-20 17:47:14,658 [myid:1] - WARN  [main:ContextHandler@1599] - Empty contextPath
broker1    | [Configuring] 'host.name' in '/opt/kafka/config/server.properties'
zoo1       | 2020-01-20 17:47:14,670 [myid:1] - INFO  [main:Server@370] - jetty-9.4.17.v20190418; built: 2019-04-18T19:45:35.259Z; git: aa1c656c315c011c01e7b21aabb04066635b9f67; jvm 1.8.0_232-b09
broker1    | [Configuring] 'broker.id' in '/opt/kafka/config/server.properties'
broker1    | Excluding KAFKA_VERSION from broker config
broker1    | [Configuring] 'listeners' in '/opt/kafka/config/server.properties'
broker1    | [Configuring] 'zookeeper.connect' in '/opt/kafka/config/server.properties'
zoo1       | 2020-01-20 17:47:14,712 [myid:1] - INFO  [main:DefaultSessionIdManager@365] - DefaultSessionIdManager workerName=node0
zoo1       | 2020-01-20 17:47:14,713 [myid:1] - INFO  [main:DefaultSessionIdManager@370] - No SessionScavenger set, using defaults
zoo1       | 2020-01-20 17:47:14,714 [myid:1] - INFO  [main:HouseKeeper@149] - node0 Scavenging every 600000ms
broker1    | [Configuring] 'log.dirs' in '/opt/kafka/config/server.properties'
zoo1       | 2020-01-20 17:47:14,725 [myid:1] - INFO  [main:ContextHandler@855] - Started o.e.j.s.ServletContextHandler@2d928643{/,null,AVAILABLE}
zoo1       | 2020-01-20 17:47:14,737 [myid:1] - INFO  [main:AbstractConnector@292] - Started ServerConnector@7dc7cbad{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
zoo1       | 2020-01-20 17:47:14,738 [myid:1] - INFO  [main:Server@410] - Started @605ms
zoo1       | 2020-01-20 17:47:14,738 [myid:1] - INFO  [main:JettyAdminServer@112] - Started AdminServer on address 0.0.0.0, port 8080 and command URL /commands
zoo1       | 2020-01-20 17:47:14,742 [myid:1] - INFO  [main:ServerCnxnFactory@135] - Using org.apache.zookeeper.server.NIOServerCnxnFactory as server connection factory
zoo1       | 2020-01-20 17:47:14,744 [myid:1] - INFO  [main:NIOServerCnxnFactory@673] - Configuring NIO connection handler with 10s sessionless connection timeout, 1 selector thread(s), 8 worker threads, and 64 kB direct buffers.
zoo1       | 2020-01-20 17:47:14,745 [myid:1] - INFO  [main:NIOServerCnxnFactory@686] - binding to port /0.0.0.0:2181
zoo1       | 2020-01-20 17:47:14,759 [myid:1] - INFO  [main:ZKDatabase@117] - zookeeper.snapshotSizeFactor = 0.33
zoo1       | 2020-01-20 17:47:14,760 [myid:1] - INFO  [main:FileSnap@83] - Reading snapshot /data/version-2/snapshot.32
zoo1       | 2020-01-20 17:47:14,775 [myid:1] - INFO  [main:FileTxnSnapLog@384] - Snapshotting: 0x47 to /data/version-2/snapshot.47
zoo1       | 2020-01-20 17:47:14,791 [myid:1] - INFO  [main:ContainerManager@64] - Using checkIntervalMs=60000 maxPerMinute=10000
zoo1       | 2020-01-20 17:47:15,019 [myid:1] - INFO  [NIOWorkerThread-2:ZooKeeperServer@762] - Invalid session 0x1001fc746640001 for client /106.119.69.73:13245, probably expired
zoo1       | 2020-01-20 17:47:15,019 [myid:1] - INFO  [NIOWorkerThread-1:ZooKeeperServer@762] - Invalid session 0x1001fc746640000 for client /106.119.69.73:13246, probably expired
zoo1       | 2020-01-20 17:47:15,060 [myid:1] - INFO  [SyncThread:0:FileTxnLog@216] - Creating new log file: log.48
broker1    | [2020-01-20 17:47:15,525] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
broker1    | [2020-01-20 17:47:16,199] INFO Registered signal handlers for TERM, INT, HUP (org.apache.kafka.common.utils.LoggingSignalHandler)
broker1    | [2020-01-20 17:47:16,200] INFO starting (kafka.server.KafkaServer)
broker1    | [2020-01-20 17:47:16,201] INFO Connecting to zookeeper on zoo1:7905 (kafka.server.KafkaServer)
broker1    | [2020-01-20 17:47:16,223] INFO [ZooKeeperClient Kafka server] Initializing a new session to zoo1:7905. (kafka.zookeeper.ZooKeeperClient)
broker1    | [2020-01-20 17:47:16,229] INFO Client environment:zookeeper.version=3.5.6-c11b7e26bc554b8523dc929761dd28808913f091, built on 10/08/2019 20:18 GMT (org.apache.zookeeper.ZooKeeper)
broker1    | [2020-01-20 17:47:16,229] INFO Client environment:host.name=b8acac8b587b (org.apache.zookeeper.ZooKeeper)
broker1    | [2020-01-20 17:47:16,229] INFO Client environment:java.version=1.8.0_212 (org.apache.zookeeper.ZooKeeper)
broker1    | [2020-01-20 17:47:16,229] INFO Client environment:java.vendor=IcedTea (org.apache.zookeeper.ZooKeeper)
broker1    | [2020-01-20 17:47:16,230] INFO Client environment:java.home=/usr/lib/jvm/java-1.8-openjdk/jre (org.apache.zookeeper.ZooKeeper)
broker1    | [2020-01-20 17:47:16,230] INFO Client environment:java.class.path=/opt/kafka/bin/../libs/activation-1.1.1.jar:/opt/kafka/bin/../libs/aopalliance-repackaged-2.5.0.jar:/opt/kafka/bin/../libs/argparse4j-0.7.0.jar:/opt/kafka/bin/../libs/audience-annotations-0.5.0.jar:/opt/kafka/bin/../libs/commons-cli-1.4.jar:/opt/kafka/bin/../libs/commons-lang3-3.8.1.jar:/opt/kafka/bin/../libs/connect-api-2.4.0.jar:/opt/kafka/bin/../libs/connect-basic-auth-extension-2.4.0.jar:/opt/kafka/bin/../libs/connect-file-2.4.0.jar:/opt/kafka/bin/../libs/connect-json-2.4.0.jar:/opt/kafka/bin/../libs/connect-mirror-2.4.0.jar:/opt/kafka/bin/../libs/connect-mirror-client-2.4.0.jar:/opt/kafka/bin/../libs/connect-runtime-2.4.0.jar:/opt/kafka/bin/../libs/connect-transforms-2.4.0.jar:/opt/kafka/bin/../libs/guava-20.0.jar:/opt/kafka/bin/../libs/hk2-api-2.5.0.jar:/opt/kafka/bin/../libs/hk2-locator-2.5.0.jar:/opt/kafka/bin/../libs/hk2-utils-2.5.0.jar:/opt/kafka/bin/../libs/jackson-annotations-2.10.0.jar:/opt/kafka/bin/../libs/jackson-core-2.10.0.jar:/opt/kafka/bin/../libs/jackson-databind-2.10.0.jar:/opt/kafka/bin/../libs/jackson-dataformat-csv-2.10.0.jar:/opt/kafka/bin/../libs/jackson-datatype-jdk8-2.10.0.jar:/opt/kafka/bin/../libs/jackson-jaxrs-base-2.10.0.jar:/opt/kafka/bin/../libs/jackson-jaxrs-json-provider-2.10.0.jar:/opt/kafka/bin/../libs/jackson-module-jaxb-annotations-2.10.0.jar:/opt/kafka/bin/../libs/jackson-module-paranamer-2.10.0.jar:/opt/kafka/bin/../libs/jackson-module-scala_2.12-2.10.0.jar:/opt/kafka/bin/../libs/jakarta.activation-api-1.2.1.jar:/opt/kafka/bin/../libs/jakarta.annotation-api-1.3.4.jar:/opt/kafka/bin/../libs/jakarta.inject-2.5.0.jar:/opt/kafka/bin/../libs/jakarta.ws.rs-api-2.1.5.jar:/opt/kafka/bin/../libs/jakarta.xml.bind-api-2.3.2.jar:/opt/kafka/bin/../libs/javassist-3.22.0-CR2.jar:/opt/kafka/bin/../libs/javax.servlet-api-3.1.0.jar:/opt/kafka/bin/../libs/javax.ws.rs-api-2.1.1.jar:/opt/kafka/bin/../libs/jaxb-api-2.3.0.jar:/opt/kafka/bin/../libs/jersey-client-2.28.jar:/opt/kafka/bin/../libs/jersey-common-2.28.jar:/opt/kafka/bin/../libs/jersey-container-servlet-2.28.jar:/opt/kafka/bin/../libs/jersey-container-servlet-core-2.28.jar:/opt/kafka/bin/../libs/jersey-hk2-2.28.jar:/opt/kafka/bin/../libs/jersey-media-jaxb-2.28.jar:/opt/kafka/bin/../libs/jersey-server-2.28.jar:/opt/kafka/bin/../libs/jetty-client-9.4.20.v20190813.jar:/opt/kafka/bin/../libs/jetty-continuation-9.4.20.v20190813.jar:/opt/kafka/bin/../libs/jetty-http-9.4.20.v20190813.jar:/opt/kafka/bin/../libs/jetty-io-9.4.20.v20190813.jar:/opt/kafka/bin/../libs/jetty-security-9.4.20.v20190813.jar:/opt/kafka/bin/../libs/jetty-server-9.4.20.v20190813.jar:/opt/kafka/bin/../libs/jetty-servlet-9.4.20.v20190813.jar:/opt/kafka/bin/../libs/jetty-servlets-9.4.20.v20190813.jar:/opt/kafka/bin/../libs/jetty-util-9.4.20.v20190813.jar:/opt/kafka/bin/../libs/jopt-simple-5.0.4.jar:/opt/kafka/bin/../libs/kafka-clients-2.4.0.jar:/opt/kafka/bin/../libs/kafka-log4j-appender-2.4.0.jar:/opt/kafka/bin/../libs/kafka-streams-2.4.0.jar:/opt/kafka/bin/../libs/kafka-streams-examples-2.4.0.jar:/opt/kafka/bin/../libs/kafka-streams-scala_2.12-2.4.0.jar:/opt/kafka/bin/../libs/kafka-streams-test-utils-2.4.0.jar:/opt/kafka/bin/../libs/kafka-tools-2.4.0.jar:/opt/kafka/bin/../libs/kafka_2.12-2.4.0-sources.jar:/opt/kafka/bin/../libs/kafka_2.12-2.4.0.jar:/opt/kafka/bin/../libs/log4j-1.2.17.jar:/opt/kafka/bin/../libs/lz4-java-1.6.0.jar:/opt/kafka/bin/../libs/maven-artifact-3.6.1.jar:/opt/kafka/bin/../libs/metrics-core-2.2.0.jar:/opt/kafka/bin/../libs/netty-buffer-4.1.42.Final.jar:/opt/kafka/bin/../libs/netty-codec-4.1.42.Final.jar:/opt/kafka/bin/../libs/netty-common-4.1.42.Final.jar:/opt/kafka/bin/../libs/netty-handler-4.1.42.Final.jar:/opt/kafka/bin/../libs/netty-resolver-4.1.42.Final.jar:/opt/kafka/bin/../libs/netty-transport-4.1.42.Final.jar:/opt/kafka/bin/../libs/netty-transport-native-epoll-4.1.42.Final.jar:/opt/kafka/bin/../libs/netty-transport-native-unix-common-4.1.42.Final.jar:/opt/kafka/bin/../libs/osgi-resource-locator-1.0.1.jar:/opt/kafka/bin/../libs/paranamer-2.8.jar:/opt/kafka/bin/../libs/plexus-utils-3.2.0.jar:/opt/kafka/bin/../libs/reflections-0.9.11.jar:/opt/kafka/bin/../libs/rocksdbjni-5.18.3.jar:/opt/kafka/bin/../libs/scala-collection-compat_2.12-2.1.2.jar:/opt/kafka/bin/../libs/scala-java8-compat_2.12-0.9.0.jar:/opt/kafka/bin/../libs/scala-library-2.12.10.jar:/opt/kafka/bin/../libs/scala-logging_2.12-3.9.2.jar:/opt/kafka/bin/../libs/scala-reflect-2.12.10.jar:/opt/kafka/bin/../libs/slf4j-api-1.7.28.jar:/opt/kafka/bin/../libs/slf4j-log4j12-1.7.28.jar:/opt/kafka/bin/../libs/snappy-java-1.1.7.3.jar:/opt/kafka/bin/../libs/validation-api-2.0.1.Final.jar:/opt/kafka/bin/../libs/zookeeper-3.5.6.jar:/opt/kafka/bin/../libs/zookeeper-jute-3.5.6.jar:/opt/kafka/bin/../libs/zstd-jni-1.4.3-1.jar (org.apache.zookeeper.ZooKeeper)
broker1    | [2020-01-20 17:47:16,230] INFO Client environment:java.library.path=/usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/server:/usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64:/usr/lib/jvm/java-1.8-openjdk/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib (org.apache.zookeeper.ZooKeeper)
broker1    | [2020-01-20 17:47:16,230] INFO Client environment:java.io.tmpdir=/tmp (org.apache.zookeeper.ZooKeeper)
broker1    | [2020-01-20 17:47:16,230] INFO Client environment:java.compiler=<NA> (org.apache.zookeeper.ZooKeeper)
broker1    | [2020-01-20 17:47:16,230] INFO Client environment:os.name=Linux (org.apache.zookeeper.ZooKeeper)
broker1    | [2020-01-20 17:47:16,230] INFO Client environment:os.arch=amd64 (org.apache.zookeeper.ZooKeeper)
broker1    | [2020-01-20 17:47:16,230] INFO Client environment:os.version=3.10.0-957.21.3.el7.x86_64 (org.apache.zookeeper.ZooKeeper)
broker1    | [2020-01-20 17:47:16,230] INFO Client environment:user.name=root (org.apache.zookeeper.ZooKeeper)
broker1    | [2020-01-20 17:47:16,231] INFO Client environment:user.home=/root (org.apache.zookeeper.ZooKeeper)
broker1    | [2020-01-20 17:47:16,231] INFO Client environment:user.dir=/ (org.apache.zookeeper.ZooKeeper)
broker1    | [2020-01-20 17:47:16,231] INFO Client environment:os.memory.free=979MB (org.apache.zookeeper.ZooKeeper)
broker1    | [2020-01-20 17:47:16,231] INFO Client environment:os.memory.max=1024MB (org.apache.zookeeper.ZooKeeper)
broker1    | [2020-01-20 17:47:16,231] INFO Client environment:os.memory.total=1024MB (org.apache.zookeeper.ZooKeeper)
broker1    | [2020-01-20 17:47:16,236] INFO Initiating client connection, connectString=zoo1:7905 sessionTimeout=6000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@3d51f06e (org.apache.zookeeper.ZooKeeper)
broker1    | [2020-01-20 17:47:16,241] INFO Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation (org.apache.zookeeper.common.X509Util)
broker1    | [2020-01-20 17:47:16,247] INFO jute.maxbuffer value is 4194304 Bytes (org.apache.zookeeper.ClientCnxnSocket)
broker1    | [2020-01-20 17:47:16,254] INFO zookeeper.request.timeout value is 0. feature enabled= (org.apache.zookeeper.ClientCnxn)
broker1    | [2020-01-20 17:47:16,257] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
broker1    | [2020-01-20 17:47:16,261] INFO Opening socket connection to server zoo1/172.31.0.2:7905. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
broker1    | [2020-01-20 17:47:16,266] INFO Socket error occurred: zoo1/172.31.0.2:7905: Connection refused (org.apache.zookeeper.ClientCnxn)
broker1    | [2020-01-20 17:47:17,368] INFO Opening socket connection to server zoo1/172.31.0.2:7905. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
broker1    | [2020-01-20 17:47:17,369] INFO Socket error occurred: zoo1/172.31.0.2:7905: Connection refused (org.apache.zookeeper.ClientCnxn)
broker1    | [2020-01-20 17:47:18,470] INFO Opening socket connection to server zoo1/172.31.0.2:7905. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
broker1    | [2020-01-20 17:47:18,470] INFO Socket error occurred: zoo1/172.31.0.2:7905: Connection refused (org.apache.zookeeper.ClientCnxn)

**Comment by cricket007** [comment]
`7905` exists only on your host, not between containers. Did you try `zoo1:2181`?

Also, kafka's host name and listeners should be localhost if you are going to be sending data to them outside of Kafka

**Comment by cricket007** [comment]
Welcome. Feel free to close the issue
