### ISSUE TITLE
[Question] How to re-start Kafka from scratch?

### ISSUE THREAD

**Issue by jeffworne** [wurstmeister/kafka-docker#568]
Hello,

How do I wipe out the current information stored in Kafka Docker and start with a fresh Kafka instance? I've tried `docker-compose down` and `docker-compose pull` to try to get fresh images to start, but my topic list still has old topics in it.

**Comment by cricket007** [comment]
`docker-compose rm -sf` will stop and remove the container.

**Comment by jeffworne** [comment]
If I do `docker-compse rm -sfv` it will remove the volume mounts and any messages that I have published. However, the topics are still re-created when I restart the container. I checked my YAML configuration file and I don't have any topics created at startup. Any ideas how this is possible?

**Comment by cricket007** [comment]
The volume mounts are not cleaned.

Do you really need volume mounts if you want a fresh broker?

**Comment by jeffworne** [comment]
It seems that _some_ of the volume mounts are cleaned, since data written to the topic is purged after i run `rm -sfv`. I wasn't aware of other mount options, but I see there is a `tmpfs` that should work. I'm still a bit stumped as to where the mystery volume is that keeps the topic name alive, but doesn't otherwise hold any data.

**Comment by cricket007** [comment]
Can you show your compose file as part of a [SSCCE](http://sscce.org/)?

**Comment by jeffworne** [comment]
So I was mid-creation of my reply when I noticed how the topic gets created. It's coming from a Kafka cluster monitoring program that seems to cache old topics and try to reload them. This seems to trigger the auto topic creation in Kafka. I should've been a bit more careful about documenting how I was doing things. I appreciate your help!
