### ISSUE TITLE
kafka-docker_kafka_1 exited with code 1

### ISSUE THREAD

**Issue by thuylevn** [wurstmeister/kafka-docker#570]
container shutdown immediately after run kafka-docker_kafka_1 exited with code 1

![image](https://user-images.githubusercontent.com/24593553/73680224-e4b8c680-4689-11ea-8494-9ee7708a19ce.png)

**Comment by cricket007** [comment]
Please show your complete compose file for a reproducible error

**Comment by sscaling** [comment]
Closing due to staleness. No response from OP
