### ISSUE TITLE
Docker volume size limit

### ISSUE THREAD

**Issue by 0807Jpatel** [wurstmeister/kafka-docker#576]
I am connecting a very small volume, with target = /kafka.  which is working fine and logs are being generated as expected. but as soon as the volume is full the docker container crashes. 

Is this expected? or it should still keep the container running.

**Comment by cricket007** [comment]
What is your host OS? If it's Linux, there's no limit. Otherwise, you're limited by the hypervisor disk space

**Comment by 0807Jpatel** [comment]
what if the volume we mount for kafka node fills up? The hardware limit.

**Comment by cricket007** [comment]
The same thing that would happen if you werent using Docker. The host locks up, and all services stop for IO wait
