### ISSUE TITLE
Can't start shell script

### ISSUE THREAD

**Issue by cpoulsen** [wurstmeister/kafka-docker#579]
Hi

I don't believe this is an actual issue, but i cant figure out how to start the shell script
Running `start-kafka-shell.sh 192.168.99.100 192.168.99.100:2181` does nothing except briefly opening a terminal window. 

If i run it in bash i get
```
C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"C:/Program Files/Git/usr/bin/bash\": stat C:/Program Files/Git/usr/bin/bash: no such file or directory": unknown.
```

**Comment by cricket007** [comment]
Can you run the command here directly? 

https://github.com/wurstmeister/kafka-docker/blob/master/start-kafka-shell.sh#L2

**Comment by YANGLLI** [comment]
I saw in tutorial you suggest use `docker-machine ip` to set KAFKA_ADVERTISED_HOST_NAME. But I'm using docker desktop where `docker-machine ip` is not available. Do you know how to get the docker host ip?

**Comment by cricket007** [comment]
Use localhost @YANGLLI 

https://rmoff.net/2018/08/02/kafka-listeners-explained/

**Comment by mgomesborges** [comment]
Hey @YANGLLI did you solve your problem?

A simple workaround to start the shell script:

1. Find out the name of the docker running Kafka:

```bash
docker-compose ps
# Name                                      Command             State
# ---------------------------------------------------
# kafka-docker_kafka_1            start-kafka.sh        Up
# kafka-docker_zookeeper_1   /bin/sh...                 Up
```

Then you can access the Kafka shell (in this example docker name: `kafka-docker_kafka_1`):

```bash
docker exec -it kafka-docker_kafka_1 /bin/bash
```

Because of the way networking is implemented in Docker Desktop for Windows/macOS, you cannot see a `docker0` interface on the host.

In this case, to communicate with Kafka you will have to do the Docker port forwarding for localhost.

In the example below, port fowarding is for `localhost:9092`:

```bash
# docker-compose.yml
version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    build: .
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

**Comment by OneCricketeer** [comment]
Reminder: Docker socket mounting exposes a security risk and should be avoided

Kafka doesn't need it

**Comment by mgomesborges** [comment]
Thanks @OneCricketeer ;)
@cpoulsen @YANGLLI 

I wrote a quick tutorial with a step-by-step instruction on how to deploy a Kafka broker with Docker containers when a Kafka producer and consumer sit on different networks.

[Tutorial Kafka Docker](https://github.com/mgomesborges/mac-kafka-docker)

I hope it is useful!

**Comment by OneCricketeer** [comment]
Personally, I prefer the bitnami kafka or Confluent containers because they actually stay up to date faster with Apache releases and have companies supporting those images. As I wrote elsewhere, it's still all the same Apache Kafka

**Comment by mgomesborges** [comment]
> Personally, I prefer the bitnami kafka or Confluent containers because they actually stay up to date faster with Apache releases and have companies supporting those images. As I wrote elsewhere, it's still all the same Apache Kafka

I fully agree with you!

I'm learning Kafka, and I also realized that [kafka-python](https://github.com/dpkp/kafka-python) is still under development, and some functions are not stable.

I believe that Bitnami or Confluent Kafka containers are more up to date, and the confluent-kafka clients are the best option, especially [confluent-kafka-python](https://github.com/confluentinc/confluent-kafka-python).

In any case, the sausage master @wurstmeister is doing an excellent job with this repo ;)

**Comment by sscaling** [comment]
closing due to staleness
