### ISSUE TITLE
Why where is no kafka official docker image?

### ISSUE THREAD

**Issue by chunzhenzyd** [wurstmeister/kafka-docker#587]
Not actually issue, but want to know.
Zookeeper has official docker image.

**Comment by kofemann** [comment]
Well, there is one

https://hub.docker.com/r/confluentinc/cp-kafka

But it's badly documented, not flexible and intended to be used as part of the other services by confluent

**Comment by OneCricketeer** [comment]
@kofemann It's documented, perfectly flexible, and definitely is not tied to Confluent products... Please provide me any reference to back up your claims

**Comment by OneCricketeer** [comment]
This issue should be closed, anyway.

You have to open an issue in the Docker official-images repo to elect a new official image

**Comment by kofemann** [comment]
@OneCricketeer 
just follow this two links 
- https://hub.docker.com/r/confluentinc/cp-kafka
- https://hub.docker.com/r/wurstmeister/kafka/

And compare what you see.

**Comment by OneCricketeer** [comment]
@kofemann what about it?

I contribute to both. As well as bitnami/kafka and debezium/kafka 

Both are open source. Both [are documented](https://github.com/confluentinc/kafka-images) [(2)](https://docs.confluent.io/current/quickstart/ce-docker-quickstart.html) [(3)](https://docs.confluent.io/current/installation/docker/index.html)

Both work with the entire Confluent Platform. 

Confluent's actually work better in Mesos/k8s/Nomad than wurstmeisters, which mostly just work in the Swarm

**Comment by kofemann** [comment]
I will give it a try (though never touch the running system). One confusing thing is that cp-kafka versions doesn't match kafka versions.

**Comment by OneCricketeer** [comment]
> One confusing thing is that cp-kafka versions doesn't match kafka versions

Do they need to? 

https://docs.confluent.io/current/installation/versions-interoperability.html
