### ISSUE TITLE
Release Kafka 2.5

### ISSUE THREAD

**Issue by ryanhall07** [wurstmeister/kafka-docker#588]
Kafka 2.5 was released on 4/15/20. https://kafka.apache.org/downloads#2.5.0

Additionally it would be nice to release a new version of https://github.com/wurstmeister/zookeeper-docker to at least 3.5.7 since Kafka 2.5 now supports TLS connections to ZK https://www.confluent.io/blog/apache-kafka-2-5-latest-version-updates/#kip-515

**Comment by ryanhall07** [comment]
an attempt https://github.com/wurstmeister/kafka-docker/pull/589

**Comment by ryanhall07** [comment]
tests are now green in https://github.com/wurstmeister/kafka-docker/pull/589 and it's ready for review/merge

**Comment by flyaruu** [comment]
+1!
