### ISSUE TITLE
Waiting for kafka to be ready.

### ISSUE THREAD

**Issue by sivaswami** [wurstmeister/kafka-docker#591]
Hi,

Can you help me here. I am getting the error message "waiting for kafka to be ready"
Below is my environment details:

 (master *)• • • docker-compose logs kafka
Attaching to kafka-docker_kafka_1
kafka_1      | waiting for kafka to be ready
kafka_1      | waiting for kafka to be ready
kafka_1      | waiting for kafka to be ready

• • • cat docker-compose-single-broker.yml 
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

**Comment by OneCricketeer** [comment]
Works for me.

Note: you shouldn't mount the Docker socket

**Comment by sscaling** [comment]
Have you already ran the brokers and then restarted (leaving some stale state around)? If so, try running `docker-compose rm -v` first to destroy existing containers before starting a new set of containers.
