### ISSUE TITLE
Archived kafka releases

### ISSUE THREAD

**Issue by nikoloutsa** [wurstmeister/kafka-docker#592]
https://github.com/wurstmeister/kafka-docker/blob/cb719bf8478500e287e7411e65fefe5e5421489c/download-kafka.sh#L8

it seems that the download url [https://downloads.apache.org/kafka](https://downloads.apache.org/kafka ) has only the current releases >2.2
archived versions have moved to [https://archive.apache.org/dist/](https://archive.apache.org/dist/)

**Comment by OneCricketeer** [comment]
Why do you need to rebuild the container?

**Comment by sscaling** [comment]
If you look at the following line, you will see that we should fallback to the archive url when the mirror fails to return a result. I'll close the issue as there was no response to the previous question.
