### ISSUE TITLE
Connect to Kafka from External host

### ISSUE THREAD

**Issue by crashinc99** [wurstmeister/kafka-docker#595]
I'm simply trying to connect from an external host to kafka hosted in docker.  I've tried a ton of configs with no luck.  The latest config is consistent with this page: https://rmoff.net/2018/08/02/kafka-listeners-explained/

When I try to connect to the kafka instance from my java client it get:
org.apache.kafka.common.errors.TimeoutException: "Timed out waiting for a node assignment."

Versions and Configs:

Mac OS X 10.14.6
Docker Desktop : 2.2.0.5 (43884)
Docker Compose: 1.25.4

docker-compose.yml
_version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    ports:
      - "9092:9092"
      - "29094:29094"
    environment:
      KAFKA_LISTENERS: BOB://kafka:29092, FRED://kafka:9092, ALICE://kafka:29094
      KAFKA_ADVERTISED_LISTENERS: BOB://kafka:9092,FRED://localhost:29092,ALICE://192.168.x.x:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BOB:PLAINTEXT, FRED:PLAINTEXT, ALICE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: BOB
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock_

netstat -ap tcp | grep -i "listen" shows:
_tcp46      0      0  *.29094                *.*                    LISTEN_     

I thought I'd see localhost.9092 as well but that's not there.

docker ps returns:

_CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                                                NAMES
1597087912e4        wurstmeister/kafka:2.11-2.0.0   "start-kafka.sh"         14 minutes ago      Up 14 minutes       0.0.0.0:9092->9092/tcp, 0.0.0.0:29094->29094/tcp     test_kafka_1
1797af83f6bd        wurstmeister/zookeeper          "/bin/sh -c '/usr/sb…"   19 hours ago        Up 14 minutes       22/tcp, 2888/tcp, 3888/tcp, 0.0.0.0:2181->2181/tcp   test_zookeeper_1_

Telnet from docker host (local host):

_telnet localhost 9092
Trying ::1...
Connected to localhost.
Escape character is '^]'._

From remote host:

_telnet 192.168.x.x 29094
Trying ::1...
Connected to ...myhostname... .
Escape character is '^]'._

Any help would be appreciated.

**Comment by OneCricketeer** [comment]
You've made the mistake of binding the listener only to the hostname of the container. 

It must be published on all addresses 

`KAFKA_LISTENERS: BOB://0.0.0.0:29092, FRED://0.0.0.0:9092, ALICE://0.0.0.0:29094`

**Comment by crashinc99** [comment]
The blog doesn't list the KAFKA_LISTENERS like you suggested.  I changed my config as per your suggestion and it works.

Thank you for your time!

**Comment by OneCricketeer** [comment]
Did you miss this part? 

> KAFKA_LISTENERS is a comma-separated list of listeners, and the host/ip and port to which Kafka binds to on which to listen. For more complex networking this might be an IP address associated with a given network interface on a machine. The default is 0.0.0.0, which means listening on all interfaces.

**Comment by crashinc99** [comment]
Ooops.  I was getting frustrated, and thus, I missed that.

**Comment by OneCricketeer** [comment]
Now worries. Feel free to close the issue
