### ISSUE TITLE
KAFKA_CREATE_TOPICS not supported on the latest version ?

### ISSUE THREAD

**Issue by bcashier** [wurstmeister/kafka-docker#600]
Hi,

I wanted to use: KAFKA_CREATE_TOPICS  with my docker-compose configs, but it doesn't create new topic.

I used the example provided on the Readme:

```
    environment:
      KAFKA_CREATE_TOPICS: "Topic1:1:3,Topic2:1:1:compact"
```

Any help please ?

**Comment by kushalchordiya216** [comment]
I faced a similar issue, I found out that when for some reason, it works fine when I try to use the kafka-console-consumer.sh on the individual topics, it seems to work fine, but obviously, this means that the process has to be done every time you rebuild the docker image, which is obviously not a solution

**Comment by mgomesborges** [comment]
For me it's working normally.

I advise you to do the following:

1. Stop Kafka cluster and clean up everything

```bash
docker-compose down --volumes
```

2. Prune unused Docker objects (volume)

```bash
docker volume ls

# DRIVER          VOLUME NAME
# local               1f7f...8a5
```

```bash
docker volume rm 1f7f...8a5
```

3. Hello Kafka Topic

```bash
docker-compose up -d
```

```bash
# Make sure everything is working
docker-compose ps
```

Test the producer and consumer for the created topic!

**Comment by bcashier** [comment]
Hi,

It is working with me also but send multiples error to the created topic first before recieving a sent messages !

Thank you

**Comment by ghost** [comment]
@bcashier, check out my tutorial [Apache Kafka Docker](https://github.com/MonsieurBorges/kafka-docker), I believe it can help you.

You will find two examples: Wurstmeister and Kafka-Python and Confluent Kafka and confluent-kafka-python. You can adapt it to other clients like Java or C++.

**Comment by bcashier** [comment]
@mgomesborges I already deployed Kafka, Zookeeper on my Docker. That is not a problem at all.

My question is about auto creating Kafka topic using this image :)

Anyaway thank you for your intention.

**Comment by mgomesborges** [comment]
@bcashier I understood that ;)

In the tutorial you will find out how to create a topic using `KAFKA_CREATE_TOPICS` or using a Python client.

Bonne chance !

**Comment by bcashier** [comment]
I stayed on my first idea, to create a temporary container to configure some TOPICS by checking if the Kafka server is up and running.

Thank you
