### ISSUE TITLE
Add notes for windows support

### ISSUE THREAD

**Issue by marielcherkassky** [wurstmeister/kafka-docker#601]
Hey,
I tried to create the containers(docker-desktop v2.3.0.3) on top of windows 10 pro with gitbash and I faced a few issues that I think worth mentioning in the readme for the windows users :

1)When I attached the kafka shell the following file was created under /var/run : `'docker.sock;C'`. As a result of this weird suffix, the kafka container couldnt reach out to the docker service : 
```
    $ ./start-kafka-shell.sh localhost
    bash-4.4# docker ps
    Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
 The solution was adding another / in the mapping when we attach to the container in the shell script : 

`docker run --rm -v //var/run/docker.sock:/var/run/docker.sock -e HOST_IP=$1 -e ZK=$2 -i -t wurstmeister/kafka /bin/bash`

2)Not sure if its because I'm using gitbash but I had to add winpty and change  /bin/bash to bash when I attach to the container. So the attaching command looked like the following : 
`winpty docker run --rm -v //var/run/docker.sock:/var/run/docker.sock -e HOST_IP=$1 -e ZK=$2 -i -t wurstmeister/kafka bash
`

**Comment by OneCricketeer** [comment]
You never needed to mount the socket anyway

Kafka doesn't do anything with it, and it's a Docker security whole if you do

**Comment by sscaling** [comment]
Yes, the docker socket should only be used for local dev testing if it is more convenient to do so. Generally avoid sharing this where possible - it is not needed, use-case as per the FAQ - https://github.com/wurstmeister/kafka-docker/wiki#why-is-varrundockersock-needed
