### ISSUE TITLE
can't run kafka : /bin/sh: illegal option -

### ISSUE THREAD

**Issue by iyossi** [wurstmeister/kafka-docker#607]
hi,
I just clones the project and run:
 docker-compose -f docker-compose-single-broker.yml up
and got :
_...
...
(19/21) Installing docker (18.09.8-r0)
Executing docker-18.09.8-r0.pre-install
(20/21) Installing oniguruma (6.9.4-r0)
(21/21) Installing jq (1.6-r0)
Executing busybox-1.29.3-r10.trigger
OK: 349 MiB in 74 packages
/bin/sh: illegal option -
ERROR: Service 'kafka' failed to build: The command '/bin/sh -c apk add --no-cache bash curl jq docker  && chmod a+x /tmp/*.sh  && mv /tmp/start-kafka.sh /tmp/broker-list.sh /tmp/create-topics.sh /tmp/versions.sh /usr/bin  && sync && /tmp/download-kafka.sh  && tar xfz /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz -C /opt  && rm /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz  && ln -s /opt/kafka_${SCALA_VERSION}-${KAFKA_VERSION} ${KAFKA_HOME}  && rm /tmp/*  && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk  && apk add --no-cache --allow-untrusted glibc-${GLIBC_VERSION}.apk  && rm glibc-${GLIBC_VERSION}.apk' returned a non-zero code: 2_

When I add /bin/bash -xv before calling/tmp/download-kafka.sh in the dockerfile's RUN line, then I see : 
_...
Executing busybox-1.29.3-r10.trigger
OK: 349 MiB in 74 packages
#!/bin/sh -e

+ $'\r'
/tmp/download-kafka.sh: line 2: $'\r': command not found
_# shellcheck disable=SC1091_
source "/usr/bin/versions.sh"
+ source $'/usr/bin/versions.sh\r'
: No such file or directorye 4: /usr/bin/versions.sh_

**Comment by OneCricketeer** [comment]
You don't need to build the image see #603

**Comment by iyossi** [comment]
Hi,
I didn't build it.
I just used docker compose up command, and got the error.
Later, when i modified the docker file in order to debug the problem, i
hadvto rebuild it.

Regards,
Yossi

בתאריך יום ו׳, 26 ביוני 2020, 4:08, מאת Jordan Moore ‏<
notifications@github.com>:

**Comment by OneCricketeer** [comment]
> just used docker compose up command

That does build. Notice `build: .` in the file

**Comment by sscaling** [comment]
Closing due to staleness. Issue should be easily worked around by using

```
image: wurstmeister/kafka
```

instead of 

```
build: .
```

In the docker-compose.yml
