### ISSUE TITLE
KAFKA_ADVERTISED_HOST_NAME

### ISSUE THREAD

**Issue by shipa988** [wurstmeister/kafka-docker#609]
KAFKA_ADVERTISED_HOST_NAME how i can install this env??? if docker-compose makes random ip???

**Comment by sscaling** [comment]
This is explained in many online blogs / tutorials as well as a fairly comprehensive coverage in the [Kafka Documentation](https://kafka.apache.org/documentation/#advertised.host.name). We have also created the [Connectivity Guide](https://github.com/wurstmeister/kafka-docker/wiki/Connectivity) which explains this.

As an aside, the "latest" way that is advised to configure the broker is by using the various `x.listeners` configurations (e.g. `KAFAK_ADVERTISED_LISTENERS`). However, the advertised host name might be simpler to get you started if you are struggling.
