### ISSUE TITLE
Gcloud required for creation

### ISSUE THREAD

**Issue by andyryan** [wurstmeister/kafka-docker#610]
I'm unsure if this is an issue, but since I can't find any steps regarding this in any of the documentation or tutorials, I thought to ask here.

Why do I require a Gcloud login to build Kafka with this image? 
```
kafka-docker git:(master) docker-compose up -d
Building kafka
ERROR: (gcloud.auth.docker-helper) You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials.
```
I don't want to have to set up a google cloud account just to have Kafka running in my dev environment.

**Comment by sscaling** [comment]
https://stackoverflow.com/questions/59148598/how-to-get-gcloud-auth-docker-helper-out-of-the-habit-to-hook-into-non-related-d
