### ISSUE TITLE
Please tag latest for getting KAFKA_ADVERTISED_HOST_NAME support

### ISSUE THREAD

**Issue by norrs** [wurstmeister/kafka-docker#62]
Hi

It would be great if you could tag latest with an 0.8.2.x version, so we can ensure we always checkout kafka8 and not "latest" which later can be kafka9.

Currently 8.x doesn't contain the changes in the run script for obtaining KAFKA_ADVERTISED_HOST_NAME via route -n which I would love to have without having to rebuild your image.

Would probably help the guy over at #22 as well, as the container probably registered itself using an hostname which isn't automatically available in other containers when linking it. (since kafka register the hostname in the broker id, which the client/consumer will try to connect to by reading zookeeper)

**Comment by wurstmeister** [comment]
done
