### ISSUE TITLE
Missing docker image for Apple Silicon (linux/arm64/v8)

### ISSUE THREAD

**Issue by includeno** [wurstmeister/kafka-docker#675]
Description
The Docker image is unusable on Mac OS with Apple Silicon M1 chip.

**Comment by okarahan** [comment]
Can you describe the problem further? Do you have a solution idea? I for example get this error when running docker-compose:

```
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount402167647/Dockerfile: no such file or directory
ERROR: Service 'kafka' failed to build : Build failed
```

Probably its related to the issue since I have a M1 Mac.

**Comment by includeno** [comment]
I have copyed the repo and use the GitHub Actions to create my own docker image using  openjdk:8u292-jdk. It supports linux/arm64/v8.
https://github.com/includeno/kafka-docker/blob/master/Dockerfile

**Comment by maxekman** [comment]
@includeno Your fork seems to work well. Very snappy with native Kafka on Apple Silicon. Can this be made into a PR to make the upstream support multi arch?

**Comment by includeno** [comment]
https://github.com/wurstmeister/kafka-docker/commit/82a4f74ec7808393d7eb7063ed624242697d04c7
Update openjdk image
The previous image was crashing on M1. After trying a few different
images, this one seems to solve the problem

According to the latest commit ,they wanted to resolve the M1 Mac issues but they choosed an base image which doesnt not support for M1 natively.In fact,openjdk supports for it such as openjdk:8u302-slim,you can use previous dockerfile to generate M1 natively images.

**Comment by maxekman** [comment]
Interesting, thanks for the tips.

**Comment by drewpc** [comment]
> Interesting, thanks for the tips. I hope an AArch64 image gets pushed to Docker Hub soon.

As part of my final testing for #694, I pushed all of the "tagged" versions to my Docker Hub repository.  You can reference them here if you need them until the PR is merged:
https://hub.docker.com/r/drewpc/kafka/tags
