### ISSUE TITLE
0.9.0.0 Kafka

### ISSUE THREAD

**Issue by fatlazycat** [wurstmeister/kafka-docker#68]
Any plans to upgrade to Kafka 0.9.0.0 ?

Thanks

**Comment by jasperavisser** [comment]
It seems to be really simple. Just replace 2 instance of the words 0.8.2.2 with 0.9.0.0. I tried it locally, and it works, but I'm not expert enough to know if it is optimal or possibly broken in some edge cases.

**Comment by jasperavisser** [comment]
Woohoo, wurstmeister added a 0.9.0.0 version. =)

It seems to work perfectly for me. Not yet in https://hub.docker.com/r/wurstmeister/kafka/tags/

**Comment by wurstmeister** [comment]
it's tagged now
