### ISSUE TITLE
Typo in main README.md

### ISSUE THREAD

**Issue by panc86** [wurstmeister/kafka-docker#680]
`BROKER_ID_COMMAND: "hostname | awk -F'-' '{print $$2}'"`
(example at point 2 in https://github.com/wurstmeister/kafka-docker/blob/master/README.md#broker-ids) contains 2 `$`

same as per https://github.com/wurstmeister/kafka-docker/blob/master/README.md#advertised-hostname

**Comment by OneCricketeer** [comment]
I don't think it is a typo. The first `$` escapes the second `$2`, which is passed to the system awk call.

**Comment by hennr** [comment]
Yep, the two $ seem correct for me as well.
This returns my host name: `hostname |awk -F'-' '{print $$2}'`
This does not: `hostname | awk -F'-' '{print $2}'`

Mind to close the issue, @panc86 ?

**Comment by panc86** [comment]
Thank you for checking this. I was not aware that the additional $ escapes the first.

**Comment by unematiii** [comment]
Removing extra `$` made this command work on MacOS.
