### ISSUE TITLE
Add more brokers not work

### ISSUE THREAD

**Issue by wolfwell5** [wurstmeister/kafka-docker#716]
Hi friends,

As the title. Seems don't have this command, ` docker-compose scale kafka=3` nor ` docker compose scale kafka=3`
<img width="871" alt="image" src="https://user-images.githubusercontent.com/30484860/180670952-aa360bf7-0f38-4e24-88a1-8d4c48c3e2d8.png">

**Comment by OneCricketeer** [comment]
The explanation is here https://github.com/wurstmeister/kafka-docker/wiki/Connectivity

**Comment by wolfwell5** [comment]
> The explanation is here https://github.com/wurstmeister/kafka-docker/wiki/Connectivity

thanks for replying, finally I found the solution:
**`docker-compose up -d --scale kafka=3`**

**Comment by wolfwell5** [comment]
solved, I use colima instead, maybe a little different
