### ISSUE TITLE
Kafka-connect

### ISSUE THREAD

**Issue by DiSimon** [wurstmeister/kafka-docker#725]
Hello everyone!

Did anyone use wurstmeister/kafka:2.12-2.1.1 image with an kafka-connect Image?
I am trying to use markusgulden/kafka-connect:2.12-2.2.1 but get an error during start of the tasks: 
 java.lang.NoSuchMethodError: org.apache.kafka.common.utils.Time.waitObject(Ljava/lang/Object;Ljava/util/function/Supplier;J)V

On which side could be that issue? Kafka or Kafka-connect?

Cheers,
Denis

**Comment by OneCricketeer** [comment]
If the Connect image fails, then the issue is there.

You can try mine - https://github.com/OneCricketeer/apache-kafka-connect-docker

Or just use Confluent ones

**Comment by DiSimon** [comment]
Your image works! Thanks a lot!

**Comment by OneCricketeer** [comment]
Glad to hear. Feel free to close this issue.
