### ISSUE TITLE
upgrade to support docker 1.10

### ISSUE THREAD

**Issue by jianbin-wei** [wurstmeister/kafka-docker#73]
In docker 1.10 link is deprecated and the environment variable for linked service is also deprecated [https://docs.docker.com/compose/link-env-deprecated/](https://docs.docker.com/compose/link-env-deprecated/), can we upgrade this to use the new network feature?

**Comment by gigafone** [comment]
This *may* be related, but I'm not sure.

I'm trying out kafka-docker with Docker 1.10 from a version 2 docker-compose.yml file. Here is a snippet I want to point out:

```
kafka_1     | [2016-02-09 22:25:09,764] INFO KafkaConfig values:
kafka_1     | 	advertised.host.name = null
kafka_1     | 	metric.reporters = []
kafka_1     | 	quota.producer.default = 9223372036854775807
kafka_1     | 	offsets.topic.num.partitions = 50
kafka_1     | 	log.flush.interval.messages = 9223372036854775807
kafka_1     | 	auto.create.topics.enable = true
kafka_1     | 	controller.socket.timeout.ms = 30000
...
kafka_1     | 	quota.window.num = 11
kafka_1     | 	zookeeper.connect = 172.17.0.2:2181
kafka_1     | 	authorizer.class.name =
kafka_1     | 	num.replica.fetchers = 1...
```

I think the lack of an assigned `zookeeper.connect` address is a problem. I suspect this leads to Kafka not starting. Here's the log from `docker-compose up` from my application:

```
kafka_1     | [2016-02-09 22:17:12,454] FATAL Fatal error during KafkaServerStartable startup. Prepare to shutdown (kafka.server.KafkaServerStartable)
kafka_1     | org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 6000
kafka_1     | 	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1223)
kafka_1     | 	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:155)
kafka_1     | 	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:129)
kafka_1     | 	at kafka.utils.ZkUtils$.createZkClientAndConnection(ZkUtils.scala:89)
kafka_1     | 	at kafka.utils.ZkUtils$.apply(ZkUtils.scala:71)
kafka_1     | 	at kafka.server.KafkaServer.initZk(KafkaServer.scala:278)
kafka_1     | 	at kafka.server.KafkaServer.startup(KafkaServer.scala:168)
kafka_1     | 	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:37)
kafka_1     | 	at kafka.Kafka$.main(Kafka.scala:67)
kafka_1     | 	at kafka.Kafka.main(Kafka.scala)
kafka_1     | [2016-02-09 22:17:12,459] INFO shutting down (kafka.server.KafkaServer)
sp1_kafka_1 exited with code 1
```

This is different from how the output looks when I run against a version 1 docker-compose.yml file; in which I see:

```
kafka_1     | 	zookeeper.connect = 172.17.0.2:2181
```

And this work fine after that.

So, this makes me wonder/suspect if `zookeeper.connect` should be handled differently now that version 2 docker-compose.yml files exist. I think I remember reading from the docker docs that one you use a version 2 compose file, it requires that transitive docker-compose files be version 2 as well.

**Comment by jianbin-netskope** [comment]
Inside start-kafka.sh, I use following to get zookeeper.connect populated.

`
if [[ -z "$KAFKA_ZOOKEEPER_CONNECT" ]]; then
    export KAFKA_ZOOKEEPER_CONNECT=$(docker ps --filter 'label=com.docker.compose.service=zookeeper' --format '{{.Names}}' | awk '{{printf "%s:2181\n", $1}}' | paste -sd ,)
fi
`

**Comment by gigafone** [comment]
Thanks. This fixed the problem best I can tell.

**Comment by willfarrell** [comment]
I got it working with the latest version of docker (1.11). The dockerfile was loading docker v1.9. This is the latest version ported to alpine. Due to some changes in docker v1.10, the start script had some issues. I rewrote to the Dockerfile using the approved java image and a few other tweaks.

I also used @jianbin-wei snippet above.

```Dockerfile
FROM java:8-jre

MAINTAINER Wurstmeister 

RUN apt-get update \
	&& apt-get upgrade -y \
	&& apt-get install -y coreutils curl unzip wget jq net-tools \
	&& curl -sSL https://get.docker.com/ | sh

ENV KAFKA_VERSION="0.9.0.1" SCALA_VERSION="2.11"
ENV KAFKA_HOME /opt/kafka_${SCALA_VERSION}-${KAFKA_VERSION}

ADD download-kafka.sh /tmp/download-kafka.sh

RUN /tmp/download-kafka.sh \
	&& tar xfz /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz -C /opt \
	&& rm /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz

ADD broker-list.sh /usr/bin/broker-list.sh
ADD create-topics.sh /usr/bin/create-topics.sh
ADD start-kafka.sh /docker-entrypoint.sh

VOLUME ["/kafka"]

# Use "exec" form so that it runs as PID 1 (useful for graceful shutdown)
CMD ["/docker-entrypoint.sh"]
```

Not as small as it would be in alpine, but it works.

**Comment by wurstmeister** [comment]
done (https://github.com/wurstmeister/kafka-docker/commit/cba65a10cda6759d1676c3fb46731e4c4aa560ee)
