### ISSUE TITLE
Whenever I try to execute any Kafka command, it is hanging and timing out

### ISSUE THREAD

**Issue by opencmit2** [wurstmeister/kafka-docker#751]
"I am experiencing issues with version 3.51 of Kafka. Whenever I try to execute any Kafka command, it is hanging and timing out. Here is an example of the problem: .
![c5ce865acf70b1a90a6661cbbc8531f](https://github.com/user-attachments/assets/bab56fb7-e14d-40f0-859f-86d665dbb3c7)

[root@kafka18 kraft]# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
[root@kafka18 kraft]# uname -r
3.10.0-957.el7.x86_64

[root@kafka18 kraft]# java --version
java 11.0.18 2023-01-17 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.18+9-LTS-195)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.18+9-LTS-195, mixed mode)

kafka version ：kafka_2.13-3.5.0

**Comment by tongrui0722** [comment]
Here is my system configuration and Java version. The runtime duration for executing the test command is shown in the image. Please optimize the system parameters accordingly. If a virtual machine is being employed, kindly review the virtual machine software factors for potential improvements.
![微信图片_20240914172552](https://github.com/user-attachments/assets/a9274721-1fbb-4ade-8da2-2e122bc274f9)
[root@kafka01 ~]# uname -r 
3.10.0-1160.119.1.el7.x86_64
[root@kafka01 ~]# java --version
java 11.0.18 2023-01-17 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.18+9-LTS-195)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.18+9-LTS-195, mixed mode)

**Comment by opencmit2** [comment]
ok,thanks
