### ISSUE TITLE
why not add a docker volume to save the kafka log?

### ISSUE THREAD

**Issue by asdfsx** [wurstmeister/kafka-docker#8]
I think add a volume to save the kafka log should be better

**Comment by eudaimos** [comment]
I agree.

Currently without a specific mount for log volumes, you can do this by mounting a volume to `/kafka`.  I use a "data volume container" that I start first which has a volume for `/kafka`, then I use `volumes_from:` to attach to it for persistence (`--volumes-from` in `docker run` command)

**Comment by stonefury** [comment]
Hi all.  Yes, I am working with this image as well. First, thank you to wurstmeister for this excellent image. It has saved me a lot of time writing scripts around installing/configuring Kafka.

Ok, so yes, I also think we need a persistent volume.  My question is, if the docker container is lost, what would be the recovery procedure to re-use the old volume?

Dumb question. Can I stop/start the broker container without any adverse affects? Will it just pick up where it left off?

I'm working on using these two containers to create an Kafka cluster on AWS. If I have anything to share I will be sure to do so.

cheers

**Comment by nwkeeley** [comment]
@stonefury any luck with a docker volume?

**Comment by ibizaman** [comment]
You can simply add this to docker compose:
```yaml
        volumes:
            - ./kafka-logs:/var/lib/kafka
```
It works as expected: everything is saved in the `./kafka-logs` folder and kafka picks up afterwards form where it was.

**Comment by wurstmeister** [comment]
Thanks @ibizaman for the answer.

**Comment by findnanda** [comment]
Adding this 
volumes:
            - ./kafka-logs:/var/lib/kafka
doesn't seem to work. it created a folder on the host -machine but didn't put the files in there. I can see that logs files in the container in /kafka/kafka-logs
