### ISSUE TITLE
missing configuration advertised.port 

### ISSUE THREAD

**Issue by asnir** [wurstmeister/kafka-docker#81]
kafka_1     | [2016-03-10 10:12:15,904] FATAL  (kafka.Kafka$)
kafka_1     | org.apache.kafka.common.config.ConfigException: Invalid value  for configuration advertised.port: Not a number of type INT
kafka_1     |   at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:253)
kafka_1     |   at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:145)
kafka_1     |   at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:49)
kafka_1     |   at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:714)
kafka_1     |   at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:698)
kafka_1     |   at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:695)
kafka_1     |   at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:28)
kafka_1     |   at kafka.Kafka$.main(Kafka.scala:58)
kafka_1     |   at kafka.Kafka.main(Kafka.scala)
kafkadocker_kafka_1 exited with code 1

**Comment by nanounanue** [comment]
I am having the same issue, when I tried to solve it defining `KAFKA_ADVERTISED_HOST_NAME` and `KAFKA_ADVERTISED_PORT` in `docker-compose.yml` it (apparently) worked, but now I am having the problems described in http://stackoverflow.com/questions/35861501/kafka-in-docker-not-working

By the way I am using `ubuntu`

**Comment by asnir** [comment]
You are welcome to try the [proposed solution](https://github.com/wurstmeister/kafka-docker/pull/82/files)

**Comment by nanounanue** [comment]
@asnir What is the proposed solution if i want to have more than one kafka running?

**Comment by wurstmeister** [comment]
Hi, 

@nanounanue in your SO post your compose file is not correct as far as i can tell:

```
zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - "2181:2181"

kafka:
  image: wurstmeister/kafka
 # hostname: kafka
  ports:
    - "9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: "kafka"
    KAFKA_ADVERTISED_PORT: "9092"
    KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
```

i.e. the port you get is ```0.0.0.0:32768->9092/tcp``` but you set your advertised port to 9092. 

the way the advertised port configuration works is that we either:
- take it from the docker environment if it is not specified and the docker socket is mounted (i.e. we can execute docker inside docker [n.b. the stack trace in this issue usually indicates that docker in docker can't be run]) - see https://github.com/wurstmeister/kafka-docker/blob/master/start-kafka.sh#L7 
- or we take the value specified in the compose file.

in your example you can see that your port is ```0.0.0.0:32768->9092/tcp```, so setting the advertised port to 9092 won't work. 

to fix it, either fix the port i.e. 
```
ports:
    - "9092:9092"
```

or remove the ```KAFKA_ADVERTISED_PORT``` configuration and add the mounting of the docker socket as in https://github.com/wurstmeister/kafka-docker/blob/master/docker-compose-single-broker.yml

in fact, if you simply change ```KAFKA_ADVERTISED_HOST_NAME``` in https://github.com/wurstmeister/kafka-docker/blob/master/docker-compose-single-broker.yml
 to your ubuntu host IP things should work.

Let me know if this helps.

**Comment by alexbuce** [comment]
after the above step the port is accessible  outside of the container 
if we set the port then
"docker-compose scale kafka=2" is not working. it fails with below error.

Cannot start service kafka: driver failed programming external connectivity on endpoint

**Comment by onieio** [comment]
My issue was with the Kafka service, After deleting the pod I forgot to remove the service from the 'kubectl get services --namespace pod_ns'. Once the service removed everything works well.
