### ISSUE TITLE
Trouble getting started

### ISSUE THREAD

**Issue by neverfox** [wurstmeister/kafka-docker#83]
I must be missing something but I can't get anything to work on once the containers are running. I followed the instructions by setting `KAFKA_ADVERTISED_HOST_NAME` to the output of

`docker-machine ip default`

Then I did

`docker-compose up -d`

Everything is running according to `docker ps` so I then proceeded to do

`kafka-topics --list --zookeeper $SOME-IP:2181`

where `$SOME-IP` is the output of

`docker inspect --format '{{ .NetworkSettings.IPAddress }}' kafkadocker_zookeeper_1`.

It just times out. Is that right? Should be using a different IP in either place?

**Comment by arbitrary-dev** [comment]
Same problem, dunno what to pass as ZK_HOST value to start-kafka-shell.sh and therefore can't go with Testing part of Wiki.

**Comment by arbitrary-dev** [comment]
It seems like you should use as DOCKER_HOST_IP and ZK_HOST the same value as in KAFKA_ADVERTISED_HOST_NAME (excluding localhost and 127.0.0.1 as they're not applicable on all systems).

**Comment by sscaling** [comment]
@neverfox  - to access zookeeper you will need to expose the port on an accessible interface. If for example, you are using the example [docker-compose.yml](https://github.com/wurstmeister/kafka-docker/blob/master/docker-compose.yml) file, you will see zookeeper is published to port 2181. 

Depending if you're on mac / linux / windows docker will be bound to a specific interface (physical / virtual). If you are using boot2docker, I think the IP address is `192.168.99.100` by default, but docker for mac and linux uses localhost `127.0.0.1`.

RE: 
> docker inspect --format '{{ .NetworkSettings.IPAddress }}' kafkadocker_zookeeper_1

This will return the internal IP for the zookeeper container, which is not publicly addressable by default.

HTH. No updates in 1 year so closing.
