### ISSUE TITLE
Document for multi-node deployment

### ISSUE THREAD

**Issue by yupengfei** [wurstmeister/kafka-docker#91]
I want to deploy kafka on a multi-node cluster, is there any document?

**Comment by ScottChapman** [comment]
I think basically you use scale=n either on the command line or in your compose.yml
https://github.com/docker/compose/issues/1661

**Comment by ScottChapman** [comment]
My question is related though, if I want to always launch a 3-node cluster, but want to assign consecutive ports to kafka (9092, 9093, 9094) how would one do that in the compose.yml exactly?

**Comment by wurstmeister** [comment]
@yupengfei http://wurstmeister.github.io/kafka-docker/ gives an example for how to setup a multi node cluster 
@ScottChapman please see https://github.com/docker/compose/issues/722

**Comment by dead10ck** [comment]
@wurstmeister the example you linked doesn't really help. Is it possible to scale the `kafka` service and reach the resulting cluster from the host machine? We can't advertise the `localhost` hostname, and we can't bind port 9092 to the host machine, so I'm not really sure how to accomplish this. An example `docker-compose.yml` would be great.
