### ISSUE TITLE
issues when I run docker compose

### ISSUE THREAD

**Issue by constantlearner** [wurstmeister/kafka-docker#93]
Step 3 : RUN apk add --update unzip wget curl docker jq coreutils
 ---> Running in 4f3fffc6d5c3
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.3/main: operation timed out
WARNING: Ignoring APKINDEX.5a59b88b.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.3/community: operation timed out
WARNING: Ignoring APKINDEX.7c1f02d6.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  coreutils (missing):
    required by: world[coreutils]
  curl (missing):
    required by: world[curl]
  docker (missing):
    required by: world[docker]
  jq (missing):
    required by: world[jq]
  unzip (missing):
    required by: world[unzip]
  wget (missing):
    required by: world[wget]
ERROR: Service 'kafka' failed to build: The command '/bin/sh -c apk add --update unzip wget curl docker jq coreutils' returned a non-zero code: 6

**Comment by wurstmeister** [comment]
Hi,

this looks like a network issue on your side. 
can you download ```http://dl-cdn.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz``` from the host you are running the build on?

Thanks

**Comment by Jobs92** [comment]
Hi,

I had the same issue, check your proxy settings

**Comment by Ox24** [comment]
getting the same error.. any other solutions on that? I checked proxy and i can manually download  `http://dl-cdn.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz`

**Comment by constantlearner** [comment]
I built outside proxy it works

**Comment by Ox24** [comment]
what do you mean 

> I built outside proxy it works

i dont get it :)

**Comment by constantlearner** [comment]
I was facing this issue when i was trying to build inside corporate proxy
inside my organization.When i went to home network it worked

**Comment by Ox24** [comment]
i will try it, thx.

**Comment by arijoon** [comment]
Is there a way to get around this behind a corporate proxy? I've tried setting proxies for docker, host machine, guest machine and can access it through the proxy for sure.

**Comment by datoml** [comment]
If anyone comes around this problem, this solution worked for me.
Open up the docker-compose.yml and change the build line to this:
```
build:
  context: .
  args:
    http_proxy: http://your-proxy
```
The **http://** is important here!

**Comment by Namphibian** [comment]
This issue is due to the apk not getting proxy credentials when you run docker up.  If you are behind corporate proxy this is a pain as the docker proxy settings does NOT propagate to the apk file.

As @datoml  mentions adding the proxy settings to the docker-compose.yml will alleviate this problem. @constantlearner  we should add this to the wiki to help people troubleshoot this issue.

See my modified docker-compose.yml below:
`version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: 
      context: .
      args:
        http_proxy: http://b-app.dmz:8080
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.4
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
`
