### ISSUE TITLE
download-kafka.sh: no such file or directory

### ISSUE THREAD

**Issue by huylv** [wurstmeister/kafka-docker#94]
I get the following error when running `docker-compose up -d`.

    Step 5 : ADD download-kafka.sh /tmp/download-kafka.sh
    ERROR: Service 'kafka' failed to build: lstat download-kafka.sh: no such file or directory

Please advise. Thanks.

**Comment by wurstmeister** [comment]
Hi,

can you please list all steps for reproducing this issue. 

Thanks

**Comment by huylv** [comment]
Hi. Here are steps to reproduce the issue:

1. Download `docker-compose.yml` from this repo to the current directory.
2. Run `docker-compose up -d`, error:

```
Creating network "docker_default" with the default driver
Building kafka
ERROR: Cannot locate specified Dockerfile: Dockerfile
```

3. Download `Dockerfile` from this repo to the current directory
4. Run `docker-compose up -d` again, error:

```
Building kafka
Step 1 : FROM anapsix/alpine-java
latest: Pulling from anapsix/alpine-java
e110a4a17941: Pull complete
557e28d14ef8: Pull complete
Digest: sha256:d70f883848d66a9431fd2954a1ee742ce88df18d40e9ab8d0ed1e07025877a72
Status: Downloaded newer image for anapsix/alpine-java:latest
 ---> eb441fe6d547
Step 2 : MAINTAINER Wurstmeister
 ---> Running in e9281bfdac08
 ---> 5b0a080cc9e4
Removing intermediate container e9281bfdac08
Step 3 : RUN apk add --update unzip wget curl docker jq coreutils
 ---> Running in 79a33eea050d
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
(1/19) Installing libattr (2.4.47-r4)
(2/19) Installing libacl (2.2.52-r2)
(3/19) Installing coreutils (8.25-r0)
(4/19) Installing libssh2 (1.7.0-r0)
(5/19) Installing libcurl (7.49.1-r0)
(6/19) Installing curl (7.49.1-r0)
(7/19) Installing libmnl (1.0.3-r1)
(8/19) Installing libnftnl-libs (1.0.5-r0)
(9/19) Installing iptables (1.6.0-r0)
(10/19) Installing expat (2.1.1-r1)
(11/19) Installing pcre (8.38-r1)
(12/19) Installing git (2.8.3-r0)
(13/19) Installing xz-libs (5.2.2-r1)
(14/19) Installing xz (5.2.2-r1)
(15/19) Installing libseccomp (2.3.1-r0)
(16/19) Installing docker (1.11.1-r0)
Executing docker-1.11.1-r0.pre-install
(17/19) Installing jq (1.5-r1)
(18/19) Installing unzip (6.0-r1)
(19/19) Installing wget (1.17.1-r1)
Executing busybox-1.24.2-r9.trigger
Executing glibc-bin-2.23-r3.trigger
OK: 116 MiB in 39 packages
 ---> 546029e6cb3a
Removing intermediate container 79a33eea050d
Step 4 : ENV KAFKA_VERSION "0.10.0.0" SCALA_VERSION "2.11"
 ---> Running in b9817aca21e0
 ---> 5f942d667d13
Removing intermediate container b9817aca21e0
Step 5 : ADD download-kafka.sh /tmp/download-kafka.sh
ERROR: Service 'kafka' failed to build: lstat download-kafka.sh: no such file or directory
```

**Comment by wurstmeister** [comment]
Hi, 

this docker compose file builds a docker image, so you should clone the whole repo rather than download individual files. 

of course, if you don't want to build, simply point your docker compose file at a pre-built image (see https://hub.docker.com/r/wurstmeister/kafka/tags/)

**Comment by huylv** [comment]
Oh, I see. After changing from `build: .` to `image: wurstmeister/kafka` in `docker-compose.yml` it works now. Thank you so much.

**Comment by hmusavi** [comment]
I had the same problem and it turned out to be caused by download-kafka.sh having Windows style EOL (CRLF instead of LF) when cloned. If you are running on a Windows machine, make sure that you configure git with core.autocrlf false.

`    git config --global core.autocrlf true
`
