### ISSUE TITLE
Support for multiple Zookeepers?

### ISSUE THREAD

**Issue by ScottChapman** [wurstmeister/kafka-docker#96]
This seems to work great for dev/test cluster. But for use in a production env one would want to create multiple zookeepers as well, and plan to support that?

**Comment by harryge00** [comment]
I think this has already been supported?
use environmental variable: `KAFKA_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2181,zoo3:2181`, for example

**Comment by wurstmeister** [comment]
thanks for the answer @harryge00.
