### ISSUE TITLE
JMX remote connection with jconsole doesn't work anymore

### ISSUE THREAD

**Issue by markuslamm** [wurstmeister/kafka-docker#98]
Hi!

Until commit f32ebdc7c11c6cf125379878432f6a5816b5b03d (Merge PR #77 ) it was possible to connect to Kafka remotely via jconsole(172.17.0.3:9997) with the given config:

kafka:
  image: wurstmeister/kafka
  ports:
    - "9092:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: localhost
    KAFKA_CREATE_TOPICS: "testtopic:1:1"
    JMX_PORT: 9997
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

After the the update to 0.10, docker-compose v2 and jmx adjustments the connection(172.19.0.3:9997) is refused.

Do I miss something? Thanks in advance!

**Comment by wurstmeister** [comment]
looks like the problem is https://github.com/wurstmeister/kafka-docker/commit/a6dbce0e71945e77bc60980422183e5c0d454bd8. I've reverted the change. Please let me know if this fixes the issue

**Comment by markuslamm** [comment]
it works, I can connect with jsonsole again. but now there is an exception concerning jmx:

`[2016-06-10 08:57:37,686] INFO [Kafka Server 1001], started (kafka.server.KafkaServer)
kafka_1      | creating topics: testtopic:1:1
kafka_1      | Error: Exception thrown by the agent : java.rmi.server.ExportException: Port already in use: 9997; nested exception is: 
kafka_1      | 	java.net.BindException: Address already in use
`

**Comment by wurstmeister** [comment]
i've done a quick test with https://github.com/wurstmeister/kafka-docker/commit/2857d50e073b4bdb86e740093a418e1f0b338edd which works

**Comment by markuslamm** [comment]
works like a charm, thanks a lot!
