### ISSUE TITLE
Is this going to work with docker 1.11.2?

### ISSUE THREAD

**Issue by joshuacalloway** [wurstmeister/kafka-docker#99]
I don't see a /var/run/docker.sock on docker 1.11.2 but I see this in the volume mappings for docker-compose.yml

**docker 1.11.2**
2usmcalloway:kafka_2.11-0.10.0.0 calloway$ docker -v
Docker version 1.11.2, build b9f10c9
2usmcalloway:kafka_2.11-0.10.0.0 calloway$ ls /var/run/do*
ls: /var/run/do*: No such file or directory

**docker-compose.yml**
volumes:
      - /var/run/docker.sock:/var/run/docker.sock

**Comment by wurstmeister** [comment]
Hi, 

 
```
Boot2Docker version 1.11.2, build HEAD : a6645c3 - Wed Jun  1 22:59:51 UTC 2016
docker@local:~$ docker --version
Docker version 1.11.2, build b9f10c9
docker@local:~$ ls /var/run/docker.sock
/var/run/docker.sock
```

It would help if you could provide a bit more information, e.g. OS, docker configuration, etc

Thanks

**Comment by sscaling** [comment]
closing. no response in 1.5 years
